### PR TITLE
Add image lint tests

### PR DESCRIPTION
**Pull request by cheshire137**
Whoops, this got approved as #5 but I merged it into `add-testing` instead of `master`.

### CODE REVIEW

**Comment by dienlei** [comment]
Listen on Work san. Presse on Mann in Office Danks Andreas

**Review by Hoove391 — COMMENTED** [review]
good

**Review by MattOoszek — COMMENTED** [review]
### ooo###

**Comment by Bell7777** [comment]
Would like to review

**Review by tigressma — COMMENTED** [review]
https://github.com/tigressma/generate/actions/workflows/pull_request.yml?query=is%3Aneutral+actor%3Atigressma+event%3Apush

**Comment by tigressma** [comment]
Pig

**Comment by sameanpum** [comment]
#18

**Comment by sameanpum** [comment]
#18

**Comment by sameanpum** [comment]
#18

**Comment by sameanpum** [comment]
#1

**Comment by sameanpum** [comment]
#18

**Review by noelportillo — COMMENTED** [review]
The first time we had to go

**Pull request merged**
