### PR TITLE
Added Lance Game Engine

### PR DESCRIPTION
**Pull request by namel**
### Thank you for contributing! Please confirm the following:

- [ x ] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [ ] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

I do have an affiliation to the project I am suggesting, but I’m hoping that it brings enough value to the list.  It’s an open source project and I’ve been working on it for almost two years. 

### Which change are you proposing?

  - [ x ] Suggesting edits to an existing topic or collection
  - [ ] Curating a new topic or collection
  
---------------------------------------------------------------------

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288)
- [ x ] Content (and my changes are in `index.md`)

Please explain why these changes are necessary:

Listing a new game engine for JavaScript .

### Curating a new topic or collection

- [ ] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [ ] My folder contains a `*.png` image (if applicable) and `index.md`
- [ ] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

Please explain why you think this topic or collection should be curated:

---------------------------------------------------------------------

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by sexwanthxx** [comment]
HI want explore

**Comment by sexwanthxx** [comment]
Yes nice compani if like come

**Comment by denettehay** [comment]
This is really my account someone hack my phone and somehow y'all got it
look at email and name and phone number. Look at info. I'm just trying to
get back what's rightfully mine. Thank you.
 This was first time doing this it was fun.

**Comment by denettehay** [comment]
I'm not a programmer this is my second time trying to get my account. I'm just looking what needs to be done to get my money back. I'm not trying to be in your project and I'm sorry. I never heard of this website until 3-4 days ago. But it is fun to learn, I was just reading y'all inputs. Like I said I'm sorry and I was having fun until it my phone froze. But I will work with y'all and learn. Was I doing good for the first time.😃

**Comment by denettehay** [comment]
Ok I will like to do that it was fun y'all were three deep changing codes, it definitely was a rush. So can I get my money, but I still want to learn. If you help me get this new block y'all can keep what y'all made or whatever. I can't pull money off old block because it was changed, so can we work something out. 😋

**Comment by Londonclog** [comment]
Close iPhone hack on these games. Close Lane 
Games! This is spam

**Comment by Londonclog** [comment]
Thank you this has been an on going issue.

**Comment by Londonclog** [comment]
Close all/tree master Docs/my JavaScript corrupted. Close all these documents.

**Comment by talsafran** [comment]
Hi @namel  thanks for the contribution ❤️. Unfortunately, as per our [contribution guidelines](https://github.com/github/explore/blob/master/CONTRIBUTING.md#guidelines), we don't allow self promotion if you are a maintainer of the project:

> Unaffiliated with the project (not self-promoting as e.g. a maintainer, creator, contractor or employee)

We do this so that projects get curated if there is enough support/activity in the community. Thank you!

**Pull request closed without merging**
