### PR TITLE
added Rucky

### PR DESCRIPTION
**Pull request by hackieNull**
### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [x] Suggesting edits to an existing topic or collection
  - [ ] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---------------------------------------------------------------------

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288, size <= 75 kB)
- [x] Content (and my changes are in `index.md`)

> Added topic `Rucky` to collection `Made-in-india`.

### Curating a new topic or collection

- [ ] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [ ] My folder contains a `*.png` image (if applicable) and `index.md`
- [ ] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

> This is a great app from India and it can be featured in Made in India collections because of its uniqueness. It is first Made In India Android based security tool that even featured on Kali Linux Nethunter and is used by many security folks like me.

### Something that does not neatly fit into the binary options above

- [ ] My suggested edits are not about an existing topic or collection, or at least not a single one
- [ ] My suggested edits are not about curating a new topic or collection, or at least not a single one
- [ ] My suggested edits conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

> Please replace this line with an explanation of your proposed changes.

---------------------------------------------------------------------

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Review by wes9971 — APPROVED** [review]

**Review by wes9971 — APPROVED** [review]

**Comment by mvkaran** [comment]
Thanks for your contribution @hackieNull. We would need a few changes on this PR:
- Please move the contribution to the end of the list.
- The `rucky` topic doesn't seem to be used on any repositories, so curating it would not be useful for the community. Please remove this. Once there is enough usage of this by the community, it can be curated again if required.

**Review by kenyonj — CHANGES_REQUESTED** [review]
Thanks for the contribution. However, this is not an appropriate addition to the curated topics section as this is an app. There are no other repositories associated with this topic, github.com/topics/rucky.

Please update this PR removing the topic addition/image.

Also, we are only accepting additions to collection lists with the new item appended to the end of the list. Please make this change as well.

**Review by hackieNull — COMMENTED** [review]
Rucky can be extended with modules that communicate to the app via network socket, and such socket code exist but are not that famous. Maybe lets add this to the list, so community can build and contribute. Some kali linux community are already so contributing to such modules.

**Comment by kenyonj** [comment]
@hackieNull 
Per our contribution guidelines (seen here: https://github.com/github/explore/blob/main/CONTRIBUTING.md#curating-a-new-topic-or-collection):
> Valuable topics, for example, include those that are already widely used by repositories and could benefit from the addition of important information.

`rucky` is not a widely used topic, in fact zero repositories have it as a topic currently. 

This does not mean it can't be added to the collection. If you would still like to add it to the `made-in-india` collection, please remove the topic and image from this PR.

**Comment by hackieNull** [comment]
Did the changes, how these changes work. Thanks.

**Review by kenyonj — APPROVED** [review]
💯 🍨 Thank you for your contribution! I'll merge this in as soon as CI is 🍏

**Comment by kenyonj** [comment]
@hackieNull can you update your fork with the latest `master`? There is a fix there for the failing CI test.

**Comment by hackieNull** [comment]
Done

**Pull request merged**
