### PR TITLE
Oracle database and spotify topic

### PR DESCRIPTION
**Pull request by AyushShahh**
### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---------------------------------------------------------------------

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288, size <= 75 kB)
- [ ] Content (and my changes are in `index.md`)

> Please replace this line with an explanation of why you think these changes should be made.

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

> Spotify is a popular music, video and podcast service. Oracle database is used by a lot of companies. They should be curated on Github.

### Something that does not neatly fit into the binary options above

- [ ] My suggested edits are not about an existing topic or collection, or at least not a single one
- [ ] My suggested edits are not about curating a new topic or collection, or at least not a single one
- [ ] My suggested edits conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

> Please replace this line with an explanation of your proposed changes.

---------------------------------------------------------------------

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by kenyonj** [comment]
Hi @AyushShahh
Please open 1 PR per topic or collection creation/edit.

Thank you!

**Comment by nholden** [comment]
Do you think we need to have separate "Oracle" and "Oracle Database" topics? It feels like one could be an alias of the other.

**Comment by AyushShahh** [comment]
@nholden I think yes because they are different. You can check Wikipedia for reference
[Oracle](https://en.wikipedia.org/wiki/Oracle_Corporation)
[Oracle Database](https://en.wikipedia.org/wiki/Oracle_Database)
Tell me your views

**Comment by nholden** [comment]
I agree that Oracle Corporation and Oracle Database are different, but [browsing through the repositories with the `oracle` topic](https://github.com/topics/oracle), it seems like most of them are dealing with Oracle Database. What do you think about replacing the `oracle` topic with `oracle-database` and adding an `oracle` alias?

**Comment by AyushShahh** [comment]
@nholden It seems right. I will add oracle as an alias inside Oracle Database topic. The PR with Oracle topic is already merged so should I delete the oracle topic and open a new PR?

**Comment by nholden** [comment]
> should I delete the oracle topic and open a new PR?

Feel free to delete the Oracle topic in this PR. Thanks for asking!

**Comment by AyushShahh** [comment]
@nholden I have committed the changes. Now just waiting for the checks to pass

**Review by nholden — APPROVED** [review]
Thanks for the edits on this one, @AyushShahh!

**Pull request merged**
