### PR TITLE
Add DataOps topic

### PR DESCRIPTION
**Pull request by ravisuhag**
### Please confirm this pull request meets the following requirements:

- [X] I followed the contributing guidelines: <https://github.com/github/explore/blob/master/CONTRIBUTING.md>.
- [X] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [X] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---

### Curating a new topic or collection

- [X] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [X] My folder contains a `*.png` image (if applicable) and `index.md`
- [X] All required fields in my `index.md` conform to the Style Guide and API docs: <https://github.com/github/explore/tree/master/docs>

> DataOps has emerged as a dedicated topic similar to DevOps in the last few years. Curating this topic will help to find tools around DataOps methodology.

### CODE REVIEW

**Review by octokatherine — APPROVED** [review]
Thank you for the contribution!

**Comment by ravisuhag** [comment]
@octokatherine Thanks. Changes are not reflected yet on explore page. Does it take time?

**Comment by octokatherine** [comment]
@ravisuhag you should see it now

**Comment by ravisuhag** [comment]
> @ravisuhag you should see it now
@octokatherine 
No luck so far. Got something to do with cache or is there a background process independent of GitHub workflows? I think all the changes that happened in the repo in the last 2-3 days are not reflected yet.

**Pull request merged**
