### PR TITLE
Add topic: fedora

### PR DESCRIPTION
**Pull request by kbdharun**
### Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: <https://github.com/github/explore/blob/main/CONTRIBUTING.md>.
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288, size <= 75 kB)
- [ ] Content (and my changes are in `index.md`)

> Please replace this line with an explanation of why you think these changes should be made.

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: <https://github.com/github/explore/tree/main/docs>

> The topic should be curated as Fedora is one of the widely used Linux distributions and has more than 1000 repositories in this topic already.

### Something that does not neatly fit into the binary options above

- [ ] My suggested edits are not about an existing topic or collection, or at least not a single one
- [ ] My suggested edits are not about curating a new topic or collection, or at least not a single one
- [ ] My suggested edits conform to the Style Guide and API docs: https://github.com/github/explore/tree/main/docs

> Please replace this line with an explanation of your proposed changes.

---

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by ipc103** [comment]
@kbdharun thanks for adding this one, too. Is there an image you could include? Not 100% required, but the topics look a little nicer with a logo 😄

**Comment by kbdharun** [comment]
> @kbdharun thanks for adding this one, too. Is there an image you could include? Not 100% required, but the topics look a little nicer with a logo 😄 

Actually, The Fedora logo isn't 288 x 288, if we need one specifically for this size, then I need to place a request too the logo team, I will mail them today, will get back to this PR when I receive a reply (probably within a month).

**Comment by ipc103** [comment]
👍 - that makes sense. Yes the size is a hard requirement - thanks for following up with them ❤️

**Comment by Morizt777** [comment]
All are great and perfect💯💯

**Review by ipc103 — APPROVED** [review]

**Comment by ipc103** [comment]
Looks good - thanks for taking care of that so quickly!

**Pull request merged**
