### PR TITLE
Added Topics (Ionic, Adobe Acrobat) and Collections (Made in CH)

### PR DESCRIPTION
**Pull request by Sigmale1000**
### Please confirm this pull request meets the following requirements:

- [👍] I followed the contributing guidelines: <https://github.com/github/explore/blob/main/CONTRIBUTING.md>.
- [👍] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: <https://github.com/github/explore/tree/main/docs>

> Ionic is a cool UI-Toolkit which I think isn't listed.

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Review by octokatherine — COMMENTED** [review]
👋 thanks for the contribution

there are a few errors in CI that need to be addressed, then we can merge

```
1) Failure:
topics::ionic topic#test_0019_has at most one image with the right name, type, and dimensions [/home/runner/work/explore/explore/test/topics_test.rb:229]:
topic images should be 288px wide.
Expected: 288
  Actual: [22](https://github.com/github/explore/actions/runs/3731725725/jobs/6330275653#step:6:23)5

  2) Failure:
topics::ionic topic#test_0014_has a matching topic key [/home/runner/work/explore/explore/test/topics_test.rb:169]:
'topic' key should match the directory name 'ionic'.
Expected: "ionic"
  Actual: "ui-toolkits"

  3) Failure:
topics::ionic topic#test_0025_follows the Topic Page Style Guide [/home/runner/work/explore/explore/test/topics_test.rb:314]:
Use open source without a hyphen.
Expected "Ionic framework is an open-source UI toolkit for building performant, high-quality mobile apps, desktop apps, and progressive web apps using web technologies such as HTML, CSS, and JavaScript based on either Angular, React or Vue." to not include "open-source".

  4) Failure:
topics::ionic topic#test_0019_has at most one image with the right name, type, and dimensions [/home/runner/work/explore/explore/test/topics_test.rb:229]:
topic images should be 288px wide.
Expected: 288
  Actual: 225

  5) Failure:
topics::ionic topic#test_0014_has a matching topic key [/home/runner/work/explore/explore/test/topics_test.rb:169]:
'topic' key should match the directory name 'ionic'.
Expected: "ionic"
rake aborted!
  Actual: "ui-toolkits"
Command failed with status (1)

/home/runner/work/explore/explore/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
  6) Failure:
/opt/hostedtoolcache/Ruby/3.1.2/x64/bin/bundle:[25](https://github.com/github/explore/actions/runs/3731725725/jobs/6330275653#step:6:26):in `load'
topics::ionic topic#test_0025_follows the Topic Page Style Guide [/home/runner/work/explore/explore/test/topics_test.rb:[31](https://github.com/github/explore/actions/runs/3731725725/jobs/6330275653#step:6:32)4]:
/opt/hostedtoolcache/Ruby/3.1.2/x64/bin/bundle:25:in `<main>'
Use open source without a hyphen.
Tasks: TOP => topics
Expected "Ionic framework is an open-source UI toolkit for building performant, high-quality mobile apps, desktop apps, and progressive web apps using web technologies such as HTML, CSS, and JavaScript based on either Angular, React or Vue." to not include "open-source".
(See full trace by running task with --trace)
```

**Review by Eshmove69 — COMMENTED** [review]
Y

**Review by Eshmove69 — COMMENTED** [review]
Y

**Review by kenyonj — APPROVED** [review]
💯 🍨 Thank you for your contribution! I'll merge this in as soon as CI is 🍏

**Pull request merged**
