### PR TITLE
add github Diff Navigator

### PR DESCRIPTION
**Pull request by daattali**
### Thank you for contributing! Please confirm the following:

- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [ ] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [x] Suggesting edits to an existing topic or collection
  - [ ] Curating a new topic or collection

---------------------------------------------------------------------

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288)
- [x] Content (and my changes are in `index.md`)

The collection is for GitHub browser extensions, I added a Chrome extension

### Curating a new topic or collection

- [ ] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [ ] My folder contains a `*.png` image (if applicable) and `index.md`
- [ ] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

> Please replace this line with an explanation of why you think this topic or collection should be curated.

---------------------------------------------------------------------

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by daattali** [comment]
I did not check the "I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee)" box because the Chrome extension I submitted **was** written by me 4 years ago.

**Comment by iwillcatchu72** [comment]
Thanx

**Comment by MikeMcQuaid** [comment]
@daattali Thanks for the heads up. Passing for now for that reason, sorry!

**Comment by daattali** [comment]
@MikeMcQuaid I don't understand why -- the point of this repo is to help explore, this seem counter productive. If the goal is to only allow high quality useful tools, then perhaps looking at each submission to verify it works and judge whether it seems useful would be beneficial.

**Pull request closed without merging**
