### PR TITLE
Add 'UEFI' topic

### PR DESCRIPTION
**Pull request by Minionguyjpro**
### Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: <https://github.com/github/explore/blob/main/CONTRIBUTING.md>.
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288, size <= 75 kB)
- [ ] Content (and my changes are in `index.md`)

> Please replace this line with an explanation of why you think these changes should be made.

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: <https://github.com/github/explore/tree/main/docs>

It is about firmware, where you see which topics belong to these which are related to UEFI firmware, when it is needed. For example, I search for UEFI-related software. I click on UEFI, and then I know what it is, and I can search further if needed.

### Something that does not neatly fit into the binary options above

- [ ] My suggested edits are not about an existing topic or collection, or at least not a single one
- [ ] My suggested edits are not about curating a new topic or collection, or at least not a single one
- [ ] My suggested edits conform to the Style Guide and API docs: https://github.com/github/explore/tree/main/docs

> Please replace this line with an explanation of your proposed changes.

---

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Review by kenyonj — CHANGES_REQUESTED** [review]
Looks like according to the failing CI that the image is too big.

**Comment by Minionguyjpro** [comment]
> Looks like according to the failing CI that the image is too big.

Will fix in my fork.

**Review by Minionguyjpro — COMMENTED** [review]
- Made description shorter.
- Made image smaller (width of 288px)

**Comment by kenyonj** [comment]
Sorry @Minionguyjpro, the image is still not compliant:

```rb
  1) Failure:
topics::uefi topic#test_0019_has at most one image with the right name, type, and dimensions [/home/runner/work/explore/explore/test/topics_test.rb:230]:
topic images should be 288px tall.
Expected: 288
  Actual: 333
```

**Comment by Minionguyjpro** [comment]
> 

It must be a sqaure image? I will try to change using a photo editor

**Review by Minionguyjpro — COMMENTED** [review]
- Image height is now correct (now 288px)
Image should now work. It is an image with square aspect ratio, 288x288px.

**Comment by Minionguyjpro** [comment]
Wait. see that something is not right

**Review by kenyonj — APPROVED** [review]

**Comment by Minionguyjpro** [comment]
Fix final thing.

**Comment by Minionguyjpro** [comment]
I have fixed the final problem. Now it should really be good.

**Pull request merged**
