### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by asarora72**
Existing content is correct just I wanted to add a line on Ajax which I believe is essential for modern day technologies like React.

### Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: <https://github.com/github/explore/blob/main/CONTRIBUTING.md>.
- [x] I am not the sole author or employee of a company who created the topic or collection I am changing.

### Which change are you proposing?

  - [x] Suggesting edits to an existing topic or collection

---

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [x] Content (and my changes are in `index.md`)

> 

> Please replace this line with an explanation of why you think this topic or collection should be curated.

---

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Review by ahpook — APPROVED** [review]
LGTM, thank you for the improvement.

**Comment by asarora72** [comment]
There seems to be some error while Auto merge. I already checked, "I am not the sole author or employee of a company who created the topic or collection I am changing." I am new to this. Please suggest @ahpook

**Comment by asarora72** [comment]
Thanks I really appreciate.

**Comment by organizacionasociada-beep** [comment]
diff --git a/topics/ajax/index.md b/topics/ajax/index.md
index 67fdfcd7a839..949700756c58 100644
--- a/topics/ajax/index.md
+++ b/topics/ajax/index.md
@@ -6,5 +6,5 @@ related: json, html, xml, javascript
 wikipedia_url: https://en.wikipedia.org/wiki/Ajax_(programming)
 logo: ajax.png
 ---
-Ajax stands for asynchronous JavaScript and XML. It is collection of several web technologies including HTML, CSS, JSON, XML, and JavaScript. It is used for creating dynamic web pages in which small parts of web page change without reloading the page.
+Ajax stands for asynchronous JavaScript and XML. It is collection of several web technologies including HTML, CSS, JSON, XML, and JavaScript. It is used for creating dynamic web pages in which small parts of web page change without reloading the page. Additionally, Ajax is fundamental for front-end developers in creating Single Page Applications (SPAs) where content updates seamlessly.

**Comment by organizacionasociada-beep** [comment]
From 86ec4a9c0453884fa094082567b73d187910fd61 Mon Sep 17 00:00:00 2001
From: Amarjit Singh <asarora72@gmail.com>
Date: Thu, 7 Dec 2023 20:00:01 +0530
Subject: [PATCH] Update index.md

Existing content is correct just I wanted to add a line on Ajax which I believe is essential for modern day technologies like React.
---
 topics/ajax/index.md | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/topics/ajax/index.md b/topics/ajax/index.md
index 67fdfcd7a839..949700756c58 100644
--- a/topics/ajax/index.md
+++ b/topics/ajax/index.md
@@ -6,5 +6,5 @@ related: json, html, xml, javascript
 wikipedia_url: https://en.wikipedia.org/wiki/Ajax_(programming)
 logo: ajax.png
 ---
-Ajax stands for asynchronous JavaScript and XML. It is collection of several web technologies including HTML, CSS, JSON, XML, and JavaScript. It is used for creating dynamic web pages in which small parts of web page change without reloading the page.
+Ajax stands for asynchronous JavaScript and XML. It is collection of several web technologies including HTML, CSS, JSON, XML, and JavaScript. It is used for creating dynamic web pages in which small parts of web page change without reloading the page. Additionally, Ajax is fundamental for front-end developers in creating Single Page Applications (SPAs) where content updates seamlessly.
 diff --git a/topics/ajax/index.md b/topics/ajax/index.md
index 67fdfcd7a839..949700756c58 100644
--- a/topics/ajax/index.md
+++ b/topics/ajax/index.md
@@ -6,5 +6,5 @@ related: json, html, xml, javascript
 wikipedia_url: https://en.wikipedia.org/wiki/Ajax_(programming)
 logo: ajax.png
 ---
-Ajax stands for asynchronous JavaScript and XML. It is collection of several web technologies including HTML, CSS, JSON, XML, and JavaScript. It is used for creating dynamic web pages in which small parts of web page change without reloading the page.
+Ajax stands for asynchronous JavaScript and XML. It is collection of several web technologies including HTML, CSS, JSON, XML, and JavaScript. It is used for creating dynamic web pages in which small parts of web page change without reloading the page. Additionally, Ajax is fundamental for front-end developers in creating Single Page Applications (SPAs) where content updates seamlessly.

**Pull request merged**
