### PR TITLE
Update index.md (made-in-egypt)

### PR DESCRIPTION
**Pull request by 0b01001010**
### Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: <https://github.com/github/explore/blob/main/CONTRIBUTING.md>.
- [x] I am not the sole author or employee of a company who created the topic or collection I am changing.

### Which change are you proposing?

  - [x] Suggesting edits to an existing topic or collection
  - [ ] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288, size <= 75 kB)
- [x] Content (and my changes are in `index.md`)

[Sveltegram](https://sveltegram.a3k.me) is an npm package to facilitate the telegram integration for svelte developers.

---

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by ahpook** [comment]
@0b01001010  The tests failed because new items need to be at the bottom of the list, not the top. Please fix if you want this merged.

**Comment by 0b01001010** [comment]
Hi @ahpook , Sorry for my misunderstanding, I thought newer = top! It's now in the bottom of the list.
Thank you.

**Review by ahpook — APPROVED** [review]

**Comment by Rolenrob** [comment]
Still not allowing me to receive Bitcoin

**Review by Rolenrob — COMMENTED** [review]
It's still wanting me to pay money instead of exchanging out of my Bitcoin allowance

**Pull request merged**
