### PR TITLE
Adding Marko

### PR DESCRIPTION
**Pull request by seangates**
Marko has thousands of stars, and is an extremely strong framework for teams looking for performance, capabilities, and a unique take on building components.

- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md

I am:
  - [x] Suggesting edits to an existing topic or collection
  - [ ] Curating a new topic or collection
  - [x] Unaffiliated with the project (not self-promoting as e.g. a maintainer, creator, contractor or employee)

************EDITING AN EXISTING TOPIC OR COLLECTION************

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288)
- [x] Content (and my changes are in `index.md`)

Please explain why these changes are necessary:

************CURATING A NEW TOPIC************

- [ ] I've formatted my changes as a new folder directory, named for the topic as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]`)
- [ ] My folder contains a `*.png` image (if applicable) and `index.md`
- [ ] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

Please explain why you think this topic should be curated:

************CURATING A NEW COLLECTION************

- [ ] I've formatted my changes as a new folder directory, named for the collection as it appears in the URL on GitHub (e.g. `https://github.com/collections/[NAME]`)
- [ ] My folder contains a `*.png` image (if applicable) and `index.md`
- [ ] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

Please explain why you think this collection should be curated:

Marko has thousands of stars, and is an extremely strong framework for teams looking for performance, capabilities, and a unique take on building components.

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by seangates** [comment]
Edited the description. The first time I mistakenly pasted the wrong thing.

**Comment by seangates** [comment]
Although the build failed, I don't believe it has anything to do with my changes.

**Comment by damaneice** [comment]
@seangates You are correct it has nothing to do with your changes. I will take a look at it.

**Comment by seangates** [comment]
Thanks, @damaneice!

**Comment by damaneice** [comment]
I fixed the broken tests. But now it looks like there are some merge conflicts that need to be fixed.  @seangates Can you take a look?

**Comment by seangates** [comment]
Sure. I’ll check it out tomorrow.

**Comment by seangates** [comment]
@talsafran Glad to contribute!

**Comment by seangates** [comment]
@talsafran How long does it usually take to show up?

**Comment by talsafran** [comment]
@seangates should be up now! https://github.com/collections/front-end-javascript-frameworks

**Pull request merged**
