### PR TITLE
Collections Riscv Made Brazil 

### PR DESCRIPTION
**Pull request by carlosdelfino**
### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---------------------------------------------------------------------

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288)
- [ ] Content (and my changes are in `index.md`)

> Please replace this line with an explanation of why you think these changes should be made.

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

The Risc-V Core projects have matured and new ones have emerged, and in Brazil it has been no different. Creating a Brazilian collection values local projects by encouraging local teams and individuals to publicize their projects.

### Something that does not neatly fit into the binary options above

- [ ] My suggested edits are not about an existing topic or collection, or at least not a single one
- [ ] My suggested edits are not about curating a new topic or collection, or at least not a single one
- [ ] My suggested edits conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

> Please replace this line with an explanation of your proposed changes.

---------------------------------------------------------------------

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by Oneill38** [comment]
@carlosdelfino please fill out the PR template fully, particularly where you see:
> Please replace this line with an explanation of why you think this topic or collection should be curated.

**Comment by kenyonj** [comment]
Hi @carlosdelfino . Looks like this PR changes two collections (one added and one modified). Please open a new PR with scoped changes for each one of these collections and we can review them individually.
Thanks!

**Comment by carlosdelfino** [comment]
This pull request deals only with the "riscv-brazil' collection, any other collection or topic that will be present are merges that were completed at the request of github or obtained from the master.

**Comment by kenyonj** [comment]
Sounds good. I reopened the PR. Just need to resolve the conflicts made in the existing collection or remove any changes from that file.

**Comment by carlosdelfino** [comment]
These conflicts came from the merge relative to the other branch that was not approved, I added new repositories and reordered the repositories, so I removed those changes.

**Comment by kenyonj** [comment]
> These conflicts came from the merge relative to the other branch that was not approved, I added other generic collection and reordered the repositories, so I removed those changes.

We don't currently support reordering in collections. If there are conflicts with the current base branch it's due to this PR getting out of date and needs to be cleaned up here. My suggestion is to remove the existing collection changes and just deal with the new collection you are proposing.

**Comment by carlosdelfino** [comment]
I will do a "pull", check locally and send the "PR" again soon, updated.

Thanks.

**Pull request closed without merging**
