### PR TITLE
Update whatsapp topic

### PR DESCRIPTION
**Pull request by AyushShahh**
### Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: <https://github.com/github/explore/blob/main/CONTRIBUTING.md>.
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [x] Suggesting edits to an existing topic or collection
  - [ ] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288, size <= 75 kB)
- [x] Content (and my changes are in `index.md`)

> Facebook Inc. is now called Meta Platforms Inc.

### Curating a new topic or collection

- [ ] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [ ] My folder contains a `*.png` image (if applicable) and `index.md`
- [ ] All required fields in my `index.md` conform to the Style Guide and API docs: <https://github.com/github/explore/tree/main/docs>

> Please replace this line with an explanation of why you think this topic or collection should be curated.

### Something that does not neatly fit into the binary options above

- [ ] My suggested edits are not about an existing topic or collection, or at least not a single one
- [ ] My suggested edits are not about curating a new topic or collection, or at least not a single one
- [ ] My suggested edits conform to the Style Guide and API docs: https://github.com/github/explore/tree/main/docs

> Please replace this line with an explanation of your proposed changes.

---

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Review by smashwilson — APPROVED** [review]
:+1: Thanks for adding the alias there, too. 🙇🏻

**Comment by Betterdayahead** [comment]
I wish I knew what this all meant. I feel like someone is acting as me.

**Comment by Globalove4all** [comment]
Show us how to use GitHub to overpower money by application data with
online real time API to manipulate rich greed money accounts using two
books Tsing style or double entries accounting.

**Comment by Betterdayahead** [comment]
> 👍 Thanks for adding the alias there, too. 🙇🏻



> 👍 Thanks for adding the alias there, too. 🙇🏻

What alias

**Comment by Globalove4all** [comment]
Rich greed political and bank rulers thought they can get away with money
worth monopoly to their own selfish-piggy benefits to the expense of
wonderful creations of humankind and mother natures.
Anyone wants to play?

**Pull request merged**
