### PR TITLE
New Topic | Added NASA Topic

### PR DESCRIPTION
**Pull request by kaiodcosta**
### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [X] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [X] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [X] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---------------------------------------------------------------------

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [X] Image (and my file is `*.png`, square, dimensions 288x288)
- [X] Content (and my changes are in `index.md`)

> Please replace this line with an explanation of why you think these changes should be made.

### Curating a new topic or collection

- [X] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [X] My folder contains a `*.png` image (if applicable) and `index.md`
- [X] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

> Please replace this line with an explanation of why you think this topic or collection should be curated.

### Something that does not neatly fit into the binary options above

- [X] My suggested edits are not about an existing topic or collection, or at least not a single one
- [X] My suggested edits are not about curating a new topic or collection, or at least not a single one
- [X] My suggested edits conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

> I put the information on the topic NASA.

---------------------------------------------------------------------

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Review by gallexi — APPROVED** [review]
Thanks for your contribution!

**Comment by gallexi** [comment]
Op, looks like there are CI failures around how large the logo and description are: 

```
1) Failure:
topics::nasa topic#test_0019_has at most one image with the right name, type, and dimensions [/home/runner/work/explore/explore/test/topics_test.rb:229]:
topic images should be 288px wide.
Expected: 288
  Actual: 1920

  2) Failure:
topics::nasa topic#test_0024_has a valid short_description [/home/runner/work/explore/explore/test/topics_test.rb:297]:
must have a short_description no more than 130 characters (currently 199)
```

Once those are fixed, happy to merge this!

**Comment by kaiodcosta** [comment]
Hello @gallexi , the problems have already been solved! now you are free to merge this!

**Comment by smashwilson** [comment]
Awesome. Thanks for contributing! 🙌🏻

**Pull request merged**
