### PR TITLE
Added Pi Hole topic

### PR DESCRIPTION
**Pull request by thomasbnt**
- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection

---------------------------------------------------------------------

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

> Please replace this line with an explanation of why you think this topic or collection should be curated.

---------------------------------------------------------------------

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by thomasbnt** [comment]
Ohh sorry, I missed that :no_mouth:

**Comment by kenyonj** [comment]
CI is going to fail again since the image needs to be `pihole.png`

**Comment by thomasbnt** [comment]
But you say

> This is great. I  Pi-hole! Just have to rename your image to match the topic directory name and we can get this merged in. Thanks for your contribution!

And the topic name is `topic: pi-hole`.

But okay, I pushed that here :)

**Comment by thomasbnt** [comment]
Good?

**Comment by kenyonj** [comment]
🎉  github.com/topics/pihole 🎉

**Pull request merged**
