### PR TITLE
Removed Pyxel game engine

### PR DESCRIPTION
**Pull request by AdamHarte**
### Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: <https://github.com/github/explore/blob/main/CONTRIBUTING.md>.
- [x] I am not the sole author or employee of a company who created either the topic I am modifying/adding or the collection entry I am modifying/adding.

### Which change are you proposing?

  - [x] Suggesting edits to an existing topic or collection
  - [ ] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288, size <= 75 kB)
- [x] Content (and my changes are in `index.md`)

Looks like the Pyxel game engine was mistaken for the PyxelEdit pixel art software, which is not opensource. So I removed it, as the game engine is not a "Pixel Art Tool".

---

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by AdamHarte** [comment]
Failing tests because:
> Error: expected collection changes to have been appended to the existing item list
Seems like a bad test, because not all changes are additions. Does this mean that nobody can ever remove items?

**Comment by jmeridth** [comment]
> Failing tests because:
> 
> > Error: expected collection changes to have been appended to the existing item list
> 
> Seems like a bad test, because not all changes are additions. Does this mean that nobody can ever remove items?

@AdamHarte That's a fair statement.  I'm good to merge this and then let the collection action generate the PR that will make this happy.  Chicken/egg.  I will take a look at it soon to hopefully allow just deletions with no issues.

**Review by jmeridth — APPROVED** [review]

**Comment by jmeridth** [comment]
@AdamHarte thank you for helping us keep these collections clean. 🙇

**Comment by AdamHarte** [comment]
@jmeridth No worries at all. Thank you for sorting this out. I was starting to get worried I was not going to be able to get this change through. :)

**Pull request merged**
