### PR TITLE
Fake pull request but please read it :)

### PR DESCRIPTION
**Pull request by lgmorand**
Hi @gallexi (or anybody else but you seem pretty active on this repo :))

It's a fake pull request but the issues have been disabled on this repo (?!!!) and that's the only way to contact the owners of the repo

It seems that someone just renamed the branch **master** to **main**. Doing that, he broke all systems relying on the content (images). For examples, the majority of github profiles are using direct link to your images (we followed a github blog explaining how to do that so for sure it's not just one or two people ;)) and all those links are now broken. I also found actions which have also direct links to the images of this repo for their description.

like this (https://github.com/github/explore/blob/**master**/topics/aspnet/aspnet.png?raw=true)

instead of  (https://github.com/github/explore/blob/**main**/topics/aspnet/aspnet.png?raw=true)

**Could please at least clone the branch "main" to a "master" branch** and put this one as read-only. thanks :)
even is master will remain out of date, at least it won't break anything. people will have to switch to main whenever they want/need to

ps: here is a page to test that readding the master branch would fix it: https://github.com/lgmorand/
ps: of course, you can delete this PR :D

### CODE REVIEW

**Comment by gallexi** [comment]
Hello!

Thanks for the heads up! For context, part of why we have issues turned off is that this is not a place where we're set up to take support requests; ideally, those would go through https://support.github.com/contact/feedback or https://github.community/. I'll make a note in the ReadMe about that, for future reference!

Ah, I'm sorry to hear the change broke some things, though to be honest, I don't particularly want to set a precedent that the filesystem here can be relied upon not to change, as it's really not meant to be an API 😬  Can you point me to the blog post you mentioned? Perhaps we can suggest they update the post, as well.

Thanks!

**Comment by salgo60** [comment]
@lgmorand cant you use [Wikidata](https://www.youtube.com/watch?v=m_9_23jXPoE) we also have a new property for GITHUB topics see [github.community](https://github.community/t/wikidata-property-p9100-created-for-github-topics/158508)

**Comment by lgmorand** [comment]
@salgo60 I'm sorry but I don't see how wikidata would solve the issue with a branch naming nor to contact a contributor. did I miss something ?

@gallexi oh yeah I know I can use community but...nobody from the staff answers there, only community people. There are issues open like vulnerabilities with secrets open for month and not a single answer from GH for months (but I do understand because monitoring the whole forum would be impossible). Because I believe the issue is from this repo, only a contrib from this repo can fix it, it was easier to do it here :) (I could on your github email Lexi but wasn't sure you were owner of the subject and didn't want to disturb too much :))
If I find the blog post, I'll definitly ping you directly

So, there is no way to put a master branch ?

**Comment by salgo60** [comment]
@lgmorand my understanding was that you tried to get some metadata/pictures of the objects..... I thought that was easier to get from WIkidata

**Comment by lgmorand** [comment]
No metadata, just a hard link to images, like a CDN. instead of duplicating images.

Using google, that's easy to find how many people are doing that for their github profile, it's not my personal weird delirium :-P

https://github.com/erdinccurebal
https://github.com/baptisteohanes
https://github.com/polatengin/polatengin

all broken

**Comment by gallexi** [comment]
Thanks for those examples, @lgmorand. They helped us understand the scope of this issue a bit better. For the time being, we've decided not to recreate the `master` branch despite the unfortunate effect this has had on some use cases. In general, we encourage folks to link to more stable identifiers like SHAs, although those too aren't necessarily permanent. We have raised an issue internally to determine the appropriateness of redirecting links with the `raw=true` parameter as we do with those without that parameter, but we can offer no promises there.

In the meantime, if you could point us to the blog post you mentioned earlier where GitHub suggested this type of link, we'll see to it that it is updated!

Thanks!

**Comment by MikeMcQuaid** [comment]
Thanks for your helpful comments @gallexi @salgo60!

> It's a fake pull request but the issues have been disabled on this repo (?!!!) and that's the only way to contact the owners of the repo

@lgmorand This is because we do not wish to be contacted with issues here. As mentioned: the GitHub community forum and GitHub support are the right approach instead.

> For examples, the majority of github profiles are using direct link to your images (we followed a github blog explaining how to do that so for sure it's not just one or two people ;)) and all those links are now broken. I also found actions which have also direct links to the images of this repo for their description.

This is an exaggeration: the majority of GitHub profiles are not doing this. The workaround/fix is also trivial.

> like this (https://github.com/github/explore/blob/**master**/topics/aspnet/aspnet.png?raw=true)

As mentioned by @gallexi: this is not a public or supported API. You should expect that using links in this way in future will break and not rely on this (or any) URL format remaining the same that is not officially documented (particularly relying on the layout of a particular repository).

If you wish to take the risk anyway, I recommend using `blob/HEAD` instead of `blob/master` or `blob/main`.

**Pull request closed without merging**
