### PR TITLE
Add topic biological-expression-language

### PR DESCRIPTION
**Pull request by cthoyt**
### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection

---------------------------------------------------------------------

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288)
- [ ] Content (and my changes are in `index.md`)

> Please replace this line with an explanation of why you think these changes should be made.

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

> Biological Expression Language (BEL) is gaining popularity as a DSL for biological knowledge graphs and is supporting lots of new machine learning / artificial intelligence approaches in drug discovery and medicine. Therefore, I think it's worth indexing on GitHub

---------------------------------------------------------------------

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by kenyonj** [comment]
Looks like there is a CI error around the size of the image. https://github.com/github/explore/pull/1320/checks?check_run_id=387886560#step:4:76

**Comment by cthoyt** [comment]
Do you have any advice on changing the size of this PNG? I don't know much about images. Unfortunately I don't know where the BEL logo came from and the only place it's available on the web is http://openbel.org/media/bel300x.png

**Comment by kenyonj** [comment]
I found this one online, can you update the PR with this file:
bel300x

**Comment by kenyonj** [comment]
looks like the dimensions were a bit off, I think this is correct:
bel300x

**Comment by kenyonj** [comment]
Try this one instead, the dimensions were off on the last one
bel300x-min

**Comment by cthoyt** [comment]
It's upset at the height of the image... unfortunately it's 288 x 286... I don't know how to add 2px to the height without making the file size go way up

**Comment by kenyonj** [comment]
let's try this one
bel300x-min-min

**Pull request merged**
