### PR TITLE
Add nhost

### PR DESCRIPTION
**Pull request by sangdth**
### Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: <https://github.com/github/explore/blob/master/CONTRIBUTING.md>.
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: <https://github.com/github/explore/tree/master/docs>

I'm a big fan of nhost, it saves lot of time for me. So I believe it helps other devs too.

---

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Review by MikeMcQuaid — CHANGES_REQUESTED** [review]
@sangdth One wee test failure that needs addressed: https://github.com/github/explore/runs/5395119449?check_suite_focus=true#step:4:17

**Comment by sangdth** [comment]
> @sangdth One wee test failure that needs addressed: https://github.com/github/explore/runs/5395119449?check_suite_focus=true#step:4:17

Thanks @MikeMcQuaid , I will fix it asap

**Comment by MikeMcQuaid** [comment]
@sangdth Most test failures I'm afraid: https://github.com/github/explore/runs/5404495414?check_suite_focus=true#step:4:18

**Comment by sangdth** [comment]
> Most test failures I'm afraid: https://github.com/github/explore/runs/5404495414?check_suite_focus=true#step:4:18

Oh I thought it check only the width of the image. I will update the logo asap.

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
Thanks so much for your first contribution! Without people like you submitting PRs we couldn't run this project. You rock, @sangdth!

**Comment by sangdth** [comment]
@MikeMcQuaid Thank you for your patience.

**Pull request merged**
