### PR TITLE
Update repository target for finom/seemple

### PR DESCRIPTION
**Pull request by PlayTheFallen**
### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [x] Suggesting edits to an existing topic or collection
  - [ ] Curating a new topic or collection

---------------------------------------------------------------------

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288)
- [x] Content (and my changes are in `index.md`)

> Please replace this line with an explanation of why you think these changes should be made.

### Curating a new topic or collection

- [ ] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [ ] My folder contains a `*.png` image (if applicable) and `index.md`
- [ ] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

> Please replace this line with an explanation of why you think this topic or collection should be curated.

See finom/seemple#52, rename was done on 20th Jan 2020 according to the issue.

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by PlayTheFallen** [comment]
This issue was patched in commit eb2f12b2488a083bfd9d2f10f4c4f16638ea1b26 at master.
PR made redundent, no files to change.

**Comment by PlayTheFallen** [comment]
@kenyonj can you shed some light on the direct commit over this? If it's just that the ci failed, I have another change that I wish to propose on or templating that I'll submit later.

**Comment by kenyonj** [comment]
I fixed the conflict on master. Was that your question?

**Comment by PlayTheFallen** [comment]
Yea, that's all. Good to see its fixed.

**Pull request closed without merging**
