### PR TITLE
Add ASGI topic

### PR DESCRIPTION
**Pull request by Ksengine**
- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

---

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---------------------------------------------------------------------

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

ASGI (Asynchronous Server Gateway Interface) is a spiritual successor to WSGI, intended to provide a standard interface between async-capable Python web servers, frameworks, and applications.

Where WSGI provided a standard for synchronous Python apps, ASGI provides one for both asynchronous and synchronous apps, with a WSGI backwards-compatibility implementation and multiple servers and application frameworks.

And there is a number of repos on asgi in github.

### CODE REVIEW

**Review by Juanepaktho — APPROVED** [review]

**Comment by Ksengine** [comment]
Thank You @Juanepaktho

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
Thanks so much for your first contribution! Without people like you submitting PRs we couldn't run this project. You rock, @Ksengine!

**Comment by Ksengine** [comment]
> Thanks so much for your first contribution! Without people like you submitting PRs we couldn't run this project. You rock, @Ksengine!

This project is cool!!!:cool:

**Comment by Ksengine** [comment]
I can't see the description of this topic on https://github.com/topics/asgi

**Pull request merged**
