### PR TITLE
:memo: CSS Reset Topic

### PR DESCRIPTION
**Pull request by krishdevdb**
### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---------------------------------------------------------------------

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

>  A CSS reset is a style sheet that sets all CSS properties to their default values.

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by krishdevdb** [comment]
@gallexi I worked on your suggestion is #2156 Here's The Result

**Review by gallexi — APPROVED** [review]
Excellent!! This looks great, thanks for your persistence in getting this across the finish line!

**Comment by krishdevdb** [comment]
Thanks However I have made my own repositories it was my first contribution to a GitHub Repository. And I am Really Happy It Was Accepted.

**Comment by lynnetteboling1** [comment]
Thanks

**Pull request merged**
