### PR TITLE
Added topics/ditsmod

### PR DESCRIPTION
**Pull request by KostyaTretyak**
### Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: <https://github.com/github/explore/blob/main/CONTRIBUTING.md>.
- [x] I am creator and maintainer of Ditsmod.

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: <https://github.com/github/explore/tree/main/docs>

> Ditsmod is new server side NodeJS framework, writen in TypeScript. So, thanks to the topic on github, users will learn more about it.

### CODE REVIEW

**Comment by kenyonj** [comment]
Hi,
Thanks for starting this pull request. In order to review it for acceptance, we need to make sure that all of the prerequisites are satisfied. I see that you removed this check:

> I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee)

However, you are a main contributor/owner to this project. This is a requirement so that we can maintain a high level of independence in this project. Please update if you are able to verify that you meet that requirement.

Thanks!

**Comment by KostyaTretyak** [comment]
Where can I read the documentation about the following requirement:

> I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee)

I think that this requirement was designed so that there would be no commercial advertising. Otherwise, this requirement makes no sense at all, and it can be easily bypassed...

**Comment by kenyonj** [comment]
> Where can I read the documentation about the following requirement:
> 
> > I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee)
> 
> I think that this requirement was designed so that there would be no commercial advertising. Otherwise, this requirement makes no sense at all, and it can be easily bypassed...

Here you go: https://github.com/github/explore/blob/main/CONTRIBUTING.md#guidelines

**Comment by KostyaTretyak** [comment]
> Avoid conflicts of interest. Maintainers of a project cannot add a topic or collection for their own project. If a topic is popular enough to warrant inclusion, someone else will add or improve it.

But where is the "conflict of interest"? What does it manifest itself in? My project is not commercial, github topics could help popularize this framework. What is wrong here?

**Comment by kenyonj** [comment]
> > Avoid conflicts of interest. Maintainers of a project cannot add a topic or collection for their own project. If a topic is popular enough to warrant inclusion, someone else will add or improve it.
> 
> But where is the "conflict of interest"? What does it manifest itself in? My project is not commercial, github topics could help popularize this framework. What is wrong here?

I appreciate the question, but we aren't currently modifying our policy on this issue. We have this stated policy as well as a "widely used" requirement in our docs that would unfortunately also preclude this topic.

**Pull request closed without merging**
