### PR TITLE
Add Supabase Topic

### PR DESCRIPTION
**Pull request by hokkqi**
### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---------------------------------------------------------------------

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

> Supabase is a fairly new, but quickly growing, Open Source alternative to Firebase.  They provide a hosted, as well as a self-hosted, PostgreSQL Database with various Features, such as Authentication, S3-Compatible Storage, as well as Functions.
---------------------------------------------------------------------

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by nholden** [comment]
Thanks for this contribution! ❤️ 

I just ran CI, and it looks like there's a failure. Mind taking a look and addressing it?

**Comment by hokkqi** [comment]
@nholden 
I can fix the alias error, and already have done so locally, but I can't seem to find their Logo in 288x288.
I could only find a 200 × 200, which is their Github Avatar and their Dev.to Avatar which is 320 × 320.
Is it alright if the Logo is 200x200?

**Comment by hokkqi** [comment]
@nholden?

**Comment by nholden** [comment]
> Is it alright if the Logo is 200x200?

Topic images should be 288x288 to be sure that they render properly on the page. If you can't find a logo that's 288x288, I recommend finding one that's larger and scaling/cropping it to 288x288.

**Comment by hokkqi** [comment]
Hopefully this works!

**Review by nholden — APPROVED** [review]

**Pull request merged**
