### PR TITLE
Topics and updates

### PR DESCRIPTION
**Pull request by AyushShahh**
### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [x] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---------------------------------------------------------------------

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [x] Image (and my file is `*.png`, square, dimensions 288x288, size <= 75 kB)
- [x] Content (and my changes are in `index.md`)

> I have changed google cloud platform icon as it is on the official website. I also have updated some information.

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

> The topics I have added include well known tech companies, platforms and tools that a lot of people use. So they should be curated on github.

### Something that does not neatly fit into the binary options above

- [ ] My suggested edits are not about an existing topic or collection, or at least not a single one
- [ ] My suggested edits are not about curating a new topic or collection, or at least not a single one
- [ ] My suggested edits conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

> Please replace this line with an explanation of your proposed changes.

---------------------------------------------------------------------

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Review by MikeMcQuaid — COMMENTED** [review]
Could you split this into separate PRs e.g. one per topic? It's a bit hard to review/merge them all together. Thanks!

**Comment by AyushShahh** [comment]
@MikeMcQuaid Sure, I will do that

**Comment by AyushShahh** [comment]
@MikeMcQuaid Can I add two topics per P.R as there are a lot of them? I will be sending PRs as I split topics one by one

**Comment by MikeMcQuaid** [comment]
@AyushShahh yup, two is fine! One would be ideal.

**Pull request closed without merging**
