### PR TITLE
Dependabot bundler rubocop 1.15.0

### PR DESCRIPTION
**Pull request by hello-smile6**
### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [X] I followed the contributing guidelines: https://github.com/github/explore/blob/master/
- [X] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [x] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [x] Something that does not neatly fit into the binary options above

---------------------------------------------------------------------

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [x] Image (and my file is `*.png`, square, dimensions 288x288)
- [x] Content (and my changes are in `index.md`)

> Please replace this line with an explanation of why you think these changes should be made.

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

> Please replace this line with an explanation of why you think this topic or collection should be curated.

### Something that does not neatly fit into the binary options above

- [x] My suggested edits are not about an existing topic or collection, or at least not a single one
- [x] My suggested edits are not about curating a new topic or collection, or at least not a single one
- [x] My suggested edits conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

> Please replace this line with an explanation of your proposed changes.

---------------------------------------------------------------------

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by Mymentorkay** [comment]
This is a very good project.

**Comment by shalomcem** [comment]
ok I need some one can help me  how to "designee  and build  a web app", I am work on it now but need your help  .

**Comment by shalomcem** [comment]
[https://trueloveclub.net.github.io](url)

**Review by Razaulgazi — COMMENTED** [review]
@ForIntent("Basic Card")
public ActionResponse basicCard(ActionRequest request) {
  ResponseBuilder responseBuilder = getResponseBuilder(request);
  if (!request.hasCapability(Capability.SCREEN_OUTPUT.getValue())) {
    return responseBuilder
        .add("Sorry, try ths on a screen device or select the phone surface in the simulator.")
        .add("Which response would you like to see next?")
        .build();
  }

  // Prepare formatted text for card
  String text =
      "This is a basic card.  Text in a basic card can include \"quotes\" and\n"
          + "  most other unicode characters including emoji \uD83D\uDCF1. Basic cards also support\n"
          + "  some markdown formatting like *emphasis* or _italics_, **strong** or\n"
          + "  __bold__, and ***bold itallic*** or ___strong emphasis___ as well as other\n"
          + "  things like line  \\nbreaks"; // Note the two spaces before '\n' required for
  // a line break to be rendered in the card.
  responseBuilder
      .add("Here's an example of a basic card.")
      .add(
          new BasicCard()
              .setTitle("Title: this is a title")
              .setSubtitle("This is a subtitle")
              .setFormattedText(text)
              .setImage(
                  new Image()
                      .setUrl(
                          "https://storage.googleapis.com/actionsresources/logo_assistant_2x_64dp.png")
                      .setAccessibilityText("Image alternate text"))
              .setImageDisplayOptions("CROPPED")
              .setButtons(
                  new ArrayList<Button>(
                      Arrays.asList(
                          new Button()
                              .setTitle("This is a Button")
                              .setOpenUrlAction(
                                  new OpenUrlAction().setUrl("https://assistant.google.com"))))))
      .add("Which response would you like to see next?");

  return responseBuilder.build();
}

**Comment by KOKOC1987** [comment]
> ### Thank you for contributing! Please confirm this pull request meets the following requirements:
> * [x]  I followed the contributing guidelines: https://github.com/github/explore/blob/master/
> * [x]  I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).
> 
> ### Which change are you proposing?
> * [x]  Suggesting edits to an existing topic or collection
> * [x]  Curating a new topic or collection
> * [x]  Something that does not neatly fit into the binary options above
> 
> ### Editing an existing topic or collection
> I'm suggesting these edits to an existing topic or collection:
> 
> * [x]  Image (and my file is `*.png`, square, dimensions 288x288)
> * [x]  Content (and my changes are in `index.md`)
> 
> > Please replace this line with an explanation of why you think these changes should be made.
> 
> ### Curating a new topic or collection
> * [x]  I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
> * [x]  My folder contains a `*.png` image (if applicable) and `index.md`
> * [x]  All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs
> 
> > Please replace this line with an explanation of why you think this topic or collection should be curated.
> 
> ### Something that does not neatly fit into the binary options above
> * [x]  My suggested edits are not about an existing topic or collection, or at least not a single one
> * [x]  My suggested edits are not about curating a new topic or collection, or at least not a single one
> * [x]  My suggested edits conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs
> 
> > Please replace this line with an explanation of your proposed changes.
> 
> **Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

**Pull request closed without merging**
