### PR TITLE
Added Govt of India's COVID management app

### PR DESCRIPTION
**Pull request by mvkaran**
### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [X] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [X] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [X] Suggesting edits to an existing topic or collection
  - [ ] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---------------------------------------------------------------------

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288)
- [X] Content (and my changes are in `index.md`)

Government of India open-sourced the main Android application that is used by millions of citizens in India and the government to manage COVID. This is being added to the Government collection.

---------------------------------------------------------------------

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by mvkaran** [comment]
Seems like some errors related to the pixel-art-tools collection

**Review by gallexi — APPROVED** [review]
Hello, thank you for your contribution!

At first I was confused by the fact that the owner of this repo doesn't seem to be verified as the Indian Government itself, but I did a bunch of digging and based on messaging from official-looking channels, it does seem to be legit! The more you know, I suppose 😅 

https://techcrunch.com/2020/05/26/aarogya-setu-india-source-code-release/

https://twitter.com/PIBMumbai/status/1265311416069656577/

**Comment by mvkaran** [comment]
Thanks, @gallexi! Where and when does this merge usually land, for it to reflect publicly?

Also, thanks for mentioning about sources. I'll keep that in mind for further contributions :)

**Comment by gallexi** [comment]
Ah whoops, I have to press a button on our side for it to appear publicly, I forgot about that part 😅 

The change is now public! https://github.com/collections/government

**Pull request merged**
