### PR TITLE
Add Solium to Clean Code Linters collection

### PR DESCRIPTION
**Pull request by duaraghav8**
Add Solium, a style and security linter for the [Solidity Programming Language](https://solidity.readthedocs.io/en/develop/index.html)

- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md

I am:
  - [x] Suggesting edits to an existing topic or collection
  - [ ] Curating a new topic or collection

***********EDITING AN EXISTING TOPIC OR COLLECTION************

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288)
- [x] Content (and my changes are in `index.md`)

Please explain why these changes are necessary:
The collection currently doesn't contain linters for blockchain-based programming languages. Solidity is Ethereum's flagship language and Solium is the leading linter for it, being used by many solidity projects trending on github.

************CURATING A NEW TOPIC************

- [ ] I've formatted my changes as a new folder directory, named for the topic as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]`)
- [ ] My folder contains a `*.png` image (if applicable) and `index.md`
- [ ] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

Please explain why you think this topic should be curated:

************CURATING A NEW COLLECTION************

- [ ] I've formatted my changes as a new folder directory, named for the collection as it appears in the URL on GitHub (e.g. `https://github.com/collections/[NAME]`)
- [ ] My folder contains a `*.png` image (if applicable) and `index.md`
- [ ] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

Please explain why you think this collection should be curated:

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by styline** [comment]
hi..is it a software Solium or a sort of SGBD need an data extractor or I made a mistake?

**Comment by duaraghav8** [comment]
@styline I'm not sure I understood your question (by SGBD, do you mean Database system?)
Solium is a software, primarily intended to be used as a CLI tool or Node.js Library. Like eslint

**Comment by MikeMcQuaid** [comment]
@duaraghav8 My apologies that https://github.com/github/explore/pull/235 isn't merged yet but: we frown on self-submissions of projects. Thanks for the PR anyway!

**Comment by duaraghav8** [comment]
@MikeMcQuaid apologies, I wasn't aware of the no self-submission practice and must've not read contribution guidelines carefully. Thanks for your time

**Comment by MikeMcQuaid** [comment]
@duaraghav8 Not your fault, they weren't well documented on our end. Have a great day!

**Pull request closed without merging**
