### PR TITLE
add github-vscode-icons

### PR DESCRIPTION
**Pull request by Kajbo**
add github-vscode-icons to github browser extensions

### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [x] Suggesting edits to an existing topic or collection
  - [ ] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---------------------------------------------------------------------

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288)
- [x] Content (and my changes are in `index.md`)

add github-vscode-icons to github-browser-extensions

### CODE REVIEW

**Review by damaneice — APPROVED** [review]

**Review by damaneice — COMMENTED** [review]
Thanks for your contribution

**Comment by maisoenaingtun** [comment]
add

**Comment by maisoenaingtun** [comment]
add

**Comment by krishdevdb** [comment]
> Please Note
>
> I have included some popular and known css-reset repositories
>Also, I have included these repositories from the topic css-reset as well

**Comment by Kajbo** [comment]
Thanks for considering this merge request - is "Closed" state correct? Comments do not suggest that there is anything wrong with this request.

Thanks

**Comment by gallexi** [comment]
Oh, whoops, it looks like that happened accidentally, my apologies!

I'd love to re-open this, but it says "The repository that submitted this pull request has been deleted" 🤔 

Would you mind opening a new PR with this change, and I'll approve and merge? Apologies for the inconvenience!

**Pull request closed without merging**
