### PR TITLE
Add Hacktoberfest

### PR DESCRIPTION
**Pull request by johndbritton**
- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md

I am:
  - [ ] Suggesting edits to an existing Topic page
  - [x] Curating a new Topic page

************CURATING A NEW TOPIC PAGE************

- [x] I've formatted my changes as a new folder directory, named for the topic as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

Please explain why you think this Topic page should be curated:

Hacktoberfest is an annual event that takes place on GitHub and there is wide usage of the [Hacktoberfest topic](https://github.com/topics/hacktoberfest).

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
`topics/.DS_Store` needs 💀ed otherwise 👍

**Comment by johndbritton** [comment]
> topics/.DS_Store needs 💀ed otherwise 👍

Fixed.

I could have sworn I removed that already. I even sent a pull request to [ignore .DS_Store](https://github.com/github/explore/pull/60) 😆.

**Comment by MikeMcQuaid** [comment]
> I even sent a pull request to ignore .DS_Store 😆.

Yes, I didn't want to say 😉

**Comment by MikeMcQuaid** [comment]
Thanks @johndbritton!

**Pull request merged**
