### PR TITLE
Add Notepads to "Text Editors"

### PR DESCRIPTION
**Pull request by SuperHeroX**
### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [x] Suggesting edits to an existing topic or collection
  - [ ] Curating a new topic or collection

---------------------------------------------------------------------

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288)
- [x] Content (and my changes are in `index.md`)

notepads is a new raising lightweight text editor written in UWP and it has gained tremendous attention and received tons of positive reviews already.

---------------------------------------------------------------------

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by kanwil** [comment]
Pull request

**Comment by kanwil** [comment]
Pull

**Comment by 0937923151** [comment]
Vào 04-08-2019 21:05, "kanwil" <notifications@github.com> đã viết:

**Comment by 0937923151** [comment]
Vào 21:02 T.2, 12 Th8 2019 Varun Sridharan <notifications@github.com> đã
viết:

**Pull request merged**
