### PR TITLE
Add hub to the collections

### PR DESCRIPTION
**Pull request by madhucharan**
### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [x] Suggesting edits to an existing topic or collection
  - [ ] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---------------------------------------------------------------------

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288)
- [x] Content (and my changes are in `index.md`)

### Curating a new topic or collection

- [ ] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [ ] My folder contains a `*.png` image (if applicable) and `index.md`
- [ ] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

> I came across the hub opensource package and it is one of the best packages for the fastest unstructured dataset management for TensorFlow/PyTorch. Stream data real-time & version-control it, maintained by http://activeloop.ai. I felt adding a hub to the collection section will help users who work with large datasets (GB's) will have a way to load and process the data much faster. It was recently in #1trending as well. 

### Something that does not neatly fit into the binary options above

- [ ] My suggested edits are not about an existing topic or collection, or at least not a single one
- [ ] My suggested edits are not about curating a new topic or collection, or at least not a single one
- [ ] My suggested edits conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

---------------------------------------------------------------------

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Review by gallexi — CHANGES_REQUESTED** [review]
Hello! Hub looks like a really cool project, thanks for suggesting it!

I want to make sure it gets into the right collection based on what it does. Rather than the categories `open source organizations`, `productivity tools`, or `tools for open source`, what do you think about adding it to the `machine learning` collection, here? https://github.com/github/explore/blob/master/collections/machine-learning/index.md

Thanks!

**Comment by madhucharan** [comment]
Hi @gallexi , Thank you so much for the feed back. I understood about it. Is it fine to list Hub in opensource and ml instead of the three mentioned? since as it is an opensource project, I thought it is fine to list it in opensource as well. Please let me know your views and I will update it as per your advice.

**Comment by gallexi** [comment]
Ah, good question! I think of the "open source"-related collections we have now, `open-source-organizations` is for open source orgs within companies, and `open-source-tools` is for tools that help to organize and run an open source project, so kind of meta =]

I don't think we currently have a collection just called `open-source`, as I think most of the projects featured by GitHub in this repo are open source by default! 😄 

So, I think putting it in `ml` is best, if you agree!

**Comment by madhucharan** [comment]
Hi @gallexi , I have updated the hub position as per the discussion, kindly let me know if there is anything I need to do.Thanks a lot for adding hub.

**Comment by gallexi** [comment]
The file `collections/machine-learning/index.md` looks good! Would you mind reverting your changes on the other three files (I think now the changes are just whitespace and indentation), so that this PR's diff is just your addition of `hub` to collections/machine-learning/index.md? Thanks!

**Comment by maisoenaingtun** [comment]
{{Add hub to the collections #2155}}

**Pull request closed without merging**
