### PR TITLE
added ai-model-zoos to collections

### PR DESCRIPTION
**Pull request by alanbraz**
- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md

I am:
  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [ ] Unaffiliated with the project (not self-promoting as e.g. a maintainer, creator, contractor or employee)

************CURATING A NEW COLLECTION************

- [x] I've formatted my changes as a new folder directory, named for the collection as it appears in the URL on GitHub (e.g. `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

Please explain why you think this collection should be curated: There are at least a dozen of different AI (Machine Learning and Deep Learning) frameworks and any of them try to catalog its models in different formats and places. This collection is an effort to at least keep a list of the main Models Zoos in a single place to the users as well as a starting point for the Data Scientists and AI developers. It is one level above the current `deep-learning` and `machine-learning` topics and `machine-learning` collection once those keep the models themselves, while this one lists the zoos (catalog of models)

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by alanbraz** [comment]
yeah this is not only DL, but both ML and DL once the model zoo are very framework specific

**Comment by alanbraz** [comment]
@styline what do you mean?? will it take too long to approve?

**Comment by styline** [comment]
No  it should be approve, on that platform some aspects have been explored, anyway the association of zoo and AI offers a bad perception due to the strange changing climate we belong, it is my opinion and a master has to help the success step by step

**Comment by alanbraz** [comment]
any chance to get approved???

**Comment by alanbraz** [comment]
getting 404 at https://github.com/collections/ai-model-zoos 
is this expected?? should I wait some time to get really available?

**Comment by talsafran** [comment]
> is this expected?? should I wait some time to get really available?

Hey @alanbraz. We run some scripts on our end to import the contents of this repo into github.com. So that's why it didn't show up instantly.

It's live now though! **https://github.com/collections/ai-model-zoos**.  Thanks!

Fyi: I actually ran into some issue with our import script. It didn't play nicely with one URL in your collection, so I removed it temporarily in https://github.com/github/explore/pull/277. It's an issue on our end – we'll schedule some time to dig in. Sorry about that. Computers are finicky 😄

**Pull request merged**
