### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by papnoisanjeev**
Add UVdesk (Ticketing Support System)  in listing.

### Which change are you proposing?
Need to add UVdesk (Ticket support system) in listing.

---------------------------------------------------------------------

### CODE REVIEW

**Comment by mvkaran** [comment]
Hey @papnoisanjeev! Thanks for your contribution! 😃  Can you please fill up the pull request template [from here](https://github.com/github/explore/blob/master/.github/PULL_REQUEST_TEMPLATE.md) completely and post it as a comment on this PR?

**Comment by papnoisanjeev** [comment]
> Hey @papnoisanjeev! Thanks for your contribution! 😃 Can you please fill up the pull request template [from here](https://github.com/github/explore/blob/master/.github/PULL_REQUEST_TEMPLATE.md) completely and post it as a comment on this PR?

Not able to check any checkboxes :(

**Comment by mvkaran** [comment]
Hey @papnoisanjeev - you won't be able to directly check the boxes from the template that I shared, since that's an MD file. You need to copy the content and paste it either as a comment here or update the content of the PR body and then check the boxes.

**Comment by kenyonj** [comment]
Feel free to re-open when ready. Thanks!

**Comment by papnoisanjeev** [comment]
@kenyonj 
https://github.com/papnoisanjeev/explore/commit/884fd695f164aa51899c7797ed392fbb8f5ff704

**Comment by mvkaran** [comment]
Thanks for your contribution @papnoisanjeev  ❤️. Unfortunately, as per our contribution guidelines, we don't allow self-promotion if you are affiliated with the project:

> Maintainers of a project cannot add a topic or collection for their own project. If a topic is popular enough to warrant inclusion, someone else will add or improve it.


We do this so that project gets curated if there is enough support/activity in the community. Thank you!

**Pull request closed without merging**
