### PR TITLE
Fix a couple things with spacevim, nim topics

### PR DESCRIPTION
**Pull request by cheshire137**
This makes a couple small fixes to two existing topics:

- A couple grammar fixes for nim. /cc @data-man 
- Fixes unintentional wrapping in the spacevim body from newlines being rendered as `<br>` tags. See before:

    topic__spacevim

    /cc @wsdjeg

### CODE REVIEW

**Comment by data-man** [comment]
@cheshire137 
Thanks!
When Nim will be in the topics?  :-)

**Comment by wsdjeg** [comment]
nice，:)

**Comment by cheshire137** [comment]
@data-man, I just pulled in the changes for nim, you can see them at https://github.com/topics/nim. That's when I noticed the missing "language" and the other things I changed. Those changes should be live shortly, once I merge this PR. 🎉 

Thanks for the quick reviews!

**Comment by data-man** [comment]
@cheshire137 
I mean the list of topics https://github.com/topics

**Comment by cheshire137** [comment]
> the list of topics

Ahh, that list is a subset of all the topics that are in this repository. I think we've not been adding topics to that list unless they have about 500 repositories using them.

**Comment by data-man** [comment]
I could be wrong, but I think Nim has more than 500 repositories. :-)

**Comment by cheshire137** [comment]
> I think Nim has more than 500

Hmm, I'm seeing a little under 400, looking at https://github.com/topics/nim + https://github.com/topics/nim-lang + https://github.com/topics/nim-language + https://github.com/topics/nimlang.

**Comment by data-man** [comment]
https://github.com/search?l=Nim&q=nim&type=Repositories give me 1,345 results

**Comment by cheshire137** [comment]
Thanks for the link! The /topics page displays topics based on how many repositories have explicitly applied them as a topic. The page giving you 1.3k results is based on the language detected for the repositories, not which topics are applied. https://github.com/search?utf8=%E2%9C%93&q=topic%3Anim&type=Repositories is closer to what the /topics/nim page displays.

**Comment by data-man** [comment]
I'm sorry, but I think this is wrong.
This means that the results for **all** languages are incorrect.
Many new github users just don't think (or don't know) about assigning a topic.

**Comment by brandonrosage** [comment]
That's a really interesting problem, @data-man. Makes me wonder if we should consider auto-assigning the respective language-named topics to repos that dynamically identify their language.

**Comment by data-man** [comment]
@brandonrosage 
> we should consider auto-assigning the respective language-named topics to repos that dynamically identify their language.

I wanted to suggest the same thing. :-)

**Comment by cheshire137** [comment]
Thanks for your feedback. The goal of the Topics page is to help more people discover topics that have been applied to repositories. If you've noticed that not enough people are using the `nim` topic, you may want to let them know about it!

**Comment by data-man** [comment]
@cheshire137 
> you may want to let them know about it!

In our Gitter channel we [did](https://gitter.im/nim-lang/Nim?at=5a4e6337232e79134dc727d0) so.
But the problem is that very few people using this system for communication.
We invite you!
If I were closer, I'd invite you for a glass of tea. The Earl Grey, of course. :-)

**Comment by wsdjeg** [comment]
I think It should be managered by repo admin himself， People who want to support a  topic, He will add the topic himself. and topic is difference from language, A language contains many topic,  and different language also may has same topic.

**Comment by brandonrosage** [comment]
I think the tension here is that a "topic" on GitHub can be interpreted (understandably) broadly as a "keyword" for which repos, users, and other things are "results." 

Instead, we're asking folks to intuit that a "topic" on GitHub is a "tag" for which repos (the only entity GitHub _currently_ associates with topics) must be actively "tagged" with.

That's some tension we (namely, us folks designing the Explore experience) are going to have to address in short order.

**Pull request merged**
