### PR TITLE
Add Homebrew topic

### PR DESCRIPTION
**Pull request by nayafia**
- [X] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md

I am:
  - [ ] Suggesting edits to an existing Topic page
  - [X] Curating a new Topic page

***********EDITING AN EXISTING TOPIC PAGE************

I'm suggesting these edits to an existing topic:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288)
- [ ] Content (and my changes are in `index.md`)

Please explain why these changes are necessary:

************CURATING A NEW TOPIC PAGE************

- [X] I've formatted my changes as a new folder directory, named for the topic as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]`)
- [X] My folder contains a `*.png` image (if applicable) and `index.md`
- [X] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

Please explain why you think this Topic page should be curated:
Homebrew has 700+ repositories tagged with this topic (`homebrew`, `brew`)

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
I'm clearly biased but ✅ and 🚢ing anyway 😆

**Comment by MikeMcQuaid** [comment]
Thanks so much for your contribution! Without people like you submitting PRs we couldn't run this project. You rock, @nayafia!

**Comment by cheshire137** [comment]
Haha I saw this got opened and came here to review. I'm not surprised @MikeMcQuaid already approved it. 😆

**Comment by MikeMcQuaid** [comment]
> came here to review

@cheshire137 you spelled "reject" wrong 🤣

**Pull request merged**
