### PR TITLE
Add OpenBSD topic

### PR DESCRIPTION
**Pull request by ligurio**
### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---------------------------------------------------------------------

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

OpenBSD is a popular operating system and there are many repositories related to OpenBSD are available on GitHub. It would be nice to have a topic with description and logo for that operating system.

### CODE REVIEW

**Review by krishdevdb — APPROVED** [review]
LGMT

**Comment by ligurio** [comment]
@deniseyu, could you review?

**Comment by krishdevdb** [comment]
I could but I don't have write access to the repo. So nothing will change but here you go

**Review by krishdevdb — APPROVED** [review]

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
Thanks so much for your first contribution! Without people like you submitting PRs we couldn't run this project. You rock, @ligurio!

**Pull request merged**
