### PR TITLE
Add Sailfish OS topic

### PR DESCRIPTION
**Pull request by HenkKalkwater**
### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---------------------------------------------------------------------

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

> There are quite a few repositories with this topic. Besides, mobile Linux OS's could use some love and Sailfish OS is one of
the bigger and older ones. There's also an active community developing open source applications for Sailfish OS.

---------------------------------------------------------------------
I went with "sailfish-os" (56 repos) as the main topic and "sailfishos" (340 repos) as an alias, even though the latter has more repositories, due to it officially being spelled as two words instead of one.

### CODE REVIEW

**Review by kenyonj — CHANGES_REQUESTED** [review]
It looks like the `sailfishos` (https://github.com/topics/sailfishos) topic is more widely used than `sailfish-os` (https://github.com/topics/sailfish-os). What do you think about swapping the main name and the alias here?

**Comment by HenkKalkwater** [comment]
Sure, I've changed it.

**Review by kenyonj — APPROVED** [review]
💯 🍨 Thank you for your contribution! I'll merge this in as soon as CI is 🍏

**Comment by HenkKalkwater** [comment]
It seems like I accidentally made a typo which caused the CI to fail. It should be fixed now.

**Pull request merged**
