### PR TITLE
Add fish

### PR DESCRIPTION
**Pull request by j-f1**
### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection

---------------------------------------------------------------------

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

It’s a pretty cool shell, and the topic has almost 500 repos tagged with it.

---------------------------------------------------------------------

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by j-f1** [comment]
cc @ridiculousfish

**Comment by MikeMcQuaid** [comment]
@j-f1 That's not valid YAML markup, see the test failures.

**Comment by MikeMcQuaid** [comment]
Thanks again so much for your repeated contribution! Without people like you submitting PRs we couldn't run this project. You rock, @j-f1!

**Comment by j-f1** [comment]
Thanks @MikeMcQuaid!

I’m one of the maintainers of [Prettier](https://prettier.io). Since the `prettier` topic has almost 700 repos, would you be OK with me adding it even though I’m affiliated?

**Comment by MikeMcQuaid** [comment]
@j-f1 Yes and thanks for asking!

**Pull request merged**
