### PR TITLE
Updated Cheatsheet to more readable form

### PR DESCRIPTION
**Pull request by CursedSpiderBoi**
### Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: <https://github.com/github/explore/blob/main/CONTRIBUTING.md>.
- [x] I am not the sole author or employee of a company who created the topic or collection I'm changing.

### Which change are you proposing?

  - [x] Suggesting edits to an existing topic or collection
  - [ ] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288, size <= 75 kB)
- [x] Content (and my changes are in `index.md`)

> the text was a mess, rearranged it

---

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by CursedSpiderBoi** [comment]
@talsafran can you look into it for me ?
thanks :3

**Comment by octokatherine** [comment]
Sorry, we have a standard format that is the same for all collections. I see how it might not be the most readable format when viewing the markdown, but this is just meant to be the data backing the more user-friendly UI here: https://github.com/collections/cheatsheets

**Comment by CursedSpiderBoi** [comment]
@octokatherine thanks for letting me know

**Comment by CursedSpiderBoi** [comment]
got it

**Pull request closed without merging**
