### PR TITLE
Adding the 3ds-homebrew Topic.

### PR DESCRIPTION
**Pull request by Colack**
### Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: <https://github.com/github/explore/blob/main/CONTRIBUTING.md>.
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: <https://github.com/github/explore/tree/main/docs>

> There are 137 different repositories for the 3ds hacking scene, and its one of the most popular for homebrew, so I think it should get a topic.

---

### CODE REVIEW

**Review by kenyonj — CHANGES_REQUESTED** [review]
Looks like there is a CI failure regarding the logo:

```
  2) Failure:
topics::3ds-homebrew topic#test_0019_has at most one image with the right name, type, and dimensions [/home/runner/work/explore/explore/test/topics_test.rb:229]:
topic images should be 288px wide.
Expected: 288
  Actual: 2000
```

**Comment by Colack** [comment]
hmmmm. Ill go resize that in Paint....

**Comment by Colack** [comment]
hmmmmmmm.. Ive added the smaller file, but it looks player. Tell if that works.

**Comment by kenyonj** [comment]
> hmmmmmmm.. Ive added the smaller file, but it looks player. Tell if that works.

CI is still failing, see here: https://github.com/github/explore/runs/6481860460?check_suite_focus=true#step:4:17

**Comment by Colack** [comment]
Ok. I'm going to open a new pull request with the new files, since this one does not want to show the new files.

**Pull request closed without merging**
