### PR TITLE
Fix "duplicated mapping key"

### PR DESCRIPTION
**Pull request by shaedrich**
### Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: <https://github.com/github/explore/blob/main/CONTRIBUTING.md>.
- [x] I am not the sole author or employee of a company who created the topic or collection I'm changing.

### Which change are you proposing?

  - [x] Suggesting edits to an existing topic or collection
  - [ ] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288, size <= 75 kB)
- [x] Content (and my changes are in `index.md`)

The `aliases` key is duplicated—while GitHub's markdown YAML frontmatter parser is not currently bothered, it doesn't mean, it stays that way or others aren't. Plus, it might confuse other contributors who might miss one of the `aliases` at the first glance and might attempt to add supposedly missing `aliases`.

### Curating a new topic or collection

- [ ] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [ ] My folder contains a `*.png` image (if applicable) and `index.md`
- [ ] All required fields in my `index.md` conform to the Style Guide and API docs: <https://github.com/github/explore/tree/main/docs>

> Please replace this line with an explanation of why you think this topic or collection should be curated.

### Something that does not neatly fit into the binary options above

- [ ] My suggested edits are not about an existing topic or collection, or at least not a single one
- [ ] My suggested edits are not about curating a new topic or collection, or at least not a single one
- [ ] My suggested edits conform to the Style Guide and API docs: https://github.com/github/explore/tree/main/docs

> Please replace this line with an explanation of your proposed changes.

---

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Review by ahpook — APPROVED** [review]
Good catch.

Are you linting these in some way that the tests aren't catching...? This should probably have caused a test failure on first commit.

**Comment by shaedrich** [comment]
@ahpook Even though, the YAML spec forbids all kinds of divergences from it, parser implementations are usually quite lax. However, the one, I happen to use at [`shaedrich/github-uncurated-topics/user-topics`](https://shaedrich.gitlab.io/github-uncurated-topics/user-topics.html) is not, so this and a couple of others caused it to fail. That led me to investigate the error, and I came across a closed issue of that package where the author refused to let his package ignore these little divergences from the spec like most other implementations do. Sorry for going a bit far afield 😬 😅

**Comment by ahpook** [comment]
Ah thanks. Appreciate your battle against the forces of entropy. 🦾

**Comment by shaedrich** [comment]
I do, what I can 😅  Even though, the error itself might have been outside my reach, it reminded me to wrap that particular part of code in a try-catch block

**Pull request merged**
