### PR TITLE
upload image and update index.md

### PR DESCRIPTION
**Pull request by amansrivastava462**
### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---------------------------------------------------------------------

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [x] Image (and my file is `*.png`, square, dimensions 288x288)
- [x] Content (and my changes are in `index.md`)

> Please replace this line with an explanation of why you think these changes should be made.

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

> Please replace this line with an explanation of why you think this topic or collection should be curated.

### Something that does not neatly fit into the binary options above

- [ ] My suggested edits are not about an existing topic or collection, or at least not a single one
- [ ] My suggested edits are not about curating a new topic or collection, or at least not a single one
- [x] My suggested edits conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

> Please replace this line with an explanation of your proposed changes.

---------------------------------------------------------------------

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Review by kenyonj — CHANGES_REQUESTED** [review]
The addition of a topic image isn't going to work in this PR since we need all the other topic information for that. Also, that topic only has the one repository of `uvdesk/community-skeleton` so it will not be accepted.

For this PR: Can you confirm that you are not involved in the project? We have a strict policy on avoiding conflicts of interest laid out in our [contributing docs](https://github.com/github/explore/blob/master/CONTRIBUTING.md).

Thanks!

**Comment by amansrivastava462** [comment]
**The addition of a topic image isn't going to work in this PR since we need all the other topic information for that. Also, that topic only has the one repository of uvdesk/community-skeleton so it will not be accepted.**
I didn't understand your concern, could you please let me know. what is needful to be accepted this project

**For this PR: Can you confirm that you are not involved in the project? We have a strict policy on avoiding conflicts of interest laid out in our contributing docs.**
yes I am only the user of this project, which is ticket based helpdesk system from india.

Best Regards

**Comment by kenyonj** [comment]
> I didn't understand your concern, could you please let me know. what is needful to be accepted this project ?

See here for our contribution guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md

> Valuable topics, for example, include those that are already widely used by repositories and could benefit from the addition of important information.

Since this topic is only used on 1 repository it does not meet that requirement.

**Comment by arabguy** [comment]
Justin, you're welcome to join the group and comment and work on the
project the chromium OS recovery project I am currently conducting let me
know what you think.

**Pull request closed without merging**
