### PR TITLE
Move topic `visual-studio-code` to `vscode`.

### PR DESCRIPTION
**Pull request by Nixinova**
### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [x] Suggesting edits to an existing topic or collection
  - [ ] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---------------------------------------------------------------------

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288)
- [x] Content (and my changes are in `index.md`)

#### Description
Moves primary topic of VS Code from [`visual-studio-code`](https://github.com/topics/visual-studio-code) (2K repos) to [`vscode`](https://github.com/topics/vscode) (7K repos).

Topic `vscode` has more repositories than `visual-studio-code` so it is better to have the former be the primary topic.

### CODE REVIEW

**Review by nholden — COMMENTED** [review]
Thank you for the contribution! ❤️ 

This change makes sense to me. @MikeMcQuaid: could you confirm that there wouldn't be any unintended consequences of indexing the `vscode` topic instead of the `visual-studio-code` topic?

**Comment by MikeMcQuaid** [comment]
@nholden From what I know: no but @kenyonj or @damaneice may be able to confirm for sure?

**Comment by kenyonj** [comment]
No unintended consequences that I can think of, but no real benefit either since `vscode` is already an alias for this topic. Unless I am missing a benefit, I might argue to leave it as is to not cause the file rename churn.

**Comment by MikeMcQuaid** [comment]
@kenyonj Works for me too 👍🏻

**Comment by nholden** [comment]
Thanks, @kenyonj and @MikeMcQuaid! Since the existing alias means there's not a real benefit to this change, I'm going to close this PR out.

**Pull request closed without merging**
