### PR TITLE
Add Nuxt.js topic

### PR DESCRIPTION
**Pull request by clarkdo**
### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection

---------------------------------------------------------------------

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

> Nuxt.js is a popular framwork which has gotten 20K stars in Github and we have very active community, so the topic may help users a lot.
---------------------------------------------------------------------

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by kenyonj** [comment]
Hi @clarkdo  ,
Thanks for starting this pull request. I see that you checked this:

> I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee)

However, it appears you are part of the core team. In order to maintain our level of independence, we are unable to accept submissions from these affiliated users. Perhaps, in the future, one of the members of the community will add this topic.

Thanks!

**Comment by clarkdo** [comment]
@kenyonj Sorry, I missed checking that options, I’m one of main maintainers of this project, is it possible to reopen this or?
/cc @atinux as he is the creator of the framework

**Comment by kenyonj** [comment]
Hi @clarkdo, sorry for the confusion. Here is the part of our CONTRIBUTING.md that I am referencing:

[Guidelines](https://github.com/github/explore/blob/master/CONTRIBUTING.md#guidelines)
>Avoid conflicts of interest. Maintainers of a project cannot add a topic or collection for their own project. If a topic is popular enough to warrant inclusion, someone else will add or improve it.

**Comment by clarkdo** [comment]
Ah, I gotcha, thanks

**Pull request closed without merging**
