### PR TITLE
add topic: extension

### PR DESCRIPTION
**Pull request by isasharafdin**
### Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: <https://github.com/github/explore/blob/main/CONTRIBUTING.md>.
- [x] I am not the sole author or employee of a company who created either the topic I am modifying/adding or the collection entry I am modifying/adding.

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288, size <= 75 kB)
- [ ] Content (and my changes are in `index.md`)

> Please replace this line with an explanation of why you think these changes should be made.

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [ ] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: <https://github.com/github/explore/tree/main/docs>

I propose a new "Extensions" topic due to their key role in augmenting software functionality and personalization. A dedicated GitHub topic will streamline access to extension-related projects, enhance community engagement, and boost innovation across multiple domains.

### Something that does not neatly fit into the binary options above

- [ ] My suggested edits are not about an existing topic or collection, or at least not a single one
- [ ] My suggested edits are not about curating a new topic or collection, or at least not a single one
- [ ] My suggested edits conform to the Style Guide and API docs: https://github.com/github/explore/tree/main/docs

> Please replace this line with an explanation of your proposed changes.

---

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by AdamRaichu** [comment]
Just a thought, but I see that you linked the wiki article for Browser Extension, but list IDE Plugins and OS Extensions side by side with Browser Extensions in the topic description. Perhaps a different article should be linked (one that would be relevant to all three subcategories you listed), or the wiki link should be removed altogether?

**Comment by isasharafdin** [comment]
> Just a thought, but I see that you linked the wiki article for Browser Extension, but list IDE Plugins and OS Extensions side by side with Browser Extensions in the topic description. Perhaps a different article should be linked (one that would be relevant to all three subcategories you listed), or the wiki link should be removed altogether?

The extension wiki I found focuses only on browser extensions, which is why that link was included.  if you could find you can contribute through my profile repo. thanks

**Review by kenyonj — APPROVED** [review]
💯 🍨 Thank you for your contribution! I'll merge this in as soon as CI is 🍏

**Comment by isasharafdin** [comment]
> 💯 🍨 Thank you for your contribution! I'll merge this in as soon as CI is 🍏

thanks for merging my PR i will contribute more on Insha'Allah!

**Pull request merged**
