### PR TITLE
Grammar Correction

### PR DESCRIPTION
**Pull request by Colack**
### Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: <https://github.com/github/explore/blob/main/CONTRIBUTING.md>.
- [x] I am not the sole author or employee of a company who created the topic or collection I am changing.

### Which change are you proposing?

  - [x] Suggesting edits to an existing topic or collection
  - [ ] Curating a new topic or collection
  - [x] Something that does not neatly fit into the binary options above

---

### Something that does not neatly fit into the binary options above

- [ ] My suggested edits are not about an existing topic or collection, or at least not a single one
- [ ] My suggested edits are not about curating a new topic or collection, or at least not a single one
- [x] My suggested edits conform to the Style Guide and API docs: https://github.com/github/explore/tree/main/docs

Grammar correction.

### CODE REVIEW

**Comment by Colack** [comment]
Ah! Sorry I forgot to mark the second checkmark, and that sent an error.

**Review by ahpook — APPROVED** [review]
Thanks for the improvement!

**Comment by ahpook** [comment]
Spurious failure on COI check, merging.

**Comment by Qrahulq** [comment]
RANK 01

**Comment by Mohammed-Alanazisa** [comment]
> ### Please confirm this pull request meets the following requirements:
> * [x]  I followed the contributing guidelines: https://github.com/github/explore/blob/main/CONTRIBUTING.md.
> * [x]  I am not the sole author or employee of a company that created the topic or collection I am changing.
> 
> ### Which change are you proposing?
> * [x]  Suggesting edits to an existing topic or collection
> * [ ]  Curating a new topic or collection
> * [x]  Something that does not neatly fit into the binary options above
> 
> ### Something that does not neatly fit into the binary options above
> * [ ]  My suggested edits are not about an existing topic or collection, or at least not a single one
> * [ ]  My suggested edits are not about curating a new topic or collection, or at least not a single one
> * [x]  My suggested edits conform to the Style Guide and API docs: https://github.com/github/explore/tree/main/docs
> 
> Grammar correction.

**Pull request merged**
