### PR TITLE
Add topic "URI template"

### PR DESCRIPTION
**Pull request by shaedrich**
### Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: <https://github.com/github/explore/blob/main/CONTRIBUTING.md>.
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288, size <= 75 kB)
- [ ] Content (and my changes are in `index.md`)

> Please replace this line with an explanation of why you think these changes should be made.

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: <https://github.com/github/explore/tree/main/docs>

The topic wasn't curated yet and it is somewhat common.

### Something that does not neatly fit into the binary options above

- [ ] My suggested edits are not about an existing topic or collection, or at least not a single one
- [ ] My suggested edits are not about curating a new topic or collection, or at least not a single one
- [ ] My suggested edits conform to the Style Guide and API docs: https://github.com/github/explore/tree/main/docs

> Please replace this line with an explanation of your proposed changes.

---

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by shaedrich** [comment]
By the way: There is another topic called "uri-template**s**" (the plural version). Is that considered an alias or a related topic?

**Comment by smashwilson** [comment]
Shouldn't this be an alias of `rfc-6570` or vice versa?

**Comment by shaedrich** [comment]
@smashwilson Ah, sure. So if there's an alias, there doesn't need to another file, right? So I just change the index.md in the rfc-6570 directory.

**Comment by smashwilson** [comment]
Yup, exactly! There's an `aliases:` key:

https://github.com/github/explore/blob/main/docs/API.md#aliases

**Comment by smashwilson** [comment]
> @smashwilson In case of [`jwt`](https://github.com/github/explore/blob/main/topics/jwt/index.md), the topic is called "jwt" and the RFC is the alias. Do you care if it's that way round or this way with the RFC being the actual document? Sorry for asking that much 😬

I think it makes the most sense for this topic to be the "authoritative" one and have the RFC as an alias. If nothing else, it makes it easier to scan the list of subdirectories and see what's what without having to open up the files to remember. There are a small number of RFCs that I'm personally able to recognize by number alone but this isn't one of them 😆 

> @smashwilson You said, the topic was a bit sparse. Any suggestions how you'd like me to expand its description?

Oh, I meant sparse in terms of usage. I see only 16 repositories in [the `rfc-6570` topic](https://github.com/topics/rfc-6570) and 25 in [`uri-template`](https://github.com/topics/uri-template). We don't have formal guidelines on how much usage a topic has before we accept curation for it, but generally for me it's something like "hundreds-ish of repositories, and not all owned by the same organization or user account". This meets the second criteria fine so I'm willing to have a little slack on the first.

**Comment by shaedrich** [comment]
Oh, right! Thanks for the hint! I fixed it

**Review by smashwilson — APPROVED** [review]
✨ Perfect! Thanks for bearing with me 😁

**Comment by shaedrich** [comment]
Thanks for bearing with _me_ 😁:sweat_smile:

**Pull request merged**
