### PR TITLE
Add Discord

### PR DESCRIPTION
**Pull request by pizzafox**
### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection

---------------------------------------------------------------------

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288)
- [ ] Content (and my changes are in `index.md`)

> Please replace this line with an explanation of why you think these changes should be made.

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

Discord is currently in the `topics-todo.md` file and has an API that lots of open source repositories on GitHub use.

---------------------------------------------------------------------

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by pizzafox** [comment]
I used an SVG from [their branding page](https://discordapp.com/branding)  
(6217ba3) and scaled it up to double the size of the original PNG

**Comment by MikeMcQuaid** [comment]
@pizzafox Still failing I'm afraid: https://travis-ci.org/github/explore/builds/436755590#L540

**Comment by pizzafox** [comment]
You said at least `245px`, Travis wants exactly `288px`. Will update image to those dimensions.

**Comment by MikeMcQuaid** [comment]
> You said at least `245px`, Travis wants exactly `288px`. Will update image to those dimensions.

@pizzafox My mistake and apologies. Thanks for the update!

Thanks so much for your first contribution! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request merged**
