### PR TITLE
Fix liquid URLs

### PR DESCRIPTION
**Pull request by shaedrich**
### Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: <https://github.com/github/explore/blob/main/CONTRIBUTING.md>.
- [x] I am not the sole author or employee of a company who created the topic or collection I'm changing.

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [ ] Curating a new topic or collection
  - [x] Something that does not neatly fit into the binary options above

---

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288, size <= 75 kB)
- [ ] Content (and my changes are in `index.md`)

> Please replace this line with an explanation of why you think these changes should be made.

### Curating a new topic or collection

- [ ] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [ ] My folder contains a `*.png` image (if applicable) and `index.md`
- [ ] All required fields in my `index.md` conform to the Style Guide and API docs: <https://github.com/github/explore/tree/main/docs>

> Please replace this line with an explanation of why you think this topic or collection should be curated.

### Something that does not neatly fit into the binary options above

- [x] My suggested edits are not about an existing topic or collection, or at least not a single one
- [x] My suggested edits are not about curating a new topic or collection, or at least not a single one
- [ ] My suggested edits conform to the Style Guide and API docs: https://github.com/github/explore/tree/main/docs

**Current**:
```json
{
    "topic_name": "3ds-homebrew",
    "created_by": "Nintendo",
    "display_name": "Nintendo 3DS Homebrew",
    "github_url": null,
    "logo": "https://explore-feed.explore-feed.github.com/topics/3ds-homebrew/3ds-homebrew.png",
    "released": 2011,
    "short_description": "3DS Homebrew is the task of producing and running custom code for the Nintendo 3DS system.",
    "url": "https://explore-feed.github.com/topics/3ds-homebrew",
    "wikipedia_url": "https://en.wikipedia.org/wiki/Homebrew_(video_games)#3DS",
    "related": [          
        "custom-firmware",          
        "nintendo-3ds"          
    ],
    "aliases": [
        "nintendo-3ds-homebrew",
        "3ds-custom-firmware"
    ],
    "content": "<p>Homebrew, when applied to video games, refers to games produced by hobbyists for proprietary video game consoles which are not intended to be user-programmable. 3DS Homebrew specifically refers to producing and running custom code on the Nintendo 3DS system. This may include custom firmware, emulators, and other applications not authorized by Nintendo.</p>\n"
}
```

**Expected**:
```json
{
    "topic_name": "3ds-homebrew",
    "created_by": "Nintendo",
    "display_name": "Nintendo 3DS Homebrew",
    "github_url": null,
    "logo": "https://explore-feed.github.com/topics/3ds-homebrew/3ds-homebrew.png",
    "released": 2011,
    "short_description": "3DS Homebrew is the task of producing and running custom code for the Nintendo 3DS system.",
    "url": "https://github.com/topics/3ds-homebrew",
    "wikipedia_url": "https://en.wikipedia.org/wiki/Homebrew_(video_games)#3DS",
    "related": [          
        "custom-firmware",          
        "nintendo-3ds"          
    ],
    "aliases": [
        "nintendo-3ds-homebrew",
        "3ds-custom-firmware"
    ],
    "content": "<p>Homebrew, when applied to video games, refers to games produced by hobbyists for proprietary video game consoles which are not intended to be user-programmable. 3DS Homebrew specifically refers to producing and running custom code on the Nintendo 3DS system. This may include custom firmware, emulators, and other applications not authorized by Nintendo.</p>\n"
}
```

**Differences**
`"logo": "https://`<del>`explore-feed.`</del>`explore-feed.github.com/topics/3ds-homebrew/3ds-homebrew.png",`
`"url": "https://`<del>`explore-feed.`</del>`github.com/topics/3ds-homebrew",`

---

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by shaedrich** [comment]
>   1) Failure:
collections::voxel-editors collection#test_0013_fails if a user, organization, or repository has been renamed or removed [/home/runner/work/explore/explore/test/collections_test.rb:197]:
Expected ["voxel-editors: mgerhardy/vengi has been renamed to vengi-voxel/vengi"] to be empty.

This change should probably be addressed in a separate PR

**Comment by ahpook** [comment]
I don't understand this change, has it been broken for a long time? (How does one even use the json feed?)

**Comment by shaedrich** [comment]
> How does one even use the json feed?

I use it and that's why I even noticed it. However, I didn't rely on links yet and rather focussed on `related` and `aliases`.

> has it been broken for a long time?

Something, I was also wondering in #4019 😂 

It appears to be broken since 2fabae9 from Sep 8, 2022

**Review by ahpook — APPROVED** [review]
Gonna go ahead and merge this.

**Pull request merged**
