### PR TITLE
new topic: gin

### PR DESCRIPTION
**Pull request by thinkerou**
### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [ ] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection

---------------------------------------------------------------------

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288)
- [ ] Content (and my changes are in `index.md`)

> Please replace this line with an explanation of why you think these changes should be made.

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

> Please replace this line with an explanation of why you think this topic or collection should be curated.

---------------------------------------------------------------------

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by thinkerou** [comment]
Because the logo of Gin is't square, if I use `288X288`, it's very ugly. Now I use `208X288`(width X height).

**Comment by thinkerou** [comment]
ci error info:
```
  1) Failure:
collections::github-browser-extensions collection#test_0007_fails if a user, organization, or repository has been renamed [/home/travis/build/github/explore/test/collections_test.rb:90]:
Expected ["github-browser-extensions: rgehan/octolenses-browser-extension has been renamed to rgehan/octolenses"] to be empty.
```

**Comment by thinkerou** [comment]
waiting #657 merged!

**Comment by talsafran** [comment]
Nice suggestion, @thinkerou! Looks like a neat project, thanks✨💖

**Comment by thinkerou** [comment]
@talsafran when the pull request take effect? thanks! https://github.com/topics/gin

**Comment by talsafran** [comment]
@thinkerou thanks for the reminder! We have to run something on our end 😄 

Should be up now 👉https://github.com/topics/gin , thank you again!

**Comment by thinkerou** [comment]
@talsafran thanks a lot

**Pull request merged**
