### PR TITLE
Update Atom Icon

### PR DESCRIPTION
**Pull request by vutondesign**
- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md

I am:
  - [x] Suggesting edits to an existing Topic page
  - [ ] Curating a new Topic page

I'm suggesting these edits to an existing topic:
- [x] Image (and my file is `*.png`, square, dimensions 288x288)
- [ ] Content (and my changes are in `index.md`)

Please explain why these changes are necessary:
As stated in a blog post, the Atom logo has now changed slightly.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
> As stated in a blog post, the Atom logo has now changed slightly.

@vutondesign Which blog post? Thanks!

**Comment by vutondesign** [comment]
@MikeMcQuaid Hey, It's here - https://discuss.atom.io/t/new-atom-logo-and-icon/8704

**Comment by MikeMcQuaid** [comment]
Hey @vutondesign, that's from 2014 and doesn't seem to be the current icon. @lee-dohm can you correct me if I'm wrong here? Thanks!

**Comment by lee-dohm** [comment]
@MikeMcQuaid Sure thing! The current icon is [here in the atom/atom repo](https://github.com/atom/atom/blob/master/resources/app-icons/stable/png/256.png). There are other sizes in that directory as well.

**Comment by MikeMcQuaid** [comment]
Thanks @lee-dohm!

Yeh, @vutondesign, that's the current icon as-is in this repo so closing this PR, sorry!

**Pull request closed without merging**
