### PR TITLE
feat: create bevy topic

### PR DESCRIPTION
**Pull request by BD103**
### Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: <https://github.com/github/explore/blob/main/CONTRIBUTING.md>.
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: <https://github.com/github/explore/tree/main/docs>

> Bevy is a game engine in Rust that blew up in popularity. While only being released in 2020, it already shows signs of becoming a effective yet simple game engine.

---

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Review by kenyonj — APPROVED** [review]
💯 🍨 Thank you for your contribution! I'll merge this in as soon as CI is 🍏

**Review by kenyonj — CHANGES_REQUESTED** [review]
Current CI failures:
```rb
1) Failure:
topics::bevy topic#test_0006_ends 'short_description' with punctuation [/home/runner/work/explore/explore/test/topics_test.rb:78]:
short_description should end with punctuation.
Expected /[.?!]\z/ to match "A refreshingly simple data-driven game engine built in Rust".
  2) Failure:
topics::bevy topic#test_00[19](https://github.com/github/explore/runs/6903808794?check_suite_focus=true#step:4:20)_has at most one image with the right name, type, and dimensions [/home/runner/work/explore/explore/test/topics_test.rb:[22](https://github.com/github/explore/runs/6903808794?check_suite_focus=true#step:4:23)9]:
topic images should be 288px wide.
Expected: 288
  Actual: 256
  3) Failure:
topics::bevy topic#test_00[25](https://github.com/github/explore/runs/6903808794?check_suite_focus=true#step:4:26)_follows the Topic Page Style Guide [/home/runner/work/explore/explore/test/topics_test.rb:310]:
Use open source without a hyphen.
Expected "Bevy is a refreshingly simple data-driven game engine built in Rust. It is free and open-source forever!" to not include "open-source".
```

**Comment by BD103** [comment]
Ok, I fixed the CI errors.

**Review by kenyonj — APPROVED** [review]

**Comment by BD103** [comment]
Any idea why the CI is still failing? I haven't used Rubocop before.

**Comment by MisileLab** [comment]
> Any idea why the CI is still failing? I haven't used Rubocop before.

Maybe bot can't push to your forked repository.

**Comment by kenyonj** [comment]
> > Maybe bot can't push to your forked repository.
> 
> CC @kenyonj for help here

Yes, that is the case (the bot can't push to a fork). I am working on a fix now and should have this PR green shortly.

**Comment by BD103** [comment]
Thanks for the merge! :)

**Pull request merged**
