### PR TITLE
Remove CasperJS from OpenSource Testing

### PR DESCRIPTION
**Pull request by valfirst**
### Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: <https://github.com/github/explore/blob/main/CONTRIBUTING.md>.
- [x] I am not the sole author or employee of a company who created the topic or collection I'm changing.

### Which change are you proposing?

  - [x] Suggesting edits to an existing topic or collection
  - [ ] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288, size <= 75 kB)
- [x] Content (and my changes are in `index.md`)

https://github.com/casperjs/casperjs:
> CasperJS is no longer actively maintained.

---

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by Semfoxm** [comment]
Semfoxm

**Comment by kenyonj** [comment]
While this repository is indeed archived, we aren't currently removing it because it remains a valid resource. If that should change in the future, or if the repository is deleted/removed/privatized, we will remove it from this list.

Thank you!

**Comment by valfirst** [comment]
@kenyonj does it make sense to de-prioritize such repos? because whenever you browse https://github.com/collections/opensource-testing, there are a lot of unmaintained repos in top

**Comment by kenyonj** [comment]
> @kenyonj does it make sense to de-prioritize such repos? because whenever you browse https://github.com/collections/opensource-testing, there are a lot of unmaintained repos in top

That does make sense, however, we haven't been able to prioritize the work to do that in a programmatic way so the current system remains.

**Pull request closed without merging**
