### PR TITLE
added topics for PIM and Org mode

### PR DESCRIPTION
**Pull request by novoid**
### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

There are lots of projects in both topics I added.

PIM needs to have an explanation that two different phrases are the most relevant for the same abbreviation.

Org mode has a very strong and active community, providing many source code projects which deserves a brief explanation.

### CODE REVIEW

**Review by gallexi — APPROVED** [review]
Thanks for your contribution!

**Comment by gallexi** [comment]
Oops, ack, just went to update this on our end and apparently there is a "50 character limit" on the display name. Thoughts on, for the PIM topic, making the display name "PIM" and then keeping "Personal Information Management OR Product Information Management." as the description?

**Comment by novoid** [comment]
> Oops, ack, just went to update this on our end and apparently there is a "50 character limit" on the display name. Thoughts on, for the PIM topic, making the display name "PIM" and then keeping "Personal Information Management OR Product Information Management." as the description?

@gallexi 
Yes, that's OK to me. Are you able to do the changes?

**Comment by gallexi** [comment]
Yes! Either you @novoid can open another PR with that new change here, or I can go ahead and do it, whichever you'd prefer ✨

**Comment by novoid** [comment]
> Yes! Either you @novoid can open another PR with that new change here, or I can go ahead and do it, whichever you'd prefer sparkles

I do think that you're much quicker than I am. Thanks for your help! :+1:

**Pull request merged**
