### PR TITLE
Add Fortran to GH community curated topic

### PR DESCRIPTION
**Pull request by zbeekman**
### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

Note: Fortran is standardized programming language, formerly by ANSI, and currently by ISO. I am __NOT__ a member of the J3 (U.S. based) or WG5 (international) standards committee, __NOR__ do I work for a commercial compiler vendor.

I do use Fortran on a daily basis both for work and for hobby projects, and contribute to open source Fortran projects and organizations.

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection

---------------------------------------------------------------------

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
  - Note: There is no official logo for the language
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

While Fortran is arguably the oldest compiled language (with an optimizing compiler), it continues to update and modernize its syntax and plays a very important role in our daily lives. Critically, it is the language used to implement every numerical weather prediction model (that I am aware of) and many/most climate science research models. As such its used indirectly by millions of people around the world on a daily basis when they check the weather, and may be critical the ongoing health and viability of our planet.

Unfortunately, there are a few problems that plague Fortran, Fortran programmers, and the Fortran software ecosystem as a whole:

1. __Outdated perceptions:__ People often are unaware of modern Fortran, and often perceive it as outdated and clunky (i.e., Fortran 77 and earlier)
2. __Slow or buggy compiler updates:__ This is really related to the point above in that the Fortran community has a lack of human capital. Commercial and open source compiler vendors have trouble recruiting compiler engineers and allocating the required time and resources to implement revisions to the standard. This has a negative feedback that can tarnish people's perceptions of Fortran
3. __Not enough community and tooling:__ Again, this relates to points one and two above and creates a bad feedback loop. Furthermore, the majority of Fortran programmers are application scientists or engineers, often with little or no formal training in computer science.

My hope is that formalizing a community curated Fortran topic on github will both expose more people to high-quality Fortran projects and tooling, and allow the existing Fortran developers and projects to coalesce around the topic. This obviously will not be a panacea, but it might be one small step towards solving the "cobbler's children have no shoes" problem while building additional community.

---------------------------------------------------------------------

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by zbeekman** [comment]
Didn't seem to like my force push... also a few other things are failing. I'll try to fix those also.

**Comment by zbeekman** [comment]
FYI, it's not completely clear to me: Can aliases or topics *ever* contain uppercase letters? I've stripped all uppercase letters, but people often use the antiquated FORTRAN spelling, so I just wanted to ensure we captured all the appropriate aliases.

Also, please let me know if you want me to squash/rebase/split-into-multiple-PRs

**Comment by filips123** [comment]
Topics should be case insensitive, so it is OK.

**Comment by zbeekman** [comment]
@kenyonj (and @filips123 ?) Please let me know if you want me to squash this all down into one commit rebased on master, or whether there are any additional changes you would like me to implement.

**Comment by o1ndayy** [comment]
Master copy judged no commit
________________________________

**Comment by kenyonj** [comment]
Looks like there isn't a consensus on what the Fortran logo should be, so lets not have that block this change.

**Comment by zbeekman** [comment]
I don't like the linked unofficial logo, and yes, there is no official logo. I may bring it up with the J3/WG5 (ISO) folks and maybe we can get something, but for now I suggest leaving it without a logo. Thanks for merging!

**Pull request merged**
