### PR TITLE
Alita

### PR DESCRIPTION
**Pull request by imhele**
### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection

---------------------------------------------------------------------

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

It's always not easy to develop and maintain a project. In a lot of demand and limited time, we need to focus more on the project itself, rather than being trapped in a lot of messy documents, hard-to-trace crashes, frequent mistakes in collaboration, no way to start any optimization.

As the industry continues to evolve and new technologies continue to emerge, more and more developers are beginning to focus on their own development experience. With such an ultimate goal, Alita began to explore low-threshold, high-performance, easy-to-expand development and maintenance solutions, enhance the development experience through pluggable features, and allow developers to focus more on the project itself.

---------------------------------------------------------------------

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by xiaohuoni** [comment]
LGTM

**Comment by HuoXiaoYe** [comment]
very good

**Comment by ShawDanon** [comment]
nice

**Comment by DiamondYuan** [comment]
LGTM

**Comment by xiaohuoni** [comment]
@kenyonj cc

**Comment by talsafran** [comment]
Hi @imhele  thanks for the contribution ❤️. Unfortunately, as per our [contribution guidelines](https://github.com/github/explore/blob/master/CONTRIBUTING.md#guidelines), we don't allow self promotion if you are a maintainer of the project:

> Unaffiliated with the project (not self-promoting as e.g. a maintainer, creator, contractor or employee)

We do this so that project get curated if there is enough support/activity in the community. Thank you!

**Pull request closed without merging**
