### PR TITLE
Cypher 3 victor+ MI +Teeto +Ceemos +Jesse jagz 

### PR DESCRIPTION
**Pull request by m-star5**
### Thank you for contributing! Please confirm this pull request meets the following [Cypher 3 ](https://youtu.be/flMehELsznw  ) requirements:

- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---------------------------------------------------------------------

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [x] Image (and my file is `*.png`, square, dimensions 288x288)
- [x] Content (and my changes are in `index.md`)

> Please replace this line with an explanation of why you think these changes should be made.

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

> Please replace this line with an explanation of why you think this topic or collection should be curated.

### Something that does not neatly fit into the binary options above

- [x] My suggested edits are not about an existing topic or collection, or at least not a single one
- [x] My suggested edits are not about curating a new topic or collection, or at least not a single one
- [x] My suggested edits conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

> Please replace this line with an explanation of your proposed changes.

---------------------------------------------------------------------

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by m-star5** [comment]
Hello world

**Comment by deniseyu** [comment]
Hi @m-star5, it looks like this PR is not comparing to the active base branch, so the history isn't correct.

If you're trying to add content, please run

```
git checkout origin master
git pull origin master
git checkout <branch name>
git rebase master
git push --force origin HEAD
```

**Comment by m-star5** [comment]
@m-star5
The best rapper in the world 
https://youtu.be/zA9jersJYzA

**Comment by m-star5** [comment]
I love this

**Comment by m-star5** [comment]
> @m-star5
> The best rapper in the world
> https://youtu.be/zA9jersJYzA

**Pull request closed without merging**
