### PR TITLE
Add functional-programming topic

### PR DESCRIPTION
**Pull request by Kristories**
### Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: <https://github.com/github/explore/blob/main/CONTRIBUTING.md>.
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288, size <= 75 kB)
- [ ] Content (and my changes are in `index.md`)

> Please replace this line with an explanation of why you think these changes should be made.

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [ ] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: <https://github.com/github/explore/tree/main/docs>

> Please replace this line with an explanation of why you think this topic or collection should be curated.

### Something that does not neatly fit into the binary options above

- [ ] My suggested edits are not about an existing topic or collection, or at least not a single one
- [ ] My suggested edits are not about curating a new topic or collection, or at least not a single one
- [ ] My suggested edits conform to the Style Guide and API docs: https://github.com/github/explore/tree/main/docs

> Please replace this line with an explanation of your proposed changes.

---

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by Kristories** [comment]
Please check the lint action @kenyonj  : 

```
RuboCop is not installed
```

**Comment by Sanoussi85** [comment]
Vulnerablr

**Comment by Sanoussi85** [comment]
Vulnérable

**Comment by Sanoussi85** [comment]
From 7a2c54979b86243fba231e0aab9bfbc520884ca3 Mon Sep 17 00:00:00 2001
From: Sanoussi Djibrilla  <w.sanoussidjibrilla85@gmail.com>
Date: Sat, 29 Oct 2022 05:24:45 +0700
Subject: [PATCH] Add functional-programming topic

---
 topics-todo.md                         | 2 +-
 topics/functional-programming/index.md | 8 ++++++++
 2 files changed, 9 insertions(+), 1 deletion(-)
 create mode 100644 topics/functional-programming/index.md

diff --git a/topics-todo.md b/topics-todo.md
index f9622027183..72f0db84cae 100644
--- a/topics-todo.md
+++ b/topics-todo.md
@@ -31,7 +31,7 @@ Information included in this repository will appear on each topic's respective p
 - [ ] [education](https://github.com/topics/education/)
 - [x] [elasticsearch](https://github.com/topics/elasticsearch/)
 - [ ] [example](https://github.com/topics/example/)
-- [ ] [functional-programming](https://github.com/topics/functional-programming/)
+- [x] [functional-programming](https://github.com/topics/functional-programming/)
 - [x] [game-development](https://github.com/topics/game-development/)
 - [ ] [generator](https://github.com/topics/generator/)
 - [x] [gui](https://github.com/topics/gui/)
diff --git a/topics/functional-programming/index.md b/topics/functional-programming/index.md
new file mode 100644
index 00000000000..a10cb9c0698
--- /dev/null
+++ b/topics/functional-programming/index.md
@@ -0,0 +1,8 @@
+---
+display_name: Functional programming
+short_description: Functional programming is a programming paradigm where programs are constructed by applying and composing functions.
+topic: functional-programming
+wikipedia_url: https://en.wikipedia.org/wiki/Functional_programming
+---
+
+In computer science, functional programming is a programming paradigm where programs are constructed by applying and composing functions. It is a declarative programming paradigm in which function definitions are trees of expressions that map values to other values, rather than a sequence of imperative statements which update the running state of the program.
\ No newline at end of file

**Review by kenyonj — APPROVED** [review]
Looks great. Thanks for your contribution!

**Pull request merged**
