### PR TITLE
Add fantasy console collection 💾 

### PR DESCRIPTION
**Pull request by leereilly**
This PR adds a small collection of open source fantasy consoles.

- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---------------------------------------------------------------------

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

I find them fantastic... punt intended.

### CODE REVIEW

**Review by AndreaGriffiths11 — APPROVED** [review]
LGTM!

**Comment by Candycrushlove** [comment]
IMG_20210523_172009
Live is through your eyes

**Comment by Candycrushlove** [comment]
Be More Then  They Expect 
Screenshot_2021-04-20-00-15-37

**Comment by Candycrushlove** [comment]
Be the fantasy 
IMG_20210604_201758

**Pull request merged**
