### PR TITLE
Add WebXR topic

### PR DESCRIPTION
**Pull request by msub2**
### Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: <https://github.com/github/explore/blob/master/CONTRIBUTING.md>.
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: <https://github.com/github/explore/tree/master/docs>

WebXR has been seeing steady growth over the past couple of years and provides a lot of possibilities for creators and developers in terms of the content that can be made with it. Currently there are 324 public repositories using the topic.

---

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by Jonathanmarsh4** [comment]
Screenshot 2021-11-06 at 03 44 29

**Comment by hello-smile6** [comment]
> Screenshot 2021-11-06 at 03 44 29

Monterey? Nice!

**Comment by msub2** [comment]
Would appreciate someone taking a look at this. @smashwilson

**Review by nholden — CHANGES_REQUESTED** [review]
👋  Hi, @msub2! Thanks for this contribution. It looks like there's a CI failure that will need to be addressed before we merge this PR. Mind taking a look?

>   1) Failure:
topics::webxr topic#test_0022_has expected metadata in Jekyll front matter [/home/runner/work/explore/explore/test/topics_test.rb:273]:
unexpected metadata key 'created-by'.
Expected ["aliases", "created_by", "display_name", "github_url", "logo", "related", "released", "short_description", "topic", "url", "wikipedia_url"] to include "created-by".

**Review by nholden — APPROVED** [review]
Thanks for this contribution! 💖

**Pull request merged**
