### PR TITLE
Create topic 'Contentful'.

### PR DESCRIPTION
**Pull request by olegburov**
- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md

I am:
  - [x] Curating a new topic or collection

************CURATING A NEW TOPIC************

- [x] I've formatted my changes as a new folder directory, named for the topic as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

Please explain why you think this topic should be curated:

There are currently 110 public repositories (sdks/tools/extensions/examples) in Contentful organization account. Contentful SDKs for different languages are completely open source, and these guys accept PRs from the community.

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Thanks @olegburov! Can you confirm if you are affiliated with the Contentful project in any paid fashion? Thanks!

**Comment by olegburov** [comment]
@MikeMcQuaid No, I'm not. I'm just using Contentful (SaaS) for my pet projects. They provide a free pricing plan. See [here](https://www.contentful.com/pricing/) for details.

**Comment by MikeMcQuaid** [comment]
Great, thanks so much for your contribution! Without people like you submitting PRs we couldn't run this project. You rock, @olegburov!

**Comment by olegburov** [comment]
@MikeMcQuaid you're welcome!

**Pull request merged**
