### PR TITLE
Add Caronte in Made in Italy and CTF resources collections

### PR DESCRIPTION
**Pull request by Panchhh**
### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [x] Suggesting edits to an existing topic or collection
  - [ ] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---------------------------------------------------------------------

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288)
- [x] Content (and my changes are in `index.md`)

The project is great and it is developed by an Italian guy, and it makes sense to include it in the list of projects made in Italy.
It is a tool created for Capture the Flag competitions, so I have also included it in the collection of resources for CTF.

### CODE REVIEW

**Comment by krishdevdb** [comment]
@Panchhh this repo doesn't seem popular enough. As per the pulse `there was a single commit in the whole month that too by the author`. Only 3 contributors including the author. Where only the author is doing like 99% of the commits. All The Issues (7) Are Made By The Author Himself. Moreover, Majority Pull Requests Are Either Made By The Author Or Bots. The CI is also failing since 10 days. **Not a active and popular project**

**Comment by Panchhh** [comment]
Thanks @krishdevdb for the feedback. I found this tool because it was published by "The Hacker News", and it seemed quite relevant to me (https://twitter.com/TheHackersNews/status/1380198653994823681). Continuous integration doesn't seem to fail in the latest commits in the main branch. There are other users who have contributed to the project by making important changes.

**Comment by krishdevdb** [comment]
> Thanks @krishdevdb for the feedback. I found this tool because it was published by "The Hacker News", and it seemed quite relevant to me (https://twitter.com/TheHackersNews/status/1380198653994823681). Continuous integration doesn't seem to fail in the latest commits in the main branch. There are other users who have contributed to the project by making important changes.

Today's  Commits were made to fix the ci else the ci was failing. There are only 2 contributors (who at least changed some code) excluding the author. Most issues are by the author and bots. Not that of a popular to be in github explore. else curate a topic that is being used by the repo, and github will decide its popularity via **stars**

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
Thanks so much for your first contribution! Without people like you submitting PRs we couldn't run this project. You rock, @Panchhh!

**Pull request merged**
