### PR TITLE
Revert "Update index.md in collection/made-in-iran"

### PR DESCRIPTION
**Pull request by Drewski813**
### Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: <https://github.com/github/explore/blob/main/CONTRIBUTING.md>.
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [ ] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [x] Image (and my file is `*.png`, square, dimensions 288x288, size <= 75 kB)
- [x] Content (and my changes are in `index.md`)

> Please replace this line with an explanation of why you think these changes should be made.

### Curating a new topic or collection

- [ ] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [ ] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: <https://github.com/github/explore/tree/main/docs>

> Please replace this line with an explanation of why you think this topic or collection should be curated.

### Something that does not neatly fit into the binary options above

- [ ] My suggested edits are not about an existing topic or collection, or at least not a single one
- [ ] My suggested edits are not about curating a new topic or collection, or at least not a single one
- [x] My suggested edits conform to the Style Guide and API docs: https://github.com/github/explore/tree/main/docs

> Please replace this line with an explanation of your proposed changes.

---

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by moncefdhk999** [comment]
Je suis bloqué depuis le premier janvier 2022 jusqu'à maintenant beaucoup des fraudeurs tunienne qui vole mon réf et numéro bancaire et mon information personnelle la position ici en Mahdia région scandaria et jusqu'à maintenant j'ai arrêté de travailler dehors

**Comment by moncefdhk999** [comment]
Je suis heureux beaucoup c'est moi MD mondiaux

**Comment by SatoshiNakamoto-MAM** [comment]
I  am  Satoshi  nakamoto  and  i  return  to  start  finishing  the  last  all  complet  final  code.  Rules  Laws  and  correct  Regulations  nun-government interfierence.  Soon  my  system  will  run  as  it  has  always  attended  to  opperate.  I  said  anyone  can  be  part  of  meaning  getting  on  board  not  to  start  sealing  the  boat  i  am  your  captine  or  get  off the  ship.  The  creator  is  how  sets  everything  perfect.  I  created  Blockchain,  Bitcoin, BItcoin mining,  cryptofarming,  reusable green energy,  BSV,  ETH 2.0, lightting network,  BCH,  litecoin,  Dogecoin, USDT,  i  am  Bitcoin #1 ranking market  and. #1 rank Cryptocurrency  Market

**Comment by SatoshiNakamoto-MAM** [comment]
I  will  be  takeing  control  of  bitcoin bank  and  fanas  and any loans on behalf  of  Me are. All  fruad  wich  i  will. Make  all  the  scam  companys  or  some. How  providing  services  nun authorized  by  myself. Will  close  its  doors.  I  am  creating  my Bitcion infinity supply  with my  infinity money  and  the  hole all. Most  the  who. Economy  system. Willl  be  created  those  that. Will. Attached  will. Be. That. You  are. Providing. What. Your  offering  no  3rd party and  all. Data  or. Other  type of. Private  information will be  redirected to. BLOCKCHAIN PRIVATE SECURITY FIRST CHAIN  Wich its not. Called  that.  Way  for  security  reasons  so  no. One. Can  get. There  hand  on. And  its not  bad. Is. Just data  some elses  data. But. I. Protect  to. Protect  We  the  people  from  being  used
And  from  government  and. Companys  ever. Being  as. Strong. As  they  once  where they will. Fall  thats. Up. To . Each  one  of  them  this  system. Is. Going  to  change  how  the  world  moves  in. Time  98% will  approve. My  action with in 4  years after that. 100%  will. Approve  life. Will  be. Easy  but  with  challenges to  thrive helping  one. Another. Take  care. And  we made. It. This. Far. We. Sure can. Finish. It. Once and  for  all.  For all the. Peopel where ever your. From i stand with you all for We The  people.

**Pull request closed without merging**
