### PR TITLE
Added p5play, a JS game engine which has +500 stars on GitHub

### PR DESCRIPTION
**Pull request by quinton-ashley**
I added p5play right below planck.js because it uses planck.js for physics simulation.

### Please confirm this pull request meets the following requirements:

- [yes] I followed the contributing guidelines: <https://github.com/github/explore/blob/main/CONTRIBUTING.md>.
- [no] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [yes] Suggesting edits to an existing topic or collection
  - [ ] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288, size <= 75 kB)
- [yes] Content (and my changes are in `index.md`)

p5play is a notable JavaScript game engine used by many US colleges and high schools:

https://p5play.org

### CODE REVIEW

**Comment by kenyonj** [comment]
Hi,
Thanks for starting this pull request. In order to review it for acceptance, we need to make sure that all of the prerequisites are satisfied. I see that you didn't check this:

> I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee)

This is a requirement so that we can maintain a high level of independence in this project.

Thanks!

**Comment by quinton-ashley** [comment]
I don't understand, so someone else would have to add it? Could you do it for me?

**Comment by quinton-ashley** [comment]
p5play is more notable and has more GitHub stars than many other game engines on the list so I think it should be added.

**Comment by Waponfad** [comment]
I am not asking for these things to be done please don’t do them whatever they areSent from my iPhoneOn Feb 20, 2023, at 4:22 PM, OlawaleSC23 ***@***.***> wrote:﻿
#3442

**Comment by quinton-ashley** [comment]
I think the previous replies are from bots. @kenyonj could you please help?

**Comment by quinton-ashley** [comment]
What do you mean by a high level of independence? Does that mean I have to get someone unaffiliated with the project to submit this same pull request? I don't get the point of that.

I think since p5play is more popular than some of the other projects on the list that it should be included.

**Pull request closed without merging**
