### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by dlobo**
Adding glific - a two way communication platform

### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [x] Suggesting edits to an existing topic or collection
  - [ ] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

Added Glific

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288)
- [x] Content (and my changes are in `index.md`)

> Adding Glific which is primarily developed and used in India

### Curating a new topic or collection

- [ ] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [ ] My folder contains a `*.png` image (if applicable) and `index.md`
- [ ] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

> Please replace this line with an explanation of why you think this topic or collection should be curated.

### Something that does not neatly fit into the binary options above

- [ ] My suggested edits are not about an existing topic or collection, or at least not a single one
- [ ] My suggested edits are not about curating a new topic or collection, or at least not a single one
- [ ] My suggested edits conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

> Please replace this line with an explanation of your proposed changes.

---------------------------------------------------------------------

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by krishdevdb** [comment]
Thanks for contributing but I don't think that this organisation is not popular enough.

**Comment by dlobo** [comment]
I'm curious why you say its not popular enough. It is now being used more and more every day by an increasingly larger number of NGOs across India, from small to large NGOs

**Comment by krishdevdb** [comment]
But the github activity looks to be very low.

**Comment by dlobo** [comment]
You mean commits? or forks/stars?

On commits, there are commits pretty much on a continuous basis going back for the past 10 months (since we started the project)

In general, open source projects in the NGO / social sector space don't have a lot of contributions, check this report:

https://socialimpact.github.com/assets/images/GitHub_tCF_OSSInSocialSector_FINAL_updated.pdf

So using that as a measure, would be really hard for such projects

**Comment by krishdevdb** [comment]
First things first you said that `since we started the project`. But, Unfortunately as per contribution guidelines, we restrict self promotion. Thank you!

**Comment by dlobo** [comment]
No worries. thanks for engaging in this conversation. I'll close this PR

**Comment by krishdevdb** [comment]
No problem. But thanks for even trying to contribute

**Pull request closed without merging**
