### PR TITLE
Updating the Gradle logo

### PR DESCRIPTION
**Pull request by lacasseio**
I'm a Gradle engineer simply changing the logo to the new branding. I'm not changing anything else thus I don't see any conflict of interest aside from removing confusion around the brand by avoiding 2 different logos. See the main [GitHub organization](https://github.com/gradle) and [website](https://gradle.org/) of the project.

### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [ ] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [x] Suggesting edits to an existing topic or collection
  - [ ] Curating a new topic or collection

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [x] Image (and my file is `*.png`, square, dimensions 288x288)
- [ ] Content (and my changes are in `index.md`)

Gradle went through an update of their logos and I'm simply updating each one I come across.

### CODE REVIEW

**Comment by lacasseio** [comment]
@kenyonj The CI failures seems to be related to other repositories going offline/removed/became private/etc. Do you know when there will be a chance to look into the changes?

**Comment by talsafran** [comment]
@lacasseio thank you for this contribution ✨! I fixed the issues with CI 🍏, so this is good to ship too!

**Comment by lacasseio** [comment]
Hey @talsafran, thanks for merging this PR. Do you know how long does it take for the change to take effect? I'm still seeing the old logo event though it was merged 2 days ago. Thanks for the information.

**Comment by richarddd44** [comment]
Looks 3to 5

**Comment by talsafran** [comment]
@lacasseio thanks for the ping 😄. Your update should be live now! https://github.com/topics/gradle

**Pull request merged**
