### PR TITLE
Add Elixir topic

### PR DESCRIPTION
**Pull request by gmile**
- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md

I am:
 - [x] Curating a new Topic page
- [x] I've formatted my changes as a new folder directory, named for the topic as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

Elixir is a popular programming language with growing community (https://elixirforum.com/) and strong ecosystem (https://github.com/topics/elixir).

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
@gmile Thanks for the PR 💖! This was the first submitted PR 🎉 and we didn't have Travis CI when you submitted it but it's on now and is unfortunately 🔴 due to a couple of [missing Oxford commas](https://travis-ci.org/github/explore/builds/286648039#L571-L575). No rush but when you get the chance a fix for that would be great.

**Comment by TheLarkInn** [comment]
Can't tell you how happy the Oxford commas enforment makes me. Just wanted to stop by and say I love that.

**Comment by MikeMcQuaid** [comment]
> Can't tell you how happy the Oxford commas enforment makes me.

FYI I wrote the linter and I DESPISE Oxford commas (but lost that battle) so it makes me extremely sad that this is the case 😆

**Comment by gmile** [comment]
@MikeMcQuaid I've, pushed a fix with Oxford coma!

**Comment by MikeMcQuaid** [comment]
@gmile Thanks for your first contribution to github/explore! Without people like you submitting PRs we couldn't run this project. You rock!

**Comment by jeffrafter** [comment]
This topic is now live on GitHub https://github.com/topics/elixir thanks again! 🎉

**Comment by gmile** [comment]
Awesome, thank you!

**Pull request merged**
