### PR TITLE
Add Web of Things topic

### PR DESCRIPTION
**Pull request by egekorkan**
### Please confirm this pull request meets the following requirements:

- [X] I followed the contributing guidelines: <https://github.com/github/explore/blob/main/CONTRIBUTING.md>.
- [X] I am not the sole author or employee of a company who created the topic or collection I'm changing.

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [X] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---

### Curating a new topic or collection

- [X] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [X] My folder contains a `*.png` image (if applicable) and `index.md`
- [X] All required fields in my `index.md` conform to the Style Guide and API docs: <https://github.com/github/explore/tree/main/docs>

There is a growing list of Web of Things open-source projects. This topic can be used for gathering a consistent list of them while having a nice landing page.

The content has also been reviewed by @relu91, @danielpeintner, @lu-zero.

---

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by aashikkhan4345** [comment]
Any body help me

**Review by ahpook — APPROVED** [review]
Looks good, thanks for the contribution @egekorkan ! 🚀

**Comment by egekorkan** [comment]
@ahpook Thank you for merging but I do not see it deployed at https://github.com/topics/web-of-things ? I am guessing that the deployment is done separately?

**Comment by ahpook** [comment]
@egekorkan Yes, I deployed once the whole queue of PRs I was working through merged successfully. Topic is live now! Thanks for your contribution.

**Pull request merged**
