### PR TITLE
added some of @gautamkrishnar's project to list of project's made in India

### PR DESCRIPTION
**Pull request by akhilmhdh**
### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [x] Suggesting edits to an existing topic or collection
  - [ ] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---------------------------------------------------------------------

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288)
- [x] Content (and my changes are in `index.md`)

> An awesome project for made in india list

### Curating a new topic or collection

- [ ] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [ ] My folder contains a `*.png` image (if applicable) and `index.md`
- [ ] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

> Please replace this line with an explanation of why you think this topic or collection should be curated.

### Something that does not neatly fit into the binary options above

- [ ] My suggested edits are not about an existing topic or collection, or at least not a single one
- [ ] My suggested edits are not about curating a new topic or collection, or at least not a single one
- [ ] My suggested edits conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

> Please replace this line with an explanation of your proposed changes.

---------------------------------------------------------------------

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by gautamkrishnar** [comment]
👍🏻 Thanks @akhilmhdh

**Comment by mvkaran** [comment]
Thanks for your contribution @akhilmhdh. These are all nice projects! However, to be fair to other open-source maintainers as well who have multiple projects, we can only feature one of the projects. If you can add any one of them which you think would be the most valuable to the community, that'd be great.

I am sure folks would discover the rest of the projects as soon as they come across @gautamkrishnar :)

**Comment by akhilmhdh** [comment]
@mvkaran Sorry for the delay in my reply. Yes totally agreed and I have also updated list to one of my fav of his recent project.

**Comment by mvkaran** [comment]
Thanks @akhilmhdh. Can you please merge the updated main branch?

**Comment by akhilmhdh** [comment]
@mvkaran has synced with all the new changes to that collection of master

**Review by mvkaran — APPROVED** [review]

**Comment by mvkaran** [comment]
Thanks, @akhilmhdh!

**Pull request merged**
