### PR TITLE
Add an iris topic

### PR DESCRIPTION
**Pull request by kataras**
- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [x] Curating a new topic or collection
- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

Please explain why you think this Topic page should be curated:

- the iris topic has 258 repos in it
- kataras/iris has 18.6k ⭐️s

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
> * the iris topic has 258 repos in it

They don't all seem to refer to this project?



> * [x]  I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md

> Avoid conflicts of interest. Maintainers of a project cannot add a topic or collection for their own project. If a topic is popular enough to warrant inclusion, someone else will add or improve it.

**Comment by kataras** [comment]
Hello @MikeMcQuaid,  none of the topics registered are all referring to the same project, this is logical, take for example the [Atom topic](https://github.com/github/explore/blob/master/topics/atom/index.md), it contains hundreds of packages that are not referring to the atom editor project. However, the current [iris topic](https://github.com/topics/iris) shows the Iris web framework project already. I just want to make it easier for users that are searching this topic, edit the image and the description.

**Comment by kataras** [comment]
Hello @MikeMcQuaid,  none of the topics registered are all referring to the same project, this is logical, take for example the [Atom topic](https://github.com/github/explore/blob/master/topics/atom/index.md), it contains hundreds of packages that are not referring to the atom editor project. However, the current [iris topic](https://github.com/topics/iris) shows the Iris web framework project and its relative projects already, the majority of those are community-based extensions for the framework. I just want to make it easier for users that are searching this topic, edit the image and the description.

**Comment by kataras** [comment]
However, if you think that it contains a conflict because I am the top maintainer. You can close this PR, maybe a GitHub staff can add this instead? It's quite popular and it's sad that it's not part of this repository.

**Comment by mekmin100** [comment]
evet yazmak sanırım işe yarar ve böyle aramak dahamı anlamlı bilmem ama github görsel ve sanal görüntülere yeni bir yer tutmalı çünkü çok kafam karışıyo sadece ilişkilendirmelerle yön almaya çalışıyom alt taban bazen üst tabana yetmiyo yada takip gerekiyo ama hala kopuk arayışlarım

**Comment by robertocr** [comment]
Agreeing.

**Comment by speedwheel** [comment]
I am willing to open a PR for Iris.

**Comment by MikeMcQuaid** [comment]
> However, if you think that it contains a conflict because I am the top maintainer.

Yep, sorry, this is part our contribution guidelines.

**Comment by kataras** [comment]
No worries @MikeMcQuaid, I see that @speedwheel did it and I thank him a lot! Do you know when will be available on topics/iris page?

Rel: https://github.com/github/explore/pull/1685

**Comment by MikeMcQuaid** [comment]
> Do you know when will be available on topics/iris page?

It's there now.

**Pull request closed without merging**
