### PR TITLE
Add LMPHP...

### PR DESCRIPTION
**Pull request by BaseMax**
- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [ ] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection

---------------------------------------------------------------------

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288)
- [x] Content (and my changes are in `index.md`)

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [ ] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

### CODE REVIEW

**Comment by kenyonj** [comment]
Hi @BaseMax  ,
Thanks for starting this pull request. In order to review it for acceptance, we need to make sure that all of the prerequisites are satisfied. I see that you didn't check this:

> I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee)

This is a requirement so that we can maintain a high level of independence in this project. Please update if you are able to verify that you meet that requirement.

Thanks!

**Comment by BaseMax** [comment]
Hi Justin Kenyon @kenyonj,

I has been check that and submit a edit.

Best Regards,
Max.

**Comment by kenyonj** [comment]
Unfortunately, since you are the creator of the project this precludes you from submitting a new topic entry.

**Comment by loribarber** [comment]
🤐

**Comment by BaseMax** [comment]
OK,

I did not know it.
I hope one person who has use this library will submit it.

Best Regards,
Max.

**Pull request closed without merging**
