### PR TITLE
Add v86 article

### PR DESCRIPTION
**Pull request by hello-smile6**
### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [X] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [X] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---------------------------------------------------------------------

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288)
- [ ] Content (and my changes are in `index.md`)

> Please replace this line with an explanation of why you think these changes should be made.

### Curating a new topic or collection

- [X] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [X] My folder contains a `*.png` image (if applicable) and `index.md`
- [X] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

> v86 deserves attention.

### Something that does not neatly fit into the binary options above

- [ ] My suggested edits are not about an existing topic or collection, or at least not a single one
- [ ] My suggested edits are not about curating a new topic or collection, or at least not a single one
- [ ] My suggested edits conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

> Please replace this line with an explanation of your proposed changes.

---------------------------------------------------------------------

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by hello-smile6** [comment]
Sorry if I messed up, feel free to fix it.

**Comment by deniseyu** [comment]
hi @hello-smile6, could you please add some more details to this topic?

Here's an example of the format that we'd like to see: https://raw.githubusercontent.com/github/explore/main/topics/advent-of-code/index.md

**Review by deniseyu — CHANGES_REQUESTED** [review]
We'd like to see more detail about a new topic - please have a look at existing topics and try to copy the existing structure of those pages!

**Review by devkadirselcuk — APPROVED** [review]

**Review by devkadirselcuk — APPROVED** [review]

**Comment by kenyonj** [comment]
@devkadirselcuk, thanks again for the contribution. However, it can not be accepted as is. Please take a look at the level of detail in the other topics that are present in this repository and reopen another PR following them as a guideline.
Thanks!

**Review by BrittBratt5711 — COMMENTED** [review]
Thanks

**Pull request closed without merging**
