### PR TITLE
add opentelemetry topic

### PR DESCRIPTION
**Pull request by andrewhsu**
### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---------------------------------------------------------------------

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288)
- [ ] Content (and my changes are in `index.md`)

> Please replace this line with an explanation of why you think these changes should be made.

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

OpenTelemetry provides a single set of APIs, libraries, agents, and collector services to capture distributed traces and metrics from your application. You can analyze them using Prometheus, Jaeger, and other observability tools.

### Something that does not neatly fit into the binary options above

- [ ] My suggested edits are not about an existing topic or collection, or at least not a single one
- [ ] My suggested edits are not about curating a new topic or collection, or at least not a single one
- [ ] My suggested edits conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

> Please replace this line with an explanation of your proposed changes.

---------------------------------------------------------------------

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by andrewhsu** [comment]
I fixed a typo in git commit c39f005 in the `github_url` field. I've force-pushed new commit `299010f` and should be good to go now.

**Comment by iancanderson** [comment]
Hi @andrewhsu thanks for the contribution ❤️. Unfortunately, as per our [contribution guidelines](https://github.com/github/explore/blob/master/CONTRIBUTING.md#guidelines), we don't allow self promotion if you are a maintainer of the project:

> Maintainers of a project cannot add a topic or collection for their own project. If a topic is popular enough to warrant inclusion, someone else will add or improve it.

We do this so that project get curated if there is enough support/activity in the community. Thank you!

**Comment by andrewhsu** [comment]
@iancanderson although I contributed a few PRs to the opentelemetry community to satisfy the requirements to be accepted as a [member](https://github.com/open-telemetry/community/blob/4e5035031c773df5b4a9317f10695b8eafba6cf4/community-membership.md#member) of the github org [opentelemtry](https://github.com/orgs/open-telemetry/people), I am not a maintainer of any of the projects in that org: https://github.com/open-telemetry/community/blob/4e5035031c773df5b4a9317f10695b8eafba6cf4/community-members.md

Could this PR be reconsidered for re-opening?

**Comment by Boyloy2272** [comment]
7

**Review by antn — APPROVED** [review]

**Pull request merged**
