### PR TITLE
Add the Unigine topic

### PR DESCRIPTION
**Pull request by nxrighthere**
### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection

---------------------------------------------------------------------

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

Unigine is a popular game engine that recently [got the Community edition](https://www.youtube.com/watch?v=3Q2dAh_cmFk) with the support of C# and C++ languages for enthusiasts across the globe.

---------------------------------------------------------------------

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by nxrighthere** [comment]
Should be okay now.

**Comment by kenyonj** [comment]
Hi,
Thanks for your contribution. However, curated topics are meant to be used for heavily used topics and this topic is only used on 7 public repositories.

**Comment by kenyonj** [comment]
I re-read our contribution guidelines and think this falls into the second criteria from this sentence, so I am reopening this.

>Valuable topics, for example, include those that are already widely used by repositories, or a topic that currently lacks important information.

**Comment by kenyonj** [comment]
Can you merge master into your branch and update, once that's done we can get this merged in.

**Comment by nxrighthere** [comment]
@kenyonj Done.

> However, curated topics are meant to be used for heavily used topics and this topic is only used on 7 public repositories.

Only tagged - yes, but non-tagged repositories, source code, and data are scattered across GitHub, [see](https://github.com/search?q=unigine&type=Code). The problem is that people are rarely tagging their repositories themselves.

**Pull request merged**
