### PR TITLE
Adding public repo from the Colorado Digital Service

### PR DESCRIPTION
**Pull request by parkmichelle**
Submitting my team's work in Colorado on CO Exposure Notifications metrics, I was recommended to submit a pull request by the Github team at Code for America.

### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [x] Suggesting edits to an existing topic or collection
  - [ ] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---------------------------------------------------------------------

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288)
- [x] Content (and my changes are in `index.md`)

I was recommended to submit a pull request for our project here by the Github team at Code for America.

### Curating a new topic or collection

- [ ] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [ ] My folder contains a `*.png` image (if applicable) and `index.md`
- [ ] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

> Please replace this line with an explanation of why you think this topic or collection should be curated.

### Something that does not neatly fit into the binary options above

- [ ] My suggested edits are not about an existing topic or collection, or at least not a single one
- [ ] My suggested edits are not about curating a new topic or collection, or at least not a single one
- [ ] My suggested edits conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

> Please replace this line with an explanation of your proposed changes.

---------------------------------------------------------------------

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by parkmichelle** [comment]
Hi there, can I check in on this? I was a PM at the Colorado Digital Service, and I wasn't sure if "affiliation with the project I am suggesting" was referring to this collection or the repository I'm looking to add.

**Review by deniseyu — APPROVED** [review]
Hi @parkmichelle, thanks for the contribution and apologies for the delay! Affiliation is no problem, thanks for your work on this valuable project!

**Comment by Hawkmike** [comment]
What's up

**Review by devkadirselcuk — APPROVED** [review]

**Comment by kenyonj** [comment]
Hi @parkmichelle, just wanted to ping again regarding @deniseyu 's comment here: https://github.com/github/explore/pull/2345#pullrequestreview-673331942

**Comment by parkmichelle** [comment]
@deniseyu @kenyonj I don't see the "update branch" button. It says "This pull request can be automatically merged by project collaborators. Only those with write access to this repository can merge pull requests" with no button next to it. Should I be looking elsewhere?

**Comment by kenyonj** [comment]
Do you see a “fetch upstream” button on your repository fork? That should do the trick as well. image

**Review by Yodag7354 — APPROVED** [review]
parkmichelle:patch-1

**Review by kenyonj — APPROVED** [review]
💯 🍨 Thank you for your contribution! I'll merge this in as soon as CI is 🍏

**Comment by hhoopes** [comment]
Hi! I'm Michelle's teammate, following up for her since she has left our team. I noticed her merge never got built because of the failing tests, at least per this build job: https://github.com/github/explore/runs/2720622622

It's not critical at all, but when you get a chance, I'm sure she'd love it if you reran the job. Thank you so much for supporting govtech & open source!

**Pull request merged**
