### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by elonmusk-droid**
### Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: <https://github.com/github/explore/blob/master/CONTRIBUTING.md>.
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [x] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [x] Something that does not neatly fit into the binary options above

---

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [x] Image (and my file is `*.png`, square, dimensions 288x288, size <= 75 kB)
- [x] Content (and my changes are in `index.md`)

> Please replace this line with an explanation of why you think these changes should be made.

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: <https://github.com/github/explore/tree/master/docs>

> Please replace this line with an explanation of why you think this topic or collection should be curated.

### Something that does not neatly fit into the binary options above

- [x] My suggested edits are not about an existing topic or collection, or at least not a single one
- [x] My suggested edits are not about curating a new topic or collection, or at least not a single one
- [x] My suggested edits conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

> Please replace this line with an explanation of your proposed changes.

---

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by akieu222** [comment]
Axrx

**Comment by elonmusk-droid** [comment]
Good

**Comment by Luois45** [comment]
You aren't supposed to check all checkboxes, as well as not providing any explanation why you do want the changes.

**Comment by AristodamusAdairs** [comment]
Bruh, you kidding us.

**Comment by AristodamusAdairs** [comment]
Also your contribution is worse. You just added a space in a link, are you really a...hu...man

**Comment by Luois45** [comment]
@AristodamusAdairs
Why are you so offended by me just trying to help you?
I do not agree on that that my contribution is worse, but it's just my personal opinion.

**Comment by AristodamusAdairs** [comment]
Bruh, I am talking about Elon musk

**Comment by Luois45** [comment]
@AristodamusAdairs 
Okay. I'm sorry for not understanding.

**Comment by AristodamusAdairs** [comment]
@Luois45 Never mind, look at his contribution.

**Comment by AristodamusAdairs** [comment]
> Also your contribution is worse. You just added a space in a link, are you really a...hu...man

I was talking on his change in MD file

**Comment by Luois45** [comment]
@AristodamusAdairs I've looked already at it, but it doesn't seem like an even serious meant one because of the first PR message.

**Comment by AristodamusAdairs** [comment]
@Luois45 The billionaire is kidding us 😂

**Pull request closed without merging**
