### PR TITLE
[Tests] Check created_by length

### PR DESCRIPTION
**Pull request by ipc103**
### Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: <https://github.com/github/explore/blob/main/CONTRIBUTING.md>.
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [ ] Curating a new topic or collection
  - [x] Something that does not neatly fit into the binary options above

---

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288, size <= 75 kB)
- [ ] Content (and my changes are in `index.md`)

> Please replace this line with an explanation of why you think these changes should be made.

### Curating a new topic or collection

- [ ] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [ ] My folder contains a `*.png` image (if applicable) and `index.md`
- [ ] All required fields in my `index.md` conform to the Style Guide and API docs: <https://github.com/github/explore/tree/main/docs>

> Please replace this line with an explanation of why you think this topic or collection should be curated.

### Something that does not neatly fit into the binary options above

- [x] My suggested edits are not about an existing topic or collection, or at least not a single one
- [x] My suggested edits are not about curating a new topic or collection, or at least not a single one
- [x] My suggested edits conform to the Style Guide and API docs: https://github.com/github/explore/tree/main/docs

The import requires 100 characters or less. I basically copied this test from the display_name test above.

---

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by ipc103** [comment]
👍 This failed as expected for the [bigquery](https://github.com/github/explore/blob/main/topics/bigquery/index.md) topic: https://github.com/github/explore/actions/runs/5026263844/jobs/9014326665?pr=3732

FYI @isis-santos-costa as the creator of this topic, is there another way credit this group of folks for the `created_by` field that would fit in less than 100 characters? If not, we'll need to remove this column as we can't support 115 chars at the moment.

**Comment by drgoedelman** [comment]
Comment0

**Comment by drgoedelman** [comment]
Write0

**Review by ahpook — APPROVED** [review]
Assuming this created_by was the only long one, I'll merge this - bigquery can re-add a shorter field in a different commit.

**Pull request merged**
