### PR TITLE
Add "mswjs" topic

### PR DESCRIPTION
**Pull request by kettanaito**
### Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: <https://github.com/github/explore/blob/master/CONTRIBUTING.md>.
- [ ] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: <https://github.com/github/explore/tree/master/docs>

> Mock Service Worker is a popular API mocking library in JavaScript ecosystem (~9k GitHub stars, ~1M weekly downloads on [npm](https://www.npmjs.com/package/msw), used by Google, Microsoft, Spotify, and countless others). I'd like for GitHub to have an official topic page for it. 

---

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by kettanaito** [comment]
Hey. 

I've got a question regarding this line:

> I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

I _am_ affiliated with the project as I'm its creator. Does it mean I cannot create a topic for a widely used project because of that?

**Review by Procorners — COMMENTED** [review]
Oky

**Comment by octokatherine** [comment]
> Hey.
> 
> I've got a question regarding this line:
> 
> I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).
> 
> I am affiliated with the project as I'm its creator. Does it mean I cannot create a topic for a widely used project because of that?

Hi @kettanaito 👋  Unfortunately yes, as per our contribution guidelines, we don't allow self promotion if you are a maintainer of the project:

Maintainers of a project cannot add a topic or collection for their own project. If a topic is popular enough to warrant inclusion, someone else will add or improve it.

We do this so that project get curated if there is enough support/activity in the community. Thank you!

**Comment by kettanaito** [comment]
Hey, @octokatherine. That's completely understandable. Thank you for your response!

**Pull request closed without merging**
