### PR TITLE
Adding Rivalis as a new topic and item inside "software development tools" collection

### PR DESCRIPTION
**Pull request by jnajdovski**
### Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: <https://github.com/github/explore/blob/master/CONTRIBUTING.md>.
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [x] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288, size <= 75 kB)
- [x] Content (and my changes are in `index.md`)

> Please replace this line with an explanation of why you think these changes should be made.

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: <https://github.com/github/explore/tree/master/docs>

> Please replace this line with an explanation of why you think this topic or collection should be curated.

### Something that does not neatly fit into the binary options above

- [ ] My suggested edits are not about an existing topic or collection, or at least not a single one
- [ ] My suggested edits are not about curating a new topic or collection, or at least not a single one
- [x] My suggested edits conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

> Please replace this line with an explanation of your proposed changes.

---

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by nholden** [comment]
👋  Hi, @jnajdovski! Thanks for this contribution.

I noticed that the `topics/rivalis/index.md` file is blank. Is that intended? Since [only 4 repositories](https://github.com/topics/rivalis) use the `rivalis` topic, I'm not sure it would be super useful to add at this time. Happy to keep the change to the collection in place and merge, if that works for you!

**Comment by jnajdovski** [comment]
Hi, my mistake i forgot to push the content of the file

**Comment by nholden** [comment]
Looks like there's a CI failure to address. 👀 

>   1) Failure:
topics::rivalis topic#test_0011_has valid aliases [/home/runner/work/explore/explore/test/topics_test.rb:132]:
'rivalis.io' must be between 1-35 characters, start with a letter or number, include only lowercase letters, and may include hyphens

**Comment by jnajdovski** [comment]
@nholden the problem with the alias is fixed

**Comment by nholden** [comment]
👋  Hey, @jnajdovski! Looks like there's still a failing test:

>   1) Failure:
topics::rivalis topic#test_0011_has valid aliases [/home/runner/work/explore/explore/test/topics_test.rb:133]:
alias 'rivalis' must not be the same as the topic.
Expected "rivalis" to not be equal to "rivalis".

**Review by Hadwanvelasco — COMMENTED** [review]
nice work

**Pull request closed without merging**
