### PR TITLE
Add Stimulus topic

### PR DESCRIPTION
**Pull request by marcoroth**
### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

The popularity about lightweight JavaScript Frameworks has increased again in the last few years. Stimulus is really popular in Server-side rendered Web-Applications as it sprinkles JavaScript to add behavior to your HTML. Stimulus became an even more important topic with StimulusReflex and Hotwire/Turbo gaining popularity in the Rails world.

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by krishdevdb** [comment]
Hi @marcoroth do you mean [hopsoft/stimulus_reflex](https://github.com/hopsoft/stimulus_reflex) by stimulus?? And other repositories being plugins or extensions for that?

If Yes, Thank you for contributing. You seem to be a maintainer or collaborator or maybe some other Affiliation as per the  contributors insights (You have most commits after the author). Unfortunately as per contribution guidelines, we restrict self promotion. Thank you!

**Comment by marcoroth** [comment]
Hey @krishdevdb, no I meant [`hotwired/stimulus`](https://github.com/hotwired/stimulus). It's the other way around. StimulusReflex is a plugin/extension of Stimulus if you will, but StimulusReflex is not affiliated with Stimulus. I have no affiliation with Stimulus.

**Comment by krishdevdb** [comment]
Ok, Then Your PR looks good to me. But I would like other people's thoughts

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
Thanks so much for your first contribution! Without people like you submitting PRs we couldn't run this project. You rock, @marcoroth!

**Pull request merged**
