### PR TITLE
Added new missing Google Cloud Platform.png in /explore/topics

### PR DESCRIPTION
**Pull request by DarinJoshua-dev**
Please check me PR and do as needful, thank you, proud to contribute to GitHub

### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [x] Suggesting edits to an existing topic or collection

---------------------------------------------------------------------

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [x] Image (and my file is `*.png`, square, dimensions 288x288)
- [x] Content (and my changes are in `index.md`)

> Have added the missing Google Cloud Platform image as png and have made changes accordingly to its index.md. This will now make the logo of Google Cloud Platform accessible.

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by DarinJoshua-dev** [comment]
Please check my PR and do the needful, proud to contribute, thank you

**Comment by DarinJoshua-dev** [comment]
Hello, can someone help me out with this build fail, I seem to have done it right, thank you

**Comment by Gargaj** [comment]
> Hello, can someone help me out with this build fail. Don't know why I am getting the fail in the test, I seem to have done it right, thank you

https://github.com/github/explore/blob/master/topics/google-cloud/index.md needs to contain `logo: google-cloud.png`

**Comment by DarinJoshua-dev** [comment]
Thanks much for your help!

**Comment by DarinJoshua-dev** [comment]
Have passed all the checks, please do needful for my PR. Thank you

**Review by paulcsmith — APPROVED** [review]
Thank you for your contribution!

**Comment by DarinJoshua-dev** [comment]
Thank you, proud to contribute!

**Pull request merged**
