### PR TITLE
[suggestion] reaggrange list in programming-languages by stars

### PR DESCRIPTION
**Pull request by MaxGraey**
- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [ ] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [x] Suggesting edits to an existing topic or collection
  - [ ] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---------------------------------------------------------------------

- [x] My suggested edits are not about curating a new topic or collection, or at least not a single one

### CODE REVIEW

**Comment by krishdevdb** [comment]
Thanks For Contributing @MaxGraey. But I think there must be a reason to sort them upon stars. **Because people get fake stars pretty easily.**

Here are some **resources** I read before this comment and I think might be useful for you to understand:

- [A **Stack Exchange** Question](https://opensource.stackexchange.com/questions/5110/github-stars-is-a-very-useful-metric-but-for-what)
- [A Article By **Traefik Labs**](https://traefik.io/blog/can-we-trust-github-stars-e8aa8b6b0baa/)
- [A **Dev.to** Article](https://dev.to/robertcoopercode/should-the-quality-of-github-projects-be-evaluated-by-their-starcount-dp5)

Plus, I don't think that sorting will make any difference in the programming languages

**Comment by MaxGraey** [comment]
I agree that this is not the best metric. Perhaps it is worth considering some weighted average of the number of stars, the number of forks and the number of questions on stackoveflow, for example. But for this you have to write a whole script. Another option is just leave as is.

**Comment by krishdevdb** [comment]
@MaxGraey If You Are Working All The Metrics Then It Is Perfect.

**Review by krishdevdb — APPROVED** [review]

**Comment by MaxGraey** [comment]
> @MaxGraey If You Are Working All The Metrics

Not yet, but I could try write such script and share it and retrieved results. Just give me some time)

**Comment by mvkaran** [comment]
👋🏼  @leereilly - I'd love to know your thoughts on this :)

**Comment by BlakeWilliams** [comment]
👋 I like the idea of sorting by stars, but I think keeping the list sorted as star counts change will be a difficult and time consuming task.

**Comment by MaxGraey** [comment]
I'm wonking on script which take into account stars, forks and probably other metrics like count of stackoveflow questions (but not sure about this)

**Comment by MaxGraey** [comment]
Alright, here:
https://gist.github.com/MaxGraey/e80843bf15e9eacc4f2881126b590648

node.js script which requests `explore/collections/programming_languages/index.md` extract repos and sort them by simple weighted geometric mean score computed from number of stars, subscribers and forks. Afterwards generate new index.md page with properly sorted names.

Unfortunately I reached rate limit for GItHub's API and can't retrieve results yet 🤦

**Review by krishdevdb — APPROVED** [review]
It looks perfect to me. I would like to know other people(@gallexi @smashwilson @mvkaran )'s thoughts on this. Thanks for contributing.

**Comment by kenyonj** [comment]
We don't currently have sorting capabilities on these collections, so we're sticking to sorting by added date. If this changes we'll update the docs here.

**Pull request closed without merging**
