### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by Lucretia**
Add Ada 2012 binding to SDL2.

### Please confirm this pull request meets the following requirements:

- [X] I followed the contributing guidelines: <https://github.com/github/explore/blob/master/CONTRIBUTING.md>.
- [ ] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [X] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288, size <= 75 kB)
- [X] Content (and my changes are in `index.md`)

Addition of a new "Game Engine" (if love can be in so can sdl.) to the list, to diversify the languages used.

### Curating a new topic or collection

- [ ] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [ ] My folder contains a `*.png` image (if applicable) and `index.md`
- [ ] All required fields in my `index.md` conform to the Style Guide and API docs: <https://github.com/github/explore/tree/master/docs>

N/A

### Something that does not neatly fit into the binary options above

- [ ] My suggested edits are not about an existing topic or collection, or at least not a single one
- [X] My suggested edits are not about curating a new topic or collection, or at least not a single one
- [X] My suggested edits conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

N/A

---

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by lashonnee** [comment]
Pull request

**Comment by Lucretia** [comment]
> wave Hi, @Lucretia! Thanks for this contribution.
> 
> Is `Lucretia/sdlada` a game engine? The description for this collection is "frameworks for building games across multiple platforms." It's hard for me to tell from [the README](https://github.com/Lucretia/sdlada/blob/master/README.md) how this library provides a framework for building a game.

It's a language binding to SDL2, SDL2 is equivalent to Love, in fact more so.

**Comment by nholden** [comment]
> It's a language binding to SDL2, SDL2 is equivalent to Love, in fact more so. SDL is a portable games development library, Ada makes SDL2 even more portable.

Thanks for the explanation!

It feels like SDL itself might be an appropriate addition to this collection, but I don't see a GitHub repo. I'm a little worried this collection could become less useful if we began adding all the language bindings for each game engine.

I see that the `sdl` topic seems to be pretty popular. Instead of adding the language binding here, I wonder if it could be useful to improve the [topic page](https://github.com/topics/sdl) to bring some more visibility to the ecosystem.

**Comment by kenyonj** [comment]
Hi,
Thanks for starting this pull request. In order to review it for acceptance, we need to make sure that all of the prerequisites are satisfied. I see that you didn't check this:

> I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee)

This is a requirement so that we can maintain a high level of independence in this project.

Thanks!

p.s. I think @nholden suggestions are great to follow for expanding on the `sdl` topic. That seems like it would be a valuable addition.

**Comment by Lucretia** [comment]
Well, SDLAda is my project. That requirement is really quite idiotic.

**Pull request closed without merging**
