### PR TITLE
Create Netfree topic

### PR DESCRIPTION
**Pull request by zvizvi**
### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---------------------------------------------------------------------

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

---------------------------------------------------------------------

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by Oneill38** [comment]
@zvizvi looks like you have some test failures

**Comment by zvizvi** [comment]
I fixed it. (i hope so...)

**Comment by Oneill38** [comment]
I think if you merge main in this should be green again

**Comment by opticalpalace080** [comment]
My cash had stuck I have mandate link how to take my cash

**Comment by deniseyu** [comment]
hey @zvizvi, thanks for this contribution!

In order for these pages to build correctly, you will need to provide a short description underneath the final set of `---` in this file.

[Here's an example](https://raw.githubusercontent.com/github/explore/main/topics/activitypub/index.md) of a working file to give you an idea of what its shape should look like!

**Comment by zvizvi** [comment]
> hey @zvizvi, thanks for this contribution!
> 
> In order for these pages to build correctly, you will need to provide a short description in the frontmatter.
> 
> [Here's an example](https://raw.githubusercontent.com/github/explore/main/topics/activitypub/index.md) of a working file to give you an idea of what its shape should look like!

Done

**Comment by zvizvi** [comment]
> hey @zvizvi, thanks for this contribution!
> 
> In order for these pages to build correctly, you will need to provide a short description in the frontmatter.
> 
> [Here's an example](https://raw.githubusercontent.com/github/explore/main/topics/activitypub/index.md) of a working file to give you an idea of what its shape should look like!

Done.

**Pull request merged**
