### PR TITLE
Add mswjs topic

### PR DESCRIPTION
**Pull request by Aprillion**
### Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: <https://github.com/github/explore/blob/main/CONTRIBUTING.md>.
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: <https://github.com/github/explore/tree/main/docs>

> MSW is a very useful library for development and testing of many JS/TS projects with almost 1M weekly downloads on [npm](https://www.npmjs.com/package/msw), using a more robust mechanism compared to previous approaches (it's intercepting native network requests instead of mocking `fetch`), embracing web standards and promoting better development practices, deserving a prominent place on GitHub.

---

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by kenyonj** [comment]
Thank you for the PR, however, according to our [contribution guidelines](https://github.com/github/explore/blob/main/CONTRIBUTING.md):

> We are likely to consider suggestions to curate a topic or collection that is valuable to GitHub's community. Valuable topics, for example, include those that are already [widely used by repositories](https://help.github.com/articles/classifying-your-repository-with-topics/) and could benefit from the addition of important information. When suggesting content, please consider how to make your contribution broadly useful and relevant to others, rather than serving a specific use case.

This topic is only used on 20 repositories, therefore it does not qualify as "widely used".

**Comment by kenyonj** [comment]
Perhaps you could lobby for those projects to add the topic to their repository? Typically topics have 100s of repositories using the topic name.

I encourage you to circle back with us if the topic adoption goes well and we can revisit adding `mswjs` to the curated list.

Thanks!

**Comment by Aprillion** [comment]
the contribution guidelines say `for example, include those that are already widely used` and the link points to https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics that does not mention anything about what is the acceptable limit

you somehow treat that vague statement as a qualification criteria, but I am very confused as to what is the actual qualification criteria

please don't encourage me when you don't mean it - I tried to help a project I love and you ruined my day by having your stupid secret criteria, I would suggest to write your criteria directly to the contribution guidelines so that other participants have better information before you ruin their excitement too

good luck with all the good activities GitHub is doing and I hope `topics` will become a more pleasant experience for other people in the future

**Comment by MikeMcQuaid** [comment]
> you somehow treat that vague statement as a qualification criteria, but I am very confused as to what is the actual qualification criteria

@Aprillion We do not have a specific number and, even if we did, we would be unlikely to publish it to discourage gaming.

> please don't encourage me when you don't mean it - I tried to help a project I love and you ruined my day by having your stupid secret criteria, I would suggest to write your criteria directly to the contribution guidelines so that other participants have better information before you ruin their excitement too

We do mean it. I'm sorry that this has not been the outcome you were wanting or expecting.

In future please adjust your language here, "stupid secret criteria" does not match the respectful tone that @kenyonj has used in this PR.

> good luck with all the good activities GitHub is doing and I hope `topics` will become a more pleasant experience for other people in the future

Thanks for the kind words!

**Pull request closed without merging**
