### PR TITLE
Add topic "PSR-4"

### PR DESCRIPTION
**Pull request by shaedrich**
### Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: <https://github.com/github/explore/blob/main/CONTRIBUTING.md>.
- [x] I am not the sole author or employee of a company who created the topic or collection I'm changing.

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288, size <= 75 kB)
- [ ] Content (and my changes are in `index.md`)

> Please replace this line with an explanation of why you think these changes should be made.

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [ ] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: <https://github.com/github/explore/tree/main/docs>

PSRs are a widely used standard for the PHP community.

### Something that does not neatly fit into the binary options above

- [x] My suggested edits are not about an existing topic or collection, or at least not a single one
- [ ] My suggested edits are not about curating a new topic or collection, or at least not a single one
- [x] My suggested edits conform to the Style Guide and API docs: https://github.com/github/explore/tree/main/docs

> Please replace this line with an explanation of your proposed changes.

---

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Review by ahpook — COMMENTED** [review]
Same question as #3879 , are these really curation-worthy topics?

**Comment by shaedrich** [comment]
> Same question as #3879 , are these really curation-worthy topics?

Well, it is used in 162 repositories&mdash;that's not an awful lot but not nothing. The rule of thumb from the docs just says:

> We are likely to consider suggestions to curate a topic or collection that is valuable to GitHub's community. Valuable topics, for example, include those that are already [widely used by repositories](https://help.github.com/articles/classifying-your-repository-with-topics/) and could benefit from the addition of important information. When suggesting content, please consider how to make your contribution broadly useful and relevant to others, rather than serving a specific use case.

After all, PSR is a central topic to PHP developers. However, if one doesn't happen to be a PHP developer, that topic is&mdash;unsurprisingly&mdash;everything but relevant to them. I curated the topics because I already curated other PSR topics and did so for the sake of consistency but refrained from curating PSR topics below three digit repository amounts.

**Comment by shaedrich** [comment]
By the way: What do you consider a "sufficiently valuable/curation-worthy" topics in terms of repository count?

Aside from this PR, I would like to add this number (preferably a lower and upper bound) to my tool: https://shaedrich.gitlab.io/github-uncurated-topics/user-topics.html

**Comment by ahpook** [comment]
This is just my opinion, but I like to see more than 1000 repos in the topic. At 500 I feel it's questionable but will probably merge if it is a good PR; under 300 is quite a small niche.

**Review by ahpook — APPROVED** [review]
I'll merge this, despite my doubts

**Comment by shaedrich** [comment]
Thanks, I didn't want to make you do anything you doubted. I didn't know, what exactly was the right number&mdash;so thanks for clarifying that! I'll keep that in mind for next time.

**Pull request merged**
