### PR TITLE
Add Solana topic

### PR DESCRIPTION
**Pull request by MarkBennett**
### Please confirm this pull request meets the following requirements:

- [X] I followed the contributing guidelines: <https://github.com/github/explore/blob/master/CONTRIBUTING.md>.
- [X] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [X] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---
### Curating a new topic or collection

- [X] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [X] My folder contains a `*.png` image (if applicable) and `index.md`
- [X] All required fields in my `index.md` conform to the Style Guide and API docs: <https://github.com/github/explore/tree/master/docs>

Solana is a popular blockchain and there are a growing number of repositiries using it. As someone new to Solana it can be confusing to understand, and I thought this topic would make it more accessible to other newbies.

### CODE REVIEW

**Comment by MarkBennett** [comment]
Please let me know if there are any issues, or things you'd like changed. Thanks for making this accessible to support by the community!

**Review by nholden — APPROVED** [review]
Thanks for this contribution! 💖

**Comment by nholden** [comment]
👋  Hi, @MarkBennett! Looks like there's an error in CI. Could you address it so that we can merge this PR?

>   1) Failure:
topics::solana topic#test_0019_has at most one image with the right name, type, and dimensions [/home/runner/work/explore/explore/test/topics_test.rb:229]:
topic images should be 288px wide.

**Comment by MarkBennett** [comment]
> 👋  Hi, @MarkBennett! Looks like there's an error in CI. Could you address it so that we can merge this PR?
> 
> >   1) Failure:
> topics::solana topic#test_0019_has at most one image with the right name, type, and dimensions [/home/runner/work/explore/explore/test/topics_test.rb:229]:
> topic images should be 288px wide.

Looks like it's just the image dimensions. Out with family today but will push an update tomorrow.

**Comment by SilBit-418** [comment]
Misunderstanding on my end.

Alexa Baird
University Of Advancing Technology
Bachelor in Computer Science
5593772064
***@***.***

________________________________

**Comment by MarkBennett** [comment]
Image size updated to 288px @nholden

**Comment by MarkBennett** [comment]
Branch updated from master as well.

**Comment by beheratapasTRB3** [comment]
gh pr checkout 2766
TapasRanjanBehera

**Pull request merged**
