### PR TITLE
github_url for Duckduckgo

### PR DESCRIPTION
**Pull request by theel0ja**
### Thank you for contributing! Please confirm the following:

- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [x] Suggesting edits to an existing topic or collection
  - [ ] Curating a new topic or collection
  
---------------------------------------------------------------------

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288)
- [x] Content (and my changes are in `index.md`)

Please explain why these changes are necessary:

### CODE REVIEW

**Comment by chitphyopaing** [comment]
https://github.com/github/explore/blob/master/collections/government/index.md

**Comment by Londonclog** [comment]
Fix http://github.com/_url for DuckDuckGo

**Comment by talsafran** [comment]
🚢 

Thanks @theel0ja!

**Comment by talsafran** [comment]
The [topic](https://github.com/topics/duckduckgo) is updated with your changes 🎉 , thanks!

**Pull request merged**
