### PR TITLE
Add topic: whistleblowing

### PR DESCRIPTION
**Pull request by evilaliv3**
### Please confirm this pull request meets the following requirements:

- [X] I followed the contributing guidelines: <https://github.com/github/explore/blob/main/CONTRIBUTING.md>.
- [X] I am not the sole author or employee of a company who created either the topic I am modifying/adding or the collection entry I am modifying/adding.

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [X] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---

### Curating a new topic or collection

- [X] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [X] My folder contains a `*.png` image (if applicable) and `index.md`
- [X] All required fields in my `index.md` conform to the Style Guide and API docs: <https://github.com/github/explore/tree/main/docs>

I consider this section should be curated in order to highlight the research on the matter performed by human rights defenders and activists in developing and promoting whistleblowing technologies like @freedomofpress and @globaleaks, and many others

---

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Review by ahpook — APPROVED** [review]
LGTM, thanks.

**Comment by evilaliv3** [comment]
Thank you @ahpook !

Do you know when this changes will enter into production stage and will be published on https://github.com/topics/whistleblowing ?

**Comment by evilaliv3** [comment]
@ahpook @tomthorogood: for some reasons these changes are still not visualizing on https://github.com/topics/whistleblowing.

Do you know why?

Do you have a tickeing system where i should report this malfunction?
Maybe it applies to other topics as well ?

**Comment by jmeridth** [comment]
@evilaliv3 https://github.com/topics/whistleblowing is showing for me. 🤔

**Comment by evilaliv3** [comment]
Thank you @jmeridth , actually on this repo it is not possible to file issues cause they are disabled.

Maybe @kenyon you could help? thank you

**Comment by kenyon** [comment]
@evilaliv3 I guess you meant to tag @kenyonj.

**Comment by kenyonj** [comment]
> @evilaliv3 
> 
> Nm. I see what you're talking about. Please file an issue on this repository. Thank you for pinging us. 
> 
> 
> ~~https://github.com/topics/whistleblowing is showing for me.~~

@jmeridth issues are currently disabled for this repository. I'll take a look at this on Monday.

**Comment by evilaliv3** [comment]
> @evilaliv3 I guess you meant to tag @kenyonj.
absolutely! thank you :)

**Comment by evilaliv3** [comment]
@jmeridth: This is just a reminder about this possible bug in the codebase possibly affecting other topics.

Thank you!

**Comment by jmeridth** [comment]
@evilaliv3 might have found it.  I was fixing something else and saw [this error talking about whistleblowing short_description missing punctuation](https://github.com/github/explore/actions/runs/11299547064/job/31430715954?pr=4484#step:7:22).  I'm adding now in my current PR.  This may fix it. 🤞

**Comment by jmeridth** [comment]
@evilaliv3 nm.  We removed the period on purpose to force reindexing.  You had it in your original PR.  Still looking.

**Pull request merged**
