### PR TITLE
Add "c++" as an alias to CPP

### PR DESCRIPTION
**Pull request by R4356th**
### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [-] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [-] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [-] Suggesting edits to an existing topic or collection
  - [ ] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---------------------------------------------------------------------

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288)
- [-] Content (and my changes are in `index.md`)

> Many users may use "c++" instead of "cpp" because it is the name of the language.

### CODE REVIEW

**Comment by R4356th** [comment]
I am trying to fix this issue.

**Comment by hedythedev** [comment]
I don't think you can use + in aliases, check out your within action check logs for details

**Comment by R4356th** [comment]
I know that and am working on this.

**Comment by Donna3344** [comment]
What issue

**Review by Donna3344 — COMMENTED** [review]
Donna snowden

**Pull request closed without merging**
