### PR TITLE
add ruff to clean code linters

### PR DESCRIPTION
**Pull request by keksiqc**
An extremely fast Python linter, written in Rust.

### Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: <https://github.com/github/explore/blob/main/CONTRIBUTING.md>.
- [x] I am not the sole author or employee of a company who created either the topic I am modifying/adding or the collection entry I am modifying/adding.

### Which change are you proposing?

  - [x] Suggesting edits to an existing topic or collection
  - [ ] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288, size <= 75 kB)
- [x] Content (and my changes are in `index.md`)

> Ruff is an extremely fast Python linter, that replaces flake8, black and more.

---

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by kenyonj** [comment]
Thank you for your contribution! Currently we are only accepting additions to collection lists with the new item appended to the end of the list. Please make this change and we can merge it in 😄 .

**Review by kenyonj — CHANGES_REQUESTED** [review]
Thank you for your contribution! Currently we are only accepting additions to collection lists with the new item appended to the end of the list. Please make this change and we can merge it in 😄 .

**Comment by keksiqc** [comment]
> Thank you for your contribution! Currently we are only accepting additions to collection lists with the new item appended to the end of the list. Please make this change and we can merge it in 😄 .

Sure thing! I made the necessary adjustments and added the new item to the end of the list.

**Review by ahpook — APPROVED** [review]
LGTM!

**Pull request merged**
