### PR TITLE
Suggesting topic for Jamstack

### PR DESCRIPTION
**Pull request by philhawksworth**
To enrich: https://github.com/topics/jamstack

### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [x] Curating a new topic or collection

---------------------------------------------------------------------

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

> GitHub currently has more than 6,000 repositories labelled "Jamstack", this PR links to jamstack.org which includes definitions of Jamstack and other references and resources.

---------------------------------------------------------------------

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by salgo60** [comment]
* Jamstack on Wikidata [Q57204236](https://www.wikidata.org/wiki/Q57204236)
* I connected it to Github topics [Q57204236#P9100](https://www.wikidata.org/wiki/Q57204236#P9100)
  * see [github.community wikidata-property-p9100-created-for-github-topics](https://github.community/t/wikidata-property-p9100-created-for-github-topics/158508)

**Review by paulcsmith — CHANGES_REQUESTED** [review]
Thanks for contributing! Looks like there is a CI error relating to the image:

```
1) Failure:
topics::jamstack topic#test_0019_has at most one image with the right name, type, and dimensions [/home/runner/work/explore/explore/test/topics_test.rb:229]: topic images should be 288px wide.

  Expected: 288
  Actual: 528
```

Once that's resolved I can take another look

**Comment by philhawksworth** [comment]
oops!

I read "topic images should be 288px wide" as "topic images should **be at least** 288px wide".
My bad. 
Hope this will serve.

Thanks @paulcsmith!

**Review by paulcsmith — APPROVED** [review]
Looks great :D Thanks for your contribution 🥳

**Comment by philhawksworth** [comment]
Thanks for merging this, @paulcsmith!

I don't yet see Jamstack appearing in the [topics listing page](https://github.com/topics) or these details appearing on the [Jamstack topic page](https://github.com/topics/jamstack). 

It has been a couple of days since the PR was merged. Is there anything more I need to do to see this burst into life, or are updates to this scheduled rather than automatic?

**Comment by paulcsmith** [comment]
@philhawksworth Thanks so much! I had to run a task to import the new topics. You should see your changes now!

**Pull request merged**
