### PR TITLE
[Topics update] Curating a new topic ： Pulsar

### PR DESCRIPTION
**Pull request by Tango2018cc**
### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---------------------------------------------------------------------

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288)
- [ ] Content (and my changes are in `index.md`)

> Please replace this line with an explanation of why you think these changes should be made.

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (https://github.com/topics/pulsar)
- [x] My folder contains a `Pulsar.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

Because we need Pulsar's GitHub Topic Page to show it.

### Something that does not neatly fit into the binary options above

- [ ] My suggested edits are not about an existing topic or collection, or at least not a single one
- [ ] My suggested edits are not about curating a new topic or collection, or at least not a single one
- [ ] My suggested edits conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

> Please replace this line with an explanation of your proposed changes.

---------------------------------------------------------------------

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by kenyonj** [comment]
Please replace the main PR body with the template here (https://github.com/github/explore/blob/master/.github/PULL_REQUEST_TEMPLATE.md) and replace/fill out the required areas. Thank you!

**Comment by Tango2018cc** [comment]
the main PR body Has been updated，PTAL

**Review by kenyonj — CHANGES_REQUESTED** [review]
I've edited the main PR body to add the pull request template. Please edit if you need to. There are still CI errors that need to be addressed and then we can review this. 

Thanks!

**Comment by Tango2018cc** [comment]
> I've edited the main PR body to add the pull request template. Please edit if you need to. There are still CI errors that need to be addressed and then we can review this.
> 
> Thanks!

Thanks! I will fix it and then  Submit it.

**Review by jace4511 — APPROVED** [review]

**Review by jace4511 — APPROVED** [review]

**Review by jace4511 — APPROVED** [review]

**Review by jace4511 — APPROVED** [review]

**Review by jace4511 — APPROVED** [review]

**Comment by jace4511** [comment]
> I've edited the main PR body to add the pull request template. Please edit if you need to. There are still CI errors that need to be addressed and then we can review this.
> 
> Thanks!

**Comment by jace4511** [comment]
> I've edited the main PR body to add the pull request template. Please edit if you need to. There are still CI errors that need to be addressed and then we can review this.
> 
> Thanks!

**Review by kenyonj — APPROVED** [review]
Thanks for the contribution and all the changes!

**Pull request merged**
