### PR TITLE
Refer to Linux as a kernel, not operating system

### PR DESCRIPTION
**Pull request by tpimh**
- [X] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md (or at least I hope so)

I am:
  - [X] Suggesting edits to an existing topic or collection
  - [ ] Curating a new topic or collection

***********EDITING AN EXISTING TOPIC OR COLLECTION************

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288)
- [X] Content (and my changes are in `index.md`)

Please explain why these changes are necessary:

The text is referring to Linux as an operating system, but [this repo](https://github.com/torvalds/linux/) only contains the kernel source code. I think my changes to the description are sane and reasonable. If it's not possible to merge these changes for some reason, I'd like to start the discussion about how it should be done the right way.

************CURATING A NEW TOPIC************

- [ ] I've formatted my changes as a new folder directory, named for the topic as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]`)
- [ ] My folder contains a `*.png` image (if applicable) and `index.md`
- [ ] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

Please explain why you think this topic should be curated:

************CURATING A NEW COLLECTION************

- [ ] I've formatted my changes as a new folder directory, named for the collection as it appears in the URL on GitHub (e.g. `https://github.com/collections/[NAME]`)
- [ ] My folder contains a `*.png` image (if applicable) and `index.md`
- [ ] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

Please explain why you think this collection should be curated:

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Check out the use of this topic: https://github.com/topics/linux. Most of it are in reference to Linux the operating system rather than Linux the kernel. As a result I'd close this PR as-is but I'm open to changes with the topic use in mind.

**Comment by tpimh** [comment]
Well, most of the software listed on the page is not related to Linux. It's cross-platform software using all three topics: `linux`, `macos` and `windows`. It would've make much more sense if it was only Linux-specific software listed.
Maybe it's better to have two different topics: `linux` for operating system and `linux-kernel` for the kernel.

**Comment by MikeMcQuaid** [comment]
> Maybe it's better to have two different topics: linux for operating system and linux-kernel for the kernel.

👍 that makes sense to me. You could remove `linux-kernel` from the aliases here.

**Comment by MikeMcQuaid** [comment]
Closing this for now but feel free to open a new PR with discussed changes @tpimh!

**Pull request closed without merging**
