### PR TITLE
Add Coq to the list of programming languages.

### PR DESCRIPTION
**Pull request by Zimmi48**
### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [ ] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [x] Suggesting edits to an existing topic or collection
  - [ ] Curating a new topic or collection

---------------------------------------------------------------------

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288)
- [x] Content (and my changes are in `index.md`)

I am a maintainer of the Coq project, but the contributing guide seems to imply that the "no affiliation" criterion is only relevant when creating a new topic or collection. Note that the Coq topic already exists: https://github.com/topics/coq
I chose the position to insert Coq in the list based on the number of stars.

---------------------------------------------------------------------

### CODE REVIEW

**Comment by kenyonj** [comment]
Hi @Zimmi48 ,
Thanks for starting this pull request. In order to review it for acceptance, we need to make sure that all of the prerequisites are satisfied. I see that you didn't check this:

> I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee)

This is a requirement so that we can maintain a high level of independence in this project. Please update if you are able to verify that you meet that requirement.

Thanks!

**Comment by Zimmi48** [comment]
>I am a maintainer of the Coq project, but the contributing guide seems to imply that the "no affiliation" criterion is only relevant when creating a new topic or collection. Note that the Coq topic already exists: https://github.com/topics/coq

You should probably rephrase your contributing guide then.

**Comment by kenyonj** [comment]
@Zimmi48 thanks for the reply. You raise a good point and I think we should be more clear with our guidance in the contribution docs. 

In light of that, I think I'll open a PR to update it to explicitly only disallow new topics, since the addition of collections doesn't really apply to projects (they are broader than a single project).

Could you edit this PR to add the entry to the end of the list and I can get it merged in once CI passes.

Thank you!

**Comment by Zimmi48** [comment]
@kenyonj I've moved the entry down the list. However, I'd like to highlight the fact that the ordering that is displayed in https://github.com/collections/programming-languages currently feels weird:
1. The ordering is the same as the one in the collection file.
2. Which appears to have initially been based on the number of stars of each project (#484), but numbers have varied since then.

So this results in a list like this:
1. Go (63000 stars)
2. Swift (49000 stars)
3. TypeScript (53000 stars)

And later on:
10. CoffeeScript (15300 stars)
11. Elixir (15800 stars)
12. Crystal (13800 stars)
13. PowerShell (15400 stars)

**Comment by kenyonj** [comment]
> The ordering is the same as the one in the collection file.

That is correct, we currently display only based on the listing order. Collections can contain a few different item types, not just repos. It's on our roadmap to look into a more dynamic way of displaying/sorting the items, but for now, it's only based on the list order.

**Pull request merged**
