### PR TITLE
Add Effector

### PR DESCRIPTION
**Pull request by theghostbel**
### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [x] Suggesting edits to an existing topic or collection
  - [ ] Curating a new topic or collection

Effector is a nice framework to manage state changes for FrontEnd applications. And it fits any UI framework - Angular, React, etc. 

Besides a nice [documentation](https://effector.now.sh/) Effector has a handy [REPL](https://share.effector.dev/) which can be used to share difficult examples with colleges or among developers in [Telegram chat](https://t.me/effector_ru). 

---------------------------------------------------------------------

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by AndMe-me** [comment]
@theghostbel

**Comment by lestad** [comment]
Maybe create a new collection with frontend state-management tools?

**Comment by lestad** [comment]
https://github.com/github/explore/pull/1420

**Comment by kenyonj** [comment]
closed in favor of https://github.com/github/explore/pull/1420

**Pull request closed without merging**
