### PR TITLE
Adds Space Station 13

### PR DESCRIPTION
**Pull request by LetterN**
### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---------------------------------------------------------------------

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

> There are a lot of repositories about SS13, and it would be nice to unify the ss13 tag and space-station-13 tag

---------------------------------------------------------------------

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by LetterN** [comment]
i'l try but i only up-scaled a 64*64 image

**Comment by kenyonj** [comment]
Looks like this image needs to be optimized now, it’s exceeding our 75kb limit.

**Comment by LetterN** [comment]
oh, woops

**Comment by kenyonj** [comment]
Thanks for your work on this ✅👍🏼

**Pull request merged**
