### PR TITLE
Add PWA

### PR DESCRIPTION
**Pull request by abraham**
- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md

I am:
  - [ ] Suggesting edits to an existing Topic page
  - [x] Curating a new Topic page

***********EDITING AN EXISTING TOPIC PAGE************

I'm suggesting these edits to an existing topic:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288)
- [ ] Content (and my changes are in `index.md`)

Please explain why these changes are necessary:

************CURATING A NEW TOPIC PAGE************

- [x] I've formatted my changes as a new folder directory, named for the topic as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

Please explain why you think this Topic page should be curated:

PWAs are rapidly being added to many SPA frameworks out of the box or with starter kits.
- [Angular](https://angular.io/guide/service-worker-intro)
- [Stencil](https://stenciljs.com/pwa/)
- [React](https://github.com/facebook/create-react-app)
- [Vue](https://github.com/vuejs-templates/pwa)

Image is [CC0](https://github.com/webmaxru/progressive-web-apps-logo/issues/4)

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Thanks so much for your contribution! Without people like you submitting PRs we couldn't run this project. You rock, @abraham!

**Comment by abdonrd** [comment]
I'm with @kenchris. Maybe it would be better to remove the `created_by` field.

**Comment by kenchris** [comment]
It would be nice to educate people better though

**Comment by MikeMcQuaid** [comment]
@kenchris Will happily accept PRs to update the `created_by` field.

**Comment by kenchris** [comment]
@MikeMcQuaid Is the best way to just remove the created_by or could we refer to a link, like say wikipedia instead?

**Comment by TalAter** [comment]
I think @kenchris raises a very valid point.

I have created a PR for this (#173) and explained my reasoning in (great) detail.

And let me also thank @abraham for taking the time to create this topic. 🎉 :octocat:

**Comment by abraham** [comment]
Awesome @TalAter!

**Pull request merged**
