### PR TITLE
Remove related topics without repositories from list

### PR DESCRIPTION
**Pull request by shaedrich**
### Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: <https://github.com/github/explore/blob/main/CONTRIBUTING.md>.
- [x] I am not the sole author or employee of a company who created the topic or collection I'm changing.

### Which change are you proposing?

  - [x] Suggesting edits to an existing topic or collection
  - [ ] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288, size <= 75 kB)
- [x] Content (and my changes are in `index.md`)

Follow-up to #4016 ([Check errors](https://github.com/github/explore/actions/runs/6701686893/job/18209492242?pr=4016#check-step-7))
| Topic | Related topic | Status |
| ----- | ------------- | :----: |
| [teamfight-tactic](/topics/teamfight-tactic) | [league-of-legends-wild-rift](/topics/league-of-legends-wild-rift) | &check; |
| [hackathon-kit](/topics/hackathon-kit) | [hackathon-organiser](/topics/hackathon-organiser) | Renamed to [hackathon-organizer](/topics/hackathon-organizer)  |
| [meilisearch](/topics/meilisearch) | [entreprise-search](/topics/entreprise-search) | Renamed to [enterprise-search](/topics/enterprise-search) |
| [riot-games](/topics/riot-games) | [league-of-legends-wild-rift](/topics/league-of-legends-wild-rift) | &check; |
| [ada](/topics/ada) | [ada-stuff](/topics/ada-stuff) | Search results: [0](/search?q=topic%3Aada-stuff&type=repositories), actual: 4 |
| [hackathon](/topics/hackathon) | [hackathon-kit](/topics/hackathon-kit) | No repositories but [curated](/github/explore/blob/main/topics/hackathon-kit/index.md) |
| [valorant](/topics/valorant) | [league-of-legends-wild-rift](/topics/league-of-legends-wild-rift) | &check; |
| [video](/topics/video) | [analog-video](/topics/analog-video) | &check; |
| [motorola-68000](/topics/motorola-68000) | [motorola-6805](/topics/motorola-6805) | Search results: [0](/search?q=topic%3Amotorola-6805&type=repositories), actual: 1 |
| [fantasy-game](/topics/fantasy-game) | [choose-you-own-adventure](/topics/choose-you-own-adventure) | &check; |
| [life-simulator](/topics/life-simulator) | [god-game](/topics/god-game) | No repositories but [curated](/github/explore/blob/main/topics/god-game/index.md) |
| [racing-simulator](/topics/racing-simulator) | [kart-racing](/topics/kart-racing) | No repositories but [curated](/github/explore/blob/main/topics/kart-racing/index.md) |
| [strategy-game](/topics/strategy-game) | [real-time-tactics](/topics/real-time-tactics) | No repositories but [curated](/github/explore/blob/main/topics/real-time-tactics/index.md) |
| [perceptual-hashing](/topics/perceptual-hashing) | [audio-hashing](/topics/audio-hashing) | &check; |
| [hackathon-organiser](/topics/hackathon-organiser) | [hackathon-kit](/topics/hackathon-kit) | No repositories but [curated](/github/explore/blob/main/topics/hackathon-kit/index.md) |
| [umbraco](/topics/umbraco) | [umbraco-headless](/topics/umbraco-headless) | &check; |
| [turn-based-tactics](/topics/turn-based-tactics) | [real-time-tactics](/topics/real-time-tactics) | No repositories but [curated](/github/explore/blob/main/topics/real-time-tactics/index.md) |
| [climate-change-mitigation](/topics/climate-change-mitigation) | [agriculture-and-industry](/topics/agriculture-and-industry) | &check; |
| [league-of-legends](/topics/league-of-legends) | [league-of-legends-wild-rift](/topics/league-of-legends-wild-rift) | &check; |

### Curating a new topic or collection

- [ ] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [ ] My folder contains a `*.png` image (if applicable) and `index.md`
- [ ] All required fields in my `index.md` conform to the Style Guide and API docs: <https://github.com/github/explore/tree/main/docs>

> Please replace this line with an explanation of why you think this topic or collection should be curated.

### Something that does not neatly fit into the binary options above

- [ ] My suggested edits are not about an existing topic or collection, or at least not a single one
- [ ] My suggested edits are not about curating a new topic or collection, or at least not a single one
- [ ] My suggested edits conform to the Style Guide and API docs: https://github.com/github/explore/tree/main/docs

> Please replace this line with an explanation of your proposed changes.

---

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by shaedrich** [comment]
* Should "No repositories but curated" be excluded [in the test](https://github.com/github/explore/blob/772bbdd210f69055fb46d519deae2b4e8e2ba84b/test/topics_test.rb#L165-L171)?
* The question how "Search results: 0, actual: 4" came to be, [has already been asked elsewhere](https://github.com/orgs/community/discussions/67194).

**Review by kenyonj — APPROVED** [review]
This is wonderful! Thank you very much for taking the time to do this 👍🏼

**Comment by shaedrich** [comment]
@kenyonj My pleasure! What are your thoughts on this:
* Should "No repositories but curated" be excluded [in the test](https://github.com/github/explore/blob/772bbdd210f69055fb46d519deae2b4e8e2ba84b/test/topics_test.rb#L165-L171)?
* The question how "Search results: 0, actual: 4" came to be, [has already been asked elsewhere](https://github.com/orgs/community/discussions/67194).

**Comment by kenyonj** [comment]
> * Should "No repositories but curated" be excluded [in the test](https://github.com/github/explore/blob/772bbdd210f69055fb46d519deae2b4e8e2ba84b/test/topics_test.rb#L165-L171)?

Can you elaborate on that question? Can you give me an example topic that falls under this category? 

Would a contrived example be something that is curated to give context to something, like "Poison Ivy From Antarctica", it would describe what it is, but no one happens to be using that on any repository?

If that is an example, I don't think those topics should be curated either. If we started to do that, we'd become more like wikipedia, which we don't want to do.



> * The question of how "Search results: 0, actual: 4" came to be, [has already been asked elsewhere](https://github.com/orgs/community/discussions/67194), but is currently unanswered.

There could be a few different things happening here. Without getting too knee deep in the code that decides what repositories show up on a topic page, there are several pieces of criteria that would hide them: not having any commits, being deleted, but our topics counts in different places haven't re-cached the count... I think those are two reasons that I can think of off the top of my head. All that being said, I don't think we have an answer for this repo other than "we don't curate topics that have an `ACTUAL` count of 0"

**Comment by shaedrich** [comment]
> > * Should "No repositories but curated" be excluded [in the test](https://github.com/github/explore/blob/772bbdd210f69055fb46d519deae2b4e8e2ba84b/test/topics_test.rb#L165-L171)?
> 
> Can you elaborate on that question? Can you give me an example topic that falls under this category?

Yes, all these topics below have been curated despite no repositories having these as topics:

* [hackathon-kit](https://github.com/topics/hackathon-kit)
* [god-game](https://github.com/topics/god-game)
* [kart-racing](https://github.com/topics/kart-racing)
* [real-time-tactics](https://github.com/topics/real-time-tactics)
* [hackathon-kit](https://github.com/topics/hackathon-kit)
* [real-time-tactics](https://github.com/topics/real-time-tactics)

> * The question of how "Search results: 0, actual: 4" came to be, [has already been asked elsewhere](https://github.com/orgs/community/discussions/67194), but is currently unanswered.

Okay, since their `ACTUAL` count is above 0, and they are only related rather than intended to be curated, that should be fine for now. Maybe, I can get the `ACTUAL` value via the GraphQL solution we discussed there: https://github.com/github/explore/pull/4016#pullrequestreview-1715520021

**Comment by kenyonj** [comment]
> The thing is, they are already curated. So what should be done about them, especially regarding the checks from #4016 that would make it mandatory to have > 0 repositories?

I'm of the mindset that these should be removed. I'll bring this question to the rest of the team and see if anyone else has any opinions. Thanks for raising the question!

**Comment by shaedrich** [comment]
Thanks for considering my proposal and discussing it with the team!

**Comment by shaedrich** [comment]
@kenyonj I don't want to bother you, but is there any news yet?

**Pull request merged**
