### PR TITLE
Add Cane programming language

### PR DESCRIPTION
**Pull request by fennecdjay**
### Please confirm this pull request meets the following requirements:

- [X] I followed the contributing guidelines: <https://github.com/github/explore/blob/main/CONTRIBUTING.md>.
- [X] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [X] Suggesting edits to an existing topic or collection
  - [ ] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288, size <= 75 kB)
- [X] Content (and my changes are in `index.md`)

> Cane is a small MIDI sequencer DSL designed around vectors and euclidean rhythms, it's actively maintained and is very useful for livecoding

---

### CODE REVIEW

**Review by octokatherine — CHANGES_REQUESTED** [review]
@fennecdjay I believe CI is failing because you need to append to the end of the list

**Comment by fennecdjay** [comment]
@octokatherine thanks you so much. I saw CI was failing but I did not have the time to investigate.
It looks like you're right.
Trying that right now

**Comment by fennecdjay** [comment]
The tests seem to be passing now :)

**Review by octokatherine — APPROVED** [review]

**Comment by fennecdjay** [comment]
thank you so much. :tada:

**Pull request merged**
