### PR TITLE
Add ABAP topic

### PR DESCRIPTION
**Pull request by mbtools**
### Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: <https://github.com/github/explore/blob/main/CONTRIBUTING.md>.
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: <https://github.com/github/explore/tree/main/docs>

---

The ABAP programming language has been around for decades. It is being used by thousands of companies world-wide and is now undergoing a renaissance in open source projects.  

Globally, there are approx. 5 million registered developers, probably 500,000 active developers ([source](https://community.sap.com/topics/abap/abap-for-newbies)).

### CODE REVIEW

**Review by MikeMcQuaid — CHANGES_REQUESTED** [review]
Thanks for the PR! A few test failures need addressed: https://github.com/github/explore/actions/runs/3819539918/jobs/6503263541#step:6:20

**Comment by mbtools** [comment]
It helps to read instructions properly ;-). I fixed the issues.

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
Thanks so much for your first contribution! Without people like you submitting PRs we couldn't run this project. You rock, @mbtools!

**Comment by mbtools** [comment]
The beauty of open source is that I can do what I just did 😀

**Pull request merged**
