### PR TITLE
Add Sitecore topic.

### PR DESCRIPTION
**Pull request by olegburov**
- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md

I am:
  - [ ] Suggesting edits to an existing Topic page
  - [x] Curating a new Topic page

************CURATING A NEW TOPIC PAGE************

- [x] I've formatted my changes as a new folder directory, named for the topic as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

Please explain why you think this Topic page should be curated:

There are currently 86 open repositories (tools/frameworks/extensions) in Sitecore organization account and even more repositories shared by Sitecore community.

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by nayafia** [comment]
Thanks @olegburov! 👍

**Comment by olegburov** [comment]
@nayafia My please.

BTW, the changes are not visible at https://github.com/topics/sitecore. Is it because you guys haven't pushed to production yet?

**Comment by nayafia** [comment]
@olegburov yep, per: https://github.com/github/explore/blob/master/CONTRIBUTING.md#contributing

> Note: updates won't immediately appear once we've merged your PR. We pull in these changes regularly to GitHub.

It's live now!

**Comment by olegburov** [comment]
Thanks for the update! Indeed I can see it now.

**Pull request merged**
