### PR TITLE
Curate climate-change topic

### PR DESCRIPTION
**Pull request by fxedel**
### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---------------------------------------------------------------------

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

> Climate change affects every person on this planet and is one of the big challenges of our century. There are 347 repositories with the `climate-change` topic. Currently, [Hacktoberfest features the climate-change topic](https://hacktoberfest.digitalocean.com/#featured) amongst the covid-19 topic, which means that the topic is currently shared to a broad audience.

---------------------------------------------------------------------

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by fxedel** [comment]
PS: It would be great if you could add a `hacktoberfest-accepted` label to this PR or the `hacktoberfest` topic to this repository :smiley:

**Comment by BlakeWilliams** [comment]
👋 @fxedel Sorry, but this repo isn't participating in hacktober fest this year.

**Comment by BlakeWilliams** [comment]
@fxedel The topic content looks good, but I'm not sure about the logo. I tried to look it up, but it doesn't seem to be an official logo. If that's the case, could you remove it?

**Comment by fxedel** [comment]
Hey @BlakeWilliams, I used Ed Hawkins' [warming stripes](https://en.wikipedia.org/wiki/Warming_stripes) as a logo. They are not an official logo (how could a phenomenon like climate change even have an official logo?), but have been widely used as a symbol for global warming. Organizations like [Scientists for Future](https://www.scientists4future.org/) and the [United States House Select Committee on the Climate Crisis](https://en.wikipedia.org/wiki/United_States_House_Select_Committee_on_the_Climate_Crisis) have adopted the warming stripes in their logo, it has been in the cover of The Economist and The Guardian and it's a reoccurring symbol in climate change protests and campaings.

Furthermore, the covid-19 GitHub topic also has a logo, whereas the covid-19 pandemic can't have an official logo either.

It'll be great if we could keep the image, as it's very strong connected to climate change and is, in my opinion, the best replacement for an official logo (which doesn't exist). However, if you insist on it, I can also delete the picture.

**Comment by BlakeWilliams** [comment]
@fxedel That makes sense to me, thanks for the contribution! 🎆

**Pull request merged**
