### PR TITLE
Add ImageGoNord repository

### PR DESCRIPTION
**Pull request by federico-terzi**
### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [X] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [X] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [X] Suggesting edits to an existing topic or collection
  - [ ] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---------------------------------------------------------------------

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288)
- [X] Content (and my changes are in `index.md`)

I've added another relevant repository made in italy

### Curating a new topic or collection

- [ ] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [ ] My folder contains a `*.png` image (if applicable) and `index.md`
- [ ] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

> Please replace this line with an explanation of why you think this topic or collection should be curated.

### Something that does not neatly fit into the binary options above

- [ ] My suggested edits are not about an existing topic or collection, or at least not a single one
- [ ] My suggested edits are not about curating a new topic or collection, or at least not a single one
- [ ] My suggested edits conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

> Please replace this line with an explanation of your proposed changes.

---------------------------------------------------------------------

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by krishdevdb** [comment]
Can someone please take a look at this pull request as repeatedly the owners and maintainers are using friends' accounts or false accounts to add their repository to the lost. First on #2278 by a maintainer then #2279 and now #2284

**Comment by federico-terzi** [comment]
@krishdevdb I'm neither a false account (easy to verify by just checking it out) nor I was solicited by them to add the repository.
I do know the maintainers (the developer community in italy is rather small, so this is easier than it sounds), but again am not affiliated with the project in any way, not I was asked to open the PR.

I opened the PR because:
1. The repo is getting reasonably popular (>100) stars, more than some of the repos already listed here
2. It's almost completely made by italians (as far as I know)

I understand your concerns with fairness, but I can't really see how this repo doesn't qualify to being listed

Feel free to ask any other question if you have other doubts :)

**Comment by krishdevdb** [comment]
I just don't have any problem with you adding the repository, but it seems a little suspicious to anyone there who check [github/explore](https://github.com/github/explore)'s pull requests. Because inside of 3 days three pull requests have been made with everything similar. See your PR and #2279 only the description is different (The `Please Replace It With Why You Thing These Changes Should Be Made` thing). #2278 was there with no description and only a few things are marked as done. So all these PRs look like a modified version of each other. That is why I'm suspicious to this PR.

**Comment by federico-terzi** [comment]
@krishdevdb Thank you for the reply, I appreciate your work!

Wasn't I supposed to only change that line? I was strictly following the PR message guidelines.

Besides the PR opened by the maintainers a few days ago, I think this event is more likely a coincidence than a plan to trick the system, given that I wasn't solicited to open the PR...

**Comment by krishdevdb** [comment]
I understand @federico-terzi there was a bunch of people trying to trick the system but you're not one of them. For, that line I wanted to mention that everything except the line was same. But know there's no issue regarding this. Thanks :). By the way I viewed your profile and remembered that I read your [article about github star on github regarding espanso the text editor](https://medium.com/@federicoterzi/the-journey-to-my-first-100-github-stars-aef05d796a18). The article was great.

**Review by krishdevdb — APPROVED** [review]

**Review by MikeMcQuaid — APPROVED** [review]
Thanks so much for your first contribution! Without people like you submitting PRs we couldn't run this project. You rock, @federico-terzi!

**Comment by MikeMcQuaid** [comment]
@krishdevdb I appreciate you are trying to help out on this repository and I admire your enthusiasm but: I need to ask you to stop commenting on the PRs from others unless you are going to help them fix CI failures. If you have any other suggestions for things to help with: ask me or @kenyonj before you get involved.

This repository is maintained exclusively by GitHub employees and we have the final word on what gets included or doesn't. Comments about PRs being "suspicious" (even if they are to you) are unwelcoming to the valued first-time contributors to this repository (like @federico-terzi), make others less likely to wish to contribute and, more generally, are part of what makes open-source contribution intimidating and undesirable for some people.

Again: thanks for your enthusiasm and desire to help and hopefully we can turn things around from now :heart:

**Comment by federico-terzi** [comment]
Thank you very much @MikeMcQuaid! I really admire what you are doing, keep up the great work!

**Comment by MikeMcQuaid** [comment]
Thanks for the kind words @federico-terzi, same to you!

**Pull request merged**
