### PR TITLE
Add Conan topic

### PR DESCRIPTION
**Pull request by uilianries**
### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [X] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [X] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [X] Curating a new topic or collection

---------------------------------------------------------------------

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288)
- [ ] Content (and my changes are in `index.md`)

> Please replace this line with an explanation of why you think these changes should be made.

### Curating a new topic or collection

- [X] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [X] My folder contains a `*.png` image (if applicable) and `index.md`
- [X] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

Conan is becoming the most popular package manager in C++ community. I believe that the new topic will help people to find Conan easier when searching for C and C++ package manager.

Here are some facts:
Github: +2k stars
Slack: +500 people (cpplang.slack.com)

---------------------------------------------------------------------

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by uilianries** [comment]
Thanks @talsafran ! I have contributed to Conan for almost 2 years, but only 1 month ago I was integrated as maintainer :smile_cat:

**Comment by uilianries** [comment]
@talsafran Could you explain why I can't find https://github.com/topics/conan with logo and info? Is there something I should do?

**Comment by memsharded** [comment]
Also, I would expect to find the main repo of the conan tool https://github.com/conan-io/conan, listed there.

**Comment by uilianries** [comment]
It's alive! https://github.com/topics/conan

**Pull request merged**
