### PR TITLE
Add Clojure topic

### PR DESCRIPTION
**Pull request by roman01la**
- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md

I am:
  - [x] Curating a new Topic page

************CURATING A NEW TOPIC PAGE************

- [x] I've formatted my changes as a new folder directory, named for the topic as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

Please explain why you think this Topic page should be curated:

Clojure is a popular programming language

### CODE REVIEW

**Comment by cheshire137** [comment]
Thanks! I like the topic, but there's a test failing currently because the image is a bit small. Could you make the image 288x288? Even if you just add transparent space around it, that'd be fine. 

Would clj make sense as a related topic?

**Comment by roman01la** [comment]
@cheshire137 done! 🙂

**Comment by cheshire137** [comment]
Thanks for the fix! What do you think about adding more detail to the description? Maybe a mention of Clojure being compiled or a functional language, reading from https://clojure.org/. For comparison, here are some of the other language descriptions we have:

https://github.com/github/explore/blob/d336a4b685f26a73b53068a72fd739a7b4391ea4/topics/rust/index.md#L13

https://github.com/github/explore/blob/d336a4b685f26a73b53068a72fd739a7b4391ea4/topics/csharp/index.md#L12

https://github.com/github/explore/blob/d336a4b685f26a73b53068a72fd739a7b4391ea4/topics/go/index.md#L14

**Comment by roman01la** [comment]
@cheshire137 done!

**Pull request merged**
