### PR TITLE
Create topic "IoC"

### PR DESCRIPTION
**Pull request by shaedrich**
### Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: <https://github.com/github/explore/blob/main/CONTRIBUTING.md>.
- [x] I am not the sole author or employee of a company who created the topic or collection I am changing.

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288, size <= 75 kB)
- [ ] Content (and my changes are in `index.md`)

> Please replace this line with an explanation of why you think these changes should be made.

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [ ] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: <https://github.com/github/explore/tree/main/docs>

When you have, for example, dependency injection … well, then you have an implementation of the inversion of control principle

### Something that does not neatly fit into the binary options above

- [ ] My suggested edits are not about an existing topic or collection, or at least not a single one
- [ ] My suggested edits are not about curating a new topic or collection, or at least not a single one
- [ ] My suggested edits conform to the Style Guide and API docs: https://github.com/github/explore/tree/main/docs

> Please replace this line with an explanation of your proposed changes.

---

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by shaedrich** [comment]
> "disambiguation page", that's neat

Actually, this is how Wikipedia handles it in these cases so I thought, we just happen to have these topics above the threshold but there would otherwise be no way of curating them.

> Interesting, did not know about that 1000 repo threshold, but I guess it's sensible

Yeah, this is a bit

grafik

I mean, this is not set in stone but more of a remmendation in terms of likelihood a PR might be approved/rejected. We _do_ actually have topics with less than the threshold that are curated.

[The docs](https://github.com/github/explore/blob/main/CONTRIBUTING.md#curating-a-new-topic-or-collection) say the following:
> We are likely to consider suggestions to curate a topic or collection that is valuable to GitHub's community. Valuable topics, for example, include those that are already [widely used by repositories](https://help.github.com/articles/classifying-your-repository-with-topics/) and could benefit from the addition of important information. When suggesting content, please consider how to make your contribution broadly useful and relevant to others, rather than serving a specific use case.

The number came up a couple times in various PRs like this one: https://github.com/github/explore/pull/3880#issuecomment-1712193494

**Comment by shaedrich** [comment]
> > Since there's neither an "issues" nor a "discussions" tab on this repository, I'm not sure, where to put these kind of feature requests 🤔
> 
> I got no clue .. maybe that's their way of encouraging you to just build it yourself *wink*

yeah, you might be right 😅

**Review by ahpook — APPROVED** [review]

**Comment by shaedrich** [comment]
> This might be a bit off-topic, but maybe of interest to some at GitHub: I thought about this problem multiple times and it would be quite useful if there was a bot who alerted repository owners of better topics for their repositories. […] Since there's neither an "issues" nor a "discussions" tab on this repository, I'm not sure, where to put these kind of feature requests 🤔


> > We are likely to consider suggestions to curate a topic or collection that is valuable to GitHub's community. Valuable topics, for example, include those that are already [widely used by repositories](https://help.github.com/articles/classifying-your-repository-with-topics/) and could benefit from the addition of important information. When suggesting content, please consider how to make your contribution broadly useful and relevant to others, rather than serving a specific use case.
> 
> The number came up a couple of times in various PRs like this one: [#3880 (comment)](https://github.com/github/explore/pull/3880#issuecomment-1712193494)
> 
> Maybe, this could even be added to the tests/check? 🤔

@ahpook **TL;DR:** What's your opinion on these?

**Comment by ahpook** [comment]
> Since there's neither an "issues" nor a "discussions" tab on this repository, I'm not sure, where to put these kind of feature requests 🤔

https://github.com/orgs/community/discussions/categories/feed  is probably the best place for feedback like this

**Comment by shaedrich** [comment]
> > Since there's neither an "issues" nor a "discussions" tab on this repository, I'm not sure, where to put these kind of feature requests 🤔
> 
> https://github.com/orgs/community/discussions/categories/feed is probably the best place for feedback like this

Ah, okay, thanks—I was always wondering about that one 👍🏻  I'll put it out there, than

**Comment by ahpook** [comment]
AFAIK it doesn't really hurt anything (except build times, which we do manually) to have curations for relatively niche topics. The text you quoted is accurate: if contributors are looking for high-value things to add, 1000+ repos is a good indicator. But (obviously) we haven't been rejecting well-formed PRs for low-repo-count topics.

**Comment by shaedrich** [comment]
Thank you for clarifying that 👍🏻 

I suppose, people just don't really have an overview like a to-do list to see, what topic to curate best since [this repository's to-do list](../blob/main/topics-todo.md) is largely done. https://shaedrich.gitlab.io/github-uncurated-topics/contributed-topics.html

**Comment by shaedrich** [comment]
btw, is it just me, or hasn't [the import](https://github.com/github/explore/pull/3980#issuecomment-1762412351) been done in a while? 🤔

**Comment by ahpook** [comment]
I'm going to do it now, it has been a while. Just finished working through the PR backlog...

**Comment by shaedrich** [comment]
Ah, okay. Thanks a lot!

**Comment by ahpook** [comment]
Live now! https://github.com/topics/ioc

**Comment by shaedrich** [comment]
Awesome, thank you :)

**Pull request merged**
