### PR TITLE
Add lean topic

### PR DESCRIPTION
**Pull request by paolobrasolin**
### Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: <https://github.com/github/explore/blob/master/CONTRIBUTING.md>.
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288, size <= 75 kB)
- [ ] Content (and my changes are in `index.md`)

> Please replace this line with an explanation of why you think these changes should be made.

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: <https://github.com/github/explore/tree/master/docs>

> Please replace this line with an explanation of why you think this topic or collection should be curated.

Lean is an innovative theorem prover (and programming language) developed by Microsoft Research.
Its success in industry and academia led to many notable projects, including [Formal Abstracts](https://formalabstracts.github.io/) (which enables computers to read the semantic content of scientific publications) and [Xena Project](https://xenaproject.wordpress.com/what-is-the-xena-project/) (which formalizes the undergraduate math curriculum of the Imperial College).

### Something that does not neatly fit into the binary options above

- [ ] My suggested edits are not about an existing topic or collection, or at least not a single one
- [ ] My suggested edits are not about curating a new topic or collection, or at least not a single one
- [ ] My suggested edits conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

> Please replace this line with an explanation of your proposed changes.

---

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Hey @paolobrasolin! You need to resize the image I'm afraid: https://github.com/github/explore/runs/4384867154?check_suite_focus=true#step:7:411

**Review by MikeMcQuaid — APPROVED** [review]

**Review by MikeMcQuaid — CHANGES_REQUESTED** [review]
Need to fix up the image, otherwise looking good, thanks: https://github.com/github/explore/runs/4384867154?check_suite_focus=true#step:7:412

**Comment by Rangssan** [comment]
bc1qgpz44lmsrhz5fmrq99y7ak6fjpjvfu3a57tq4j

**Review by sv757 — COMMENTED** [review]
هناك مشكله

**Comment by nholden** [comment]
👋  Hi, @paolobrasolin! As Mike mentioned, it looks like you'll need to resize the image in order for CI to pass. As mentioned in the PR template, images need to be 288x288. Once you've made that change, we can take another look at this PR. Thanks!

**Comment by paolobrasolin** [comment]
Thanks @nholden and @MikeMcQuaid!
Sorry for the delay, I just pushed the resized image.

(Also: happy holidays!)

**Review by nholden — APPROVED** [review]

**Comment by Rangssan** [comment]
https://www.paypal.com/invoice/p/#INV2-8LVH-5SRY-KCEG-PJLQ
Competegame with acout Manywllet PayPal Email address
***@***.***

ในวันที่ พฤ. 9 ธ.ค. 2021 06:21 sv757 ***@***.***> เขียนว่า:

**Pull request merged**
