### PR TITLE
Add obofoundry topic

### PR DESCRIPTION
**Pull request by cthoyt**
### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---------------------------------------------------------------------

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

The OBO Foundry is a community and associated infrastructure supporting the creation, review, and maintenance of life science ontologies and best practices.

### CODE REVIEW

**Comment by nlharris** [comment]
Thanks, @cthoyt, I will take a look soon! (I can't add myself as reviewer either.)

**Review by deniseyu — APPROVED** [review]
Thanks for this contribution, @cthoyt! It sounds like you were double-checking about using this copy - I'm happy to merge this as is, but will wait for you to give a 👍🏼

**Review by nlharris — COMMENTED** [review]
I made these comments a while ago but apparently failed to "submit review". these comments may now be out of date.

**Comment by cthoyt** [comment]
@deniseyu thanks for checking in. Looks like we're good to merge :)

**Pull request merged**
