### PR TITLE
Add Streamly to made-in-india collection

### PR DESCRIPTION
**Pull request by weeezes**
### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [x] Suggesting edits to an existing topic or collection
  - [ ] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---------------------------------------------------------------------

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288)
- [x] Content (and my changes are in `index.md`)

Streamly is an impressive Haskell library for building high performance software, built by @harendra-kumar / Composewell from India.

---------------------------------------------------------------------

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Review by mvkaran — APPROVED** [review]
Thanks for your contribution @weeezes!

**Comment by weeezes** [comment]
Thank you :). Fixed merge conflicts.

**Review by Hawkmike — COMMENTED** [review]
Password

**Review by devkadirselcuk — APPROVED** [review]

**Review by devkadirselcuk — APPROVED** [review]

**Comment by weeezes** [comment]
Is there something still missing that's preventing merging this :)? I'm unable to do that myself.

**Pull request merged**
