### PR TITLE
Update Hacktoberfest image with 2019 logo

### PR DESCRIPTION
**Pull request by lex111**
### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [x] Suggesting edits to an existing topic or collection
  - [ ] Curating a new topic or collection

---------------------------------------------------------------------

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [x] Image (and my file is `*.png`, square, dimensions 288x288)
- [ ] Content (and my changes are in `index.md`)

Update Hacktoberfest image with 2019 logo.

### CODE REVIEW

**Comment by kenyonj** [comment]
@lex111 looks like CI is failing because the image needs to be optimized a bit.

**Comment by LeptoSpira** [comment]
This one uses a png, which is not the same one used in the website, I have created a PR that uses the exact `*.svg` used in the website

**Comment by lex111** [comment]
@kenyonj CI passed :heavy_check_mark:

**Comment by lex111** [comment]
@LeptoSpira BTW this image from official event kit.

**Pull request merged**
