### PR TITLE
Add Woodpecker CI (Pipelines) topic

### PR DESCRIPTION
**Pull request by davidak**
### Please confirm this pull request meets the following requirements:

- [X] I followed the contributing guidelines: <https://github.com/github/explore/blob/master/CONTRIBUTING.md>.
- [X] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [X] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---

### Curating a new topic or collection

- [X] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [X] My folder contains a `*.png` image (if applicable) and `index.md`
- [X] All required fields in my `index.md` conform to the Style Guide and API docs: <https://github.com/github/explore/tree/master/docs>

The topic was officially announced by the project. It will be used by users of the software.

https://github.com/woodpecker-ci/woodpecker#who-uses-woodpecker

### CODE REVIEW

**Comment by smashwilson** [comment]
I'm 👍🏻 on this as soon as the CI failures is resolved. It looks like all you'll need to do is rename `woodpecker.png` to `woodpeckerci.png` to match the topic name.

**Comment by davidak** [comment]
Great! I updated the file name.

**Comment by smashwilson** [comment]
Urk, sorry, looks like CI isn't happy about the image dimensions now:

```
  1) Failure:
topics::woodpeckerci topic#test_0019_has at most one image with the right name, type, and dimensions [/home/runner/work/explore/explore/test/topics_test.rb:229]:
topic images should be 288px wide.
Expected: 288
  Actual: 512
```

**Comment by davidak** [comment]
Oh, i haven't seen that there are such strict requirements for the image. Fixed!

**Comment by smashwilson** [comment]
Yeah, we have a ton of tests and linting in place to make sure that things look right on the final topic pages. It's picky and can take some back-and-forth to get everything green, but it keeps everything looking neat (...without us having to remember to check all of it manually). So thanks for having patience with it 😅

**Comment by davidak** [comment]
Yes, automation is great. That's why i like to use Woodpecker CI :smile: 

Now the checks passed! :tada:

**Review by smashwilson — APPROVED** [review]
Oh right I forgot to actually do this. ✅

**Pull request merged**
