### PR TITLE
Add TheAlgorithms organization in Made in India collection

### PR DESCRIPTION
**Pull request by Methro**
### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

- [x] Suggesting edits to an existing topic or collection

---------------------------------------------------------------------

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [x] Content (and my changes are in `index.md`)

> I think this topic should be added because we help each other to build new things, and more. Also, most of their repositories have 10k+ stars, and it teaches people how to learn algorithms, data structures, programming languages, and more.

---------------------------------------------------------------------

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by mvkaran** [comment]
Thanks for your contribution @Methro! This would be a good addition to the collection. Before we add, can you please confirm the basis on which this organization/repos can be termed as 'Made in India'?

**Comment by krishdevdb** [comment]
@mvkaran As per the @TheAlgorithms organization profile. The organization clearly mentions **India** in their **location**.

**Comment by mvkaran** [comment]
Awesome! Thanks, @krishdevdb!

**Review by mvkaran — APPROVED** [review]
LGTM

**Comment by Panquesito7** [comment]
Any reason why this doesn't show up in [Explore](https://github.com/collections/made-in-india)? 😕

**Pull request merged**
