### PR TITLE
Update Go logo to the new brand

### PR DESCRIPTION
**Pull request by emad-elsaid**
- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md

I am:
  - [x] Suggesting edits to an existing topic or collection
  - [x] Unaffiliated with the project (not self-promoting as e.g. a maintainer, creator, contractor or employee)

************EDITING AN EXISTING TOPIC OR COLLECTION************

I'm suggesting these edits to an existing topic or collection:
- [x] Image (and my file is `*.png`, square, dimensions 288x288)

Please explain why these changes are necessary:
Go is going through a rebranding process, the new logo is the Go word
https://blog.golang.org/go-brand

the logo is 288px width image resized from the Go official branding file.

### CODE REVIEW

**Comment by emad-elsaid** [comment]
Travis is failing for the following reason, I'm not sure if this is related to my change at all.

```
  1) Failure:
collections::programming-languages collection#test_0007_fails if a user, organization, or repository has been renamed [/home/travis/build/github/explore/test/collections_test.rb:90]:
Expected ["programming-languages: elm-lang/elm-compiler has been renamed to elm/compiler"] to be empty.
```

**Comment by emad-elsaid** [comment]
Thanks @styline for the approval, so should I fix the test problem? I can rename `elm-lang/elm-compiler` to `elm/compiler` and the test will pass.

**Comment by emad-elsaid** [comment]
@styline I fixed the test problem, but I think the PR needs to be approved again and merged

**Comment by styline** [comment]
Hi I think that's not a question of programmation but a question of authorization on github bases by a usual master. The brand is another problem for the same Logo, isn't it?

**Comment by emad-elsaid** [comment]
I didn't get the question 😃 , well I updated the logo but as the repository tests are failing because elm user/repository was renamed, so I fixed it in the same PR.

**Comment by talsafran** [comment]
@emad-elsaid @styline thanks for the contribution 👍 👍

**Comment by talsafran** [comment]
> I didn't get the question 😃 , well I updated the Go lang logo but as the repository tests are failing because elm user/repository was renamed, so I fixed it in the same PR.

I'm pretty sure `@styline` is a spambot account, I've reported it :/. Sorry for the confusion, and thank you so much for contributing 🙌 ❤️

**Pull request merged**
