### PR TITLE
Add Cirru topic

### PR DESCRIPTION
**Pull request by jiyinyiyong**
### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection

---------------------------------------------------------------------

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288)
- [ ] Content (and my changes are in `index.md`)

> Please replace this line with an explanation of why you think these changes should be made.

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

> Please replace this line with an explanation of why you think this topic or collection should be curated.

---------------------------------------------------------------------

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by chenyong** [comment]
Weird... problems existed in master branch not solved..

```
  1) Failure:
collections::design-essentials collection#test_0007_fails if a user, organization, or repository has been renamed [/home/runner/work/explore/explore/test/collections_test.rb:90]:
Expected ["design-essentials: zurb/foundation-sites has been renamed to foundation/foundation-sites"] to be empty.

  2) Failure:
topics::blockchain topic#test_0019_has no unexpected files or directories [/home/runner/work/explore/explore/test/topics_test.rb:233]:
expected only index.md and a single image.
Expected ["/home/runner/work/explore/explore/topics/blockchain/blockchain-new.png"] to be empty.

  3) Failure:
topics::blockchain topic#test_0018_has at most one image with the right name, type, and dimensions [/home/runner/work/explore/explore/test/topics_test.rb:207]:
expected image to be named [topic].[extension].
Expected: "blockchain"
  Actual: "blockchain-new"

  4) Failure:
topics::tex topic#test_0018_has at most one image with the right name, type, and dimensions [/home/runner/work/explore/explore/test/topics_test.rb:207]:
expected image to be named [topic].[extension].
Expected: "tex"
  Actual: "tex-new"

  5) Failure:
topics::tex topic#test_0019_has no unexpected files or directories [/home/runner/work/explore/explore/test/topics_test.rb:233]:
expected only index.md and a single image.
Expected ["/home/runner/work/explore/explore/topics/tex/tex-new.png"] to be empty.
```

**Comment by kenyonj** [comment]
Hi @chenyong ,
Thanks for starting this pull request. In order to review it for acceptance, we need to make sure that all of the prerequisites are satisfied. I see that you checked this:

> I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee)

This is a requirement so that we can maintain a high level of independence in this project. Please update if you are able to verify that you meet that requirement.

Thanks!

**Comment by jiyinyiyong** [comment]
Updated and unchecked the box.

Sorry I didn't read it clear since not being a native English user. I'm the creator and maintainer of the project Cirru.

What should I do next?

**Comment by kenyonj** [comment]
Hi @jiyinyiyong, unfortunately we require explore additions/edits to be done from members of the community that are not affiliated with the project they are suggesting/editing.

**Comment by jiyinyiyong** [comment]
This rule is a little strange to me... okay.. maybe I need another opportunity.

**Pull request closed without merging**
