### PR TITLE
Add Guild Wars 2 topic

### PR DESCRIPTION
**Pull request by deadpyxel**
### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection

---------------------------------------------------------------------

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

> There have been an increase in the projects of addons, tools and the general developer community around the game has grown. I believe that making it a proper topic is helpful, since we have another games like Kerbal Space Program as a topic.

---------------------------------------------------------------------

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by deadpyxel** [comment]
I'm having trouble understanding the error message from CI:
```
topics::guildwars2 topic#test_0025_follows the Topic Page Style Guide [/home/runner/work/explore/explore/test/topics_test.rb:339]:
Write out "one" and every number less than 10, except when they follow one of: Perl, Pi, Auth, Vision, Java.
Expected ["Perl", "Pi", "Auth", "Vision", "Java"] to include "Wars".
```

**Comment by deadpyxel** [comment]
CI is angry at the Number in the name of the topic, not sure if changes are needed, but let me know if they are.

**Comment by kenyonj** [comment]
> CI is angry at the Number in the name of the topic, not sure if changes are needed, but let me know if they are.

I just removed that test. It seems to cause more problems than it solves right now.

**Comment by deadpyxel** [comment]
I see. Thanks for the collaboration.

**Pull request merged**
