### PR TITLE
Add obsidian-md Topic

### PR DESCRIPTION
**Pull request by SmallPepperZ**
### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---------------------------------------------------------------------

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

Obsidian's 3rd party plugins and themes are shared on GitHub, and I believe it would be helpful to have its website and information on its topic page.

---------------------------------------------------------------------

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by Oneill38** [comment]
@SmallPepperZ looks like there are a few test failures

**Comment by SmallPepperZ** [comment]
@Oneill38, I believe I have resolved the failures for this topic 🤞

**Comment by deniseyu** [comment]
Hi @SmallPepperZ, would you mind hitting the "Update branch" button - the tests should go green after that and I'll be happy to merge this.

**Comment by SmallPepperZ** [comment]
Hi @deniseyu, is that what you wanted me to press?

**Review by deniseyu — APPROVED** [review]

**Comment by deniseyu** [comment]
sorry @SmallPepperZ, that was indeed the correct button, and I actually need you to hit it one more time! We broke main again but it's fixed now 😭

**Pull request merged**
